env:
  browser: true
  es2021: true
  node: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
  - airbnb-base
  - airbnb-typescript/base
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {}
