version: '3.8'
services:
  web:
    # depends_on:
    #   - api
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./next.config.js
          action: rebuild
        - path: ./yarn.lock
          action: rebuild
        - path: .
          target: /app
          action: sync
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - TURBO_TELEMETRY_DISABLED=1
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    ports:
      - 5001:5001
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./yarn.lock
          action: rebuild
        - path: .
          target: /app
          action: sync
    environment:
      - NODE_ENV=production
      - TURBO_TELEMETRY_DISABLED=1
      - DB_URL=mongodb://db/luth
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - luth:/data/db

volumes:
  luth:
