/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/Sides_Collection.glb --transform --types --keepnames --keepmeshes --draco --meta --shadows --exportdefault --instanceall --output ./src/_generated/LuthSides.tsx 
Files: ./public/Sides_Collection.glb [1.4MB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/Sides_Collection-transformed.glb [103.7KB] (93%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body_Heel_Block002: THREE.Mesh
    Body_Tail_Block002: THREE.Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway001: THREE.Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway001: THREE.Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway002: THREE.Mesh
    Body_Lining_Top002: THREE.Mesh
    Body_Lining_Bottom002: THREE.Mesh
    Body_End_Graft_Wedge002: THREE.Mesh
    Body_Sides002: THREE.Mesh
    Body_Sides_Venetian_Cutaway001: THREE.Mesh
    Body_Sides_Florentine_Cutaway001: THREE.Mesh
    Body_Sides_Scalloped_Cutaway001: THREE.Mesh
    Body_Sides_Arm_Bevel001: THREE.Mesh
    Body_Heel_Block003: THREE.Mesh
    Body_Tail_Block003: THREE.Mesh
    Body_Lining_Top003: THREE.Mesh
    Body_Lining_Bottom003: THREE.Mesh
    Body_End_Graft_Wedge003: THREE.Mesh
    Body_Sides003: THREE.Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway003: THREE.Mesh
  }
  materials: {
    ['SBM_FiestaRed.002']: THREE.MeshStandardMaterial
    ['SBW_SBM_FiestaRed.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Sides_Collection-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      BodyHeelBlock: nodes.Body_Heel_Block002,
      BodyTailBlock: nodes.Body_Tail_Block002,
      BodySidesArmBevelFlorentineCutaway: nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway001,
      BodySidesArmBevelVenetianCutaway: nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway001,
      BodySidesArmBevelScallopedCutaway: nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway002,
      BodyLiningTop: nodes.Body_Lining_Top002,
      BodyLiningBottom: nodes.Body_Lining_Bottom002,
      BodyEndGraftWedge: nodes.Body_End_Graft_Wedge002,
      BodySides: nodes.Body_Sides002,
      BodySidesVenetianCutaway: nodes.Body_Sides_Venetian_Cutaway001,
      BodySidesFlorentineCutaway: nodes.Body_Sides_Florentine_Cutaway001,
      BodySidesScallopedCutaway: nodes.Body_Sides_Scalloped_Cutaway001,
      BodySidesArmBevel: nodes.Body_Sides_Arm_Bevel001,
      BodyHeelBlock1: nodes.Body_Heel_Block003,
      BodyTailBlock1: nodes.Body_Tail_Block003,
      BodyLiningTop1: nodes.Body_Lining_Top003,
      BodyLiningBottom1: nodes.Body_Lining_Bottom003,
      BodyEndGraftWedge1: nodes.Body_End_Graft_Wedge003,
      BodySides1: nodes.Body_Sides003,
      BodySidesArmBevelScallopedCutaway1: nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway003,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.BodyHeelBlock
        name="Body_Heel_Block002"
        userData={{ name: 'Body_Heel_Block.002' }}
      />
      <instances.BodyTailBlock
        name="Body_Tail_Block002"
        userData={{ name: 'Body_Tail_Block.002' }}
      />
      <instances.BodySidesArmBevelFlorentineCutaway
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway001"
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway.001' }}
      />
      <instances.BodySidesArmBevelVenetianCutaway
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway001"
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway.001' }}
      />
      <instances.BodySidesArmBevelScallopedCutaway
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway002"
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway.002' }}
      />
      <instances.BodyLiningTop
        name="Body_Lining_Top002"
        userData={{ name: 'Body_Lining_Top.002' }}
      />
      <instances.BodyLiningBottom
        name="Body_Lining_Bottom002"
        userData={{ name: 'Body_Lining_Bottom.002' }}
      />
      <instances.BodyEndGraftWedge
        name="Body_End_Graft_Wedge002"
        userData={{ name: 'Body_End_Graft_Wedge.002' }}
      />
      <instances.BodySides name="Body_Sides002" userData={{ name: 'Body_Sides.002' }} />
      <instances.BodySidesVenetianCutaway
        name="Body_Sides_Venetian_Cutaway001"
        userData={{ name: 'Body_Sides_Venetian_Cutaway.001' }}
      />
      <instances.BodySidesFlorentineCutaway
        name="Body_Sides_Florentine_Cutaway001"
        userData={{ name: 'Body_Sides_Florentine_Cutaway.001' }}
      />
      <instances.BodySidesScallopedCutaway
        name="Body_Sides_Scalloped_Cutaway001"
        userData={{ name: 'Body_Sides_Scalloped_Cutaway.001' }}
      />
      <instances.BodySidesArmBevel
        name="Body_Sides_Arm_Bevel001"
        userData={{ name: 'Body_Sides_Arm_Bevel.001' }}
      />
      <instances.BodyHeelBlock1
        name="Body_Heel_Block003"
        userData={{ name: 'Body_Heel_Block.003' }}
      />
      <instances.BodyTailBlock1
        name="Body_Tail_Block003"
        userData={{ name: 'Body_Tail_Block.003' }}
      />
      <instances.BodyLiningTop1
        name="Body_Lining_Top003"
        userData={{ name: 'Body_Lining_Top.003' }}
      />
      <instances.BodyLiningBottom1
        name="Body_Lining_Bottom003"
        userData={{ name: 'Body_Lining_Bottom.003' }}
      />
      <instances.BodyEndGraftWedge1
        name="Body_End_Graft_Wedge003"
        userData={{ name: 'Body_End_Graft_Wedge.003' }}
      />
      <instances.BodySides1 name="Body_Sides003" userData={{ name: 'Body_Sides.003' }} />
      <instances.BodySidesArmBevelScallopedCutaway1
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway003"
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway.003' }}
      />
    </group>
  )
}

useGLTF.preload('/Sides_Collection-transformed.glb')
