/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/Luth_Soundboard.glb --types --transform --keepnames --keepmeshes --draco --meta --shadows --exportdefault --output ./src/_generated/LuthSoundboard.tsx 
Files: ./public/Luth_Soundboard.glb [47.05MB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/Luth_Soundboard-transformed.glb [442.85KB] (99%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body_Soundboard_Baked: THREE.Mesh
    Body_Soundboard_Venetian_Cutaway_Baked: THREE.Mesh
    Body_Soundboard_Florentine_Cutaway_Baked: THREE.Mesh
    Body_Soundboard_Arm_Bevel_Baked: THREE.Mesh
    Body_Soundboard_Arm_Bevel_Cutaway_Venetian_Baked: THREE.Mesh
    Body_Soundboard_Arm_Bevel_Cutaway_Florentine_Baked: THREE.Mesh
  }
  materials: {
    ['MergedBake_Baked.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Luth_Soundboard-transformed.glb') as GLTFResult

  console.log('materials:', materials)
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Body_Soundboard_Baked"
        castShadow
        receiveShadow
        geometry={nodes.Body_Soundboard_Baked.geometry}
        material={materials['MergedBake_Baked.002']}
        scale={0.01}
        userData={{ name: 'Body_Soundboard_Baked' }}
      />
      <mesh
        name="Body_Soundboard_Venetian_Cutaway_Baked"
        castShadow
        receiveShadow
        geometry={nodes.Body_Soundboard_Venetian_Cutaway_Baked.geometry}
        material={materials['MergedBake_Baked.002']}
        scale={0.01}
        userData={{ name: 'Body_Soundboard_Venetian_Cutaway_Baked' }}
      />
      <mesh
        name="Body_Soundboard_Florentine_Cutaway_Baked"
        castShadow
        receiveShadow
        geometry={nodes.Body_Soundboard_Florentine_Cutaway_Baked.geometry}
        material={materials['MergedBake_Baked.002']}
        scale={0.01}
        userData={{ name: 'Body_Soundboard_Florentine_Cutaway_Baked' }}
      />
      <mesh
        name="Body_Soundboard_Arm_Bevel_Baked"
        castShadow
        receiveShadow
        geometry={nodes.Body_Soundboard_Arm_Bevel_Baked.geometry}
        material={materials['MergedBake_Baked.002']}
        scale={0.01}
        userData={{ name: 'Body_Soundboard_Arm_Bevel_Baked' }}
      />
      <mesh
        name="Body_Soundboard_Arm_Bevel_Cutaway_Venetian_Baked"
        castShadow
        receiveShadow
        geometry={nodes.Body_Soundboard_Arm_Bevel_Cutaway_Venetian_Baked.geometry}
        material={materials['MergedBake_Baked.002']}
        scale={0.01}
        userData={{ name: 'Body_Soundboard_Arm_Bevel_Cutaway_Venetian_Baked' }}
      />
      <mesh
        name="Body_Soundboard_Arm_Bevel_Cutaway_Florentine_Baked"
        castShadow
        receiveShadow
        geometry={nodes.Body_Soundboard_Arm_Bevel_Cutaway_Florentine_Baked.geometry}
        material={materials['MergedBake_Baked.002']}
        scale={0.01}
        userData={{ name: 'Body_Soundboard_Arm_Bevel_Cutaway_Florentine_Baked' }}
      />
    </group>
  )
}

useGLTF.preload('/Luth_Soundboard-transformed.glb')
