/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Purfling_Collection.glb --types --transform --instanceall --keepmeshes --keepmaterials --keepattributes --keepnames --draco --meta --shadows --exportdefault --output ./src/_generated/LuthPurfling.tsx 
Files: ./public/Purfling_Collection.glb [715.41KB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/Purfling_Collection-transformed.glb [66.38KB] (91%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Body_Purfling_Top_CW_Vene_AB_Std: THREE.Mesh
    Purfling_Bottom: THREE.Mesh
    Purfling_Bottom_CW_Flor: THREE.Mesh
    Purfling_Bottom_CW_Vene: THREE.Mesh
    Purfling_Top: THREE.Mesh
    Purfling_Top_CW_Flor: THREE.Mesh
    Purfling_Top_CW_Flor_AB_Std: THREE.Mesh
    Purfling_Top_CW_None_AB_Std: THREE.Mesh
    Purfling_Top_CW_Vene: THREE.Mesh
    Body_Purfling_Top_CW_Vene_AB_Std001: THREE.Mesh
    Purfling_Bottom001: THREE.Mesh
    Purfling_Bottom_CW_Flor001: THREE.Mesh
    Purfling_Bottom_CW_Vene001: THREE.Mesh
    Purfling_Top001: THREE.Mesh
    Purfling_Top_CW_Flor001: THREE.Mesh
    Purfling_Top_CW_Flor_AB_Std001: THREE.Mesh
    Purfling_Top_CW_None_AB_Std001: THREE.Mesh
    Purfling_Top_CW_Vene001: THREE.Mesh
  }
  materials: {
    F_e080eec9735a40a18b3fd669bf364546: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Purfling_Collection-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      BodyPurflingTopCWVeneABStd: nodes.Body_Purfling_Top_CW_Vene_AB_Std,
      PurflingBottom: nodes.Purfling_Bottom,
      PurflingBottomCWFlor: nodes.Purfling_Bottom_CW_Flor,
      PurflingBottomCWVene: nodes.Purfling_Bottom_CW_Vene,
      PurflingTop: nodes.Purfling_Top,
      PurflingTopCWFlor: nodes.Purfling_Top_CW_Flor,
      PurflingTopCWFlorABStd: nodes.Purfling_Top_CW_Flor_AB_Std,
      PurflingTopCWNoneABStd: nodes.Purfling_Top_CW_None_AB_Std,
      PurflingTopCWVene: nodes.Purfling_Top_CW_Vene,
      BodyPurflingTopCWVeneABStd1: nodes.Body_Purfling_Top_CW_Vene_AB_Std001,
      PurflingBottom1: nodes.Purfling_Bottom001,
      PurflingBottomCWFlor1: nodes.Purfling_Bottom_CW_Flor001,
      PurflingBottomCWVene1: nodes.Purfling_Bottom_CW_Vene001,
      PurflingTop1: nodes.Purfling_Top001,
      PurflingTopCWFlor1: nodes.Purfling_Top_CW_Flor001,
      PurflingTopCWFlorABStd1: nodes.Purfling_Top_CW_Flor_AB_Std001,
      PurflingTopCWNoneABStd1: nodes.Purfling_Top_CW_None_AB_Std001,
      PurflingTopCWVene1: nodes.Purfling_Top_CW_Vene001,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.BodyPurflingTopCWVeneABStd name="Body_Purfling_Top_CW_Vene_AB_Std" userData={{ name: 'Body_Purfling_Top_CW_Vene_AB_Std' }} />
      <instances.PurflingBottom name="Purfling_Bottom" userData={{ name: 'Purfling_Bottom' }} />
      <instances.PurflingBottomCWFlor name="Purfling_Bottom_CW_Flor" userData={{ name: 'Purfling_Bottom_CW_Flor' }} />
      <instances.PurflingBottomCWVene name="Purfling_Bottom_CW_Vene" userData={{ name: 'Purfling_Bottom_CW_Vene' }} />
      <instances.PurflingTop name="Purfling_Top" userData={{ name: 'Purfling_Top' }} />
      <instances.PurflingTopCWFlor name="Purfling_Top_CW_Flor" userData={{ name: 'Purfling_Top_CW_Flor' }} />
      <instances.PurflingTopCWFlorABStd name="Purfling_Top_CW_Flor_AB_Std" userData={{ name: 'Purfling_Top_CW_Flor_AB_Std' }} />
      <instances.PurflingTopCWNoneABStd name="Purfling_Top_CW_None_AB_Std" userData={{ name: 'Purfling_Top_CW_None_AB_Std' }} />
      <instances.PurflingTopCWVene name="Purfling_Top_CW_Vene" userData={{ name: 'Purfling_Top_CW_Vene' }} />
      <instances.BodyPurflingTopCWVeneABStd1 name="Body_Purfling_Top_CW_Vene_AB_Std001" userData={{ name: 'Body_Purfling_Top_CW_Vene_AB_Std.001' }} />
      <instances.PurflingBottom1 name="Purfling_Bottom001" userData={{ name: 'Purfling_Bottom.001' }} />
      <instances.PurflingBottomCWFlor1 name="Purfling_Bottom_CW_Flor001" userData={{ name: 'Purfling_Bottom_CW_Flor.001' }} />
      <instances.PurflingBottomCWVene1 name="Purfling_Bottom_CW_Vene001" userData={{ name: 'Purfling_Bottom_CW_Vene.001' }} />
      <instances.PurflingTop1 name="Purfling_Top001" userData={{ name: 'Purfling_Top.001' }} />
      <instances.PurflingTopCWFlor1 name="Purfling_Top_CW_Flor001" userData={{ name: 'Purfling_Top_CW_Flor.001' }} />
      <instances.PurflingTopCWFlorABStd1 name="Purfling_Top_CW_Flor_AB_Std001" userData={{ name: 'Purfling_Top_CW_Flor_AB_Std.001' }} />
      <instances.PurflingTopCWNoneABStd1 name="Purfling_Top_CW_None_AB_Std001" userData={{ name: 'Purfling_Top_CW_None_AB_Std.001' }} />
      <instances.PurflingTopCWVene1 name="Purfling_Top_CW_Vene001" userData={{ name: 'Purfling_Top_CW_Vene.001' }} />
    </group>
  )
}

useGLTF.preload('/Purfling_Collection-transformed.glb')
