/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/luth-acoustic.glb --types --transform --keepnames --keepmeshes --draco --meta --shadows --exportdefault --instanceall --output ./src/_generated/LuthAcoustic.tsx 
Files: ./public/luth-acoustic.glb [8.03MB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/luth-acoustic-transformed.glb [3.11MB] (61%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged, PerspectiveCamera } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body_Heel_Block: THREE.Mesh
    Body_Heel_Block_1: THREE.Mesh
    Body_Heel_Block_2: THREE.Mesh
    Body_Heel_Block_3: THREE.Mesh
    Body_Heel_Block_4: THREE.Mesh
    Body_Heel_Block_5: THREE.Mesh
    Body_Heel_Block_6: THREE.Mesh
    Body_Heel_Block_7: THREE.Mesh
    Body_Heel_Block_8: THREE.Mesh
    Body_Heel_Block_9: THREE.Mesh
    Body_Heel_Block_10: THREE.Mesh
    Body_Heel_Block_11: THREE.Mesh
    Body_Heel_Block_12: THREE.Mesh
    Body_Tail_Block: THREE.Mesh
    Body_Tail_Block_1: THREE.Mesh
    Body_Tail_Block_2: THREE.Mesh
    Body_Tail_Block_3: THREE.Mesh
    Body_Tail_Block_4: THREE.Mesh
    Body_Tail_Block_5: THREE.Mesh
    Body_Lining_Top: THREE.Mesh
    Body_Lining_Top_1: THREE.Mesh
    Body_Lining_Top_2: THREE.Mesh
    Body_Lining_Top_3: THREE.Mesh
    Body_Lining_Top_4: THREE.Mesh
    Body_Lining_Bottom: THREE.Mesh
    Body_Lining_Bottom_1: THREE.Mesh
    Body_Lining_Bottom_2: THREE.Mesh
    Body_Lining_Bottom_3: THREE.Mesh
    Body_Lining_Bottom_4: THREE.Mesh
    Body_End_Graft_Wedge: THREE.Mesh
    Body_End_Graft_Wedge_1: THREE.Mesh
    Body_End_Graft_Wedge_2: THREE.Mesh
    Body_End_Graft_Wedge_3: THREE.Mesh
    Body_End_Graft_Wedge_4: THREE.Mesh
    Body_End_Graft_Wedge_5: THREE.Mesh
    Body_End_Graft_Wedge_6: THREE.Mesh
    Body_End_Graft_Wedge_7: THREE.Mesh
    Body_End_Graft_Wedge_8: THREE.Mesh
    Body_End_Graft_Wedge_9: THREE.Mesh
    Body_Sides: THREE.Mesh
    Body_Sides_1: THREE.Mesh
    Body_Sides_2: THREE.Mesh
    Body_Sides_3: THREE.Mesh
    Body_Sides_4: THREE.Mesh
    Body_Sides_5: THREE.Mesh
    Body_Sides_6: THREE.Mesh
    Body_Sides_7: THREE.Mesh
    Body_Sides_8: THREE.Mesh
    Body_Sides_Venetian_Cutaway: THREE.Mesh
    Body_Sides_Venetian_Cutaway_1: THREE.Mesh
    Body_Sides_Venetian_Cutaway_2: THREE.Mesh
    Body_Sides_Venetian_Cutaway_3: THREE.Mesh
    Body_Sides_Venetian_Cutaway_4: THREE.Mesh
    Body_Sides_Venetian_Cutaway_5: THREE.Mesh
    Body_Sides_Venetian_Cutaway_6: THREE.Mesh
    Body_Sides_Venetian_Cutaway_7: THREE.Mesh
    Body_Sides_Venetian_Cutaway_8: THREE.Mesh
    Body_Sides_Florentine_Cutaway: THREE.Mesh
    Body_Sides_Florentine_Cutaway_1: THREE.Mesh
    Body_Sides_Florentine_Cutaway_2: THREE.Mesh
    Body_Sides_Florentine_Cutaway_3: THREE.Mesh
    Body_Sides_Florentine_Cutaway_4: THREE.Mesh
    Body_Sides_Florentine_Cutaway_5: THREE.Mesh
    Body_Sides_Florentine_Cutaway_6: THREE.Mesh
    Body_Sides_Florentine_Cutaway_7: THREE.Mesh
    Body_Sides_Florentine_Cutaway_8: THREE.Mesh
    Body_Sides_Scalloped_Cutaway: THREE.Mesh
    Body_Sides_Scalloped_Cutaway_1: THREE.Mesh
    Body_Sides_Scalloped_Cutaway_2: THREE.Mesh
    Body_Sides_Scalloped_Cutaway_3: THREE.Mesh
    Body_Sides_Scalloped_Cutaway_4: THREE.Mesh
    Body_Sides_Scalloped_Cutaway_5: THREE.Mesh
    Body_Sides_Scalloped_Cutaway_6: THREE.Mesh
    Body_Sides_Scalloped_Cutaway_7: THREE.Mesh
    Body_Sides_Scalloped_Cutaway_8: THREE.Mesh
    Body_Sides_Scalloped_Cutaway_9: THREE.Mesh
    Body_Sides_Scalloped_Cutaway_10: THREE.Mesh
    Body_Sides_Arm_Bevel: THREE.Mesh
    Body_Sides_Arm_Bevel_1: THREE.Mesh
    Body_Sides_Arm_Bevel_2: THREE.Mesh
    Body_Sides_Arm_Bevel_3: THREE.Mesh
    Body_Sides_Arm_Bevel_4: THREE.Mesh
    Body_Sides_Arm_Bevel_5: THREE.Mesh
    Body_Sides_Arm_Bevel_6: THREE.Mesh
    Body_Sides_Arm_Bevel_7: THREE.Mesh
    Body_Sides_Arm_Bevel_8: THREE.Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway: THREE.Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway_1: THREE.Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway_2: THREE.Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway_3: THREE.Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway_4: THREE.Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway_5: THREE.Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway_6: THREE.Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway_7: THREE.Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway_8: THREE.Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway: THREE.Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway_1: THREE.Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway_2: THREE.Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway_3: THREE.Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway_4: THREE.Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway_5: THREE.Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway_6: THREE.Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway_7: THREE.Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway_8: THREE.Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway: THREE.Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway_1: THREE.Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway_2: THREE.Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway_3: THREE.Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway_4: THREE.Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway_5: THREE.Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway_6: THREE.Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway_7: THREE.Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway_8: THREE.Mesh
    Body_Rosette: THREE.Mesh
    ['Body_Rosette_(1)']: THREE.Mesh
    ['Body_Rosette_(2)']: THREE.Mesh
    ['Body_Rosette_(3)']: THREE.Mesh
    ['Body_Rosette_(4)']: THREE.Mesh
    Body_Brace_Fretboard_Reinforcement_Right: THREE.Mesh
    Body_Lateral_BraceA: THREE.Mesh
    Body_X_BraceB: THREE.Mesh
    Body_X_BraceC: THREE.Mesh
    Body_BraceD: THREE.Mesh
    Body_BraceE: THREE.Mesh
    Body_BraceF_Right: THREE.Mesh
    Body_BraceG_Right: THREE.Mesh
    Body_BraceG_Left: THREE.Mesh
    Body_BraceF_Left: THREE.Mesh
    Body_BraceH_Left: THREE.Mesh
    Body_BraceH_Right: THREE.Mesh
    Body_Bridge_Plate: THREE.Mesh
    Body_Soundboard: THREE.Mesh
    Body_Soundboard_Venetian_Cutaway: THREE.Mesh
    Body_Soundboard_Florentine_Cutaway: THREE.Mesh
    Body_Soundboard_Arm_Bevel: THREE.Mesh
    Body_Soundboard_Arm_Bevel_Cutaway_Venetian: THREE.Mesh
    Body_Soundboard_Arm_Bevel_Cutaway_Florentine: THREE.Mesh
    Body_Saddle: THREE.Mesh
    Body_Bridge_Pin_Inlay: THREE.Mesh
    Body_Bridge_Pin_Inlay_1: THREE.Mesh
    Body_Bridge_Pin_Inlay_2: THREE.Mesh
    Body_Bridge_Pin_Inlay_3: THREE.Mesh
    Body_Bridge_Pin_Inlay_4: THREE.Mesh
    Body_Bridge_Pin_Inlay_5: THREE.Mesh
    Body_Bridge_Pin: THREE.Mesh
    Body_Bridge_Pin_1: THREE.Mesh
    Body_Bridge_Pin_2: THREE.Mesh
    Body_Bridge_Pin_3: THREE.Mesh
    Body_Bridge_Pin_4: THREE.Mesh
    Body_Bridge_Pin_5: THREE.Mesh
    Body_Bridge: THREE.Mesh
    Body_Back_Center_Strip: THREE.Mesh
    ['Body_Back_Double_Strip_Right_(1)']: THREE.Mesh
    Body_Back_Double_Strip_Left: THREE.Mesh
    Body_Center_Back_Strip: THREE.Mesh
    Body_Double_Back_Strip_Left: THREE.Mesh
    Body_Double_Back_Strip_Right: THREE.Mesh
    Body_Back: THREE.Mesh
    Body_Back_Venetian_Cutaway: THREE.Mesh
    Body_Back_Florentine_Cutaway: THREE.Mesh
    Body_Back_Two_Piece_Left: THREE.Mesh
    Body_Back_Two_Piece_Venetian_Cutaway_Left: THREE.Mesh
    Body_Back_Two_Piece_Florentine_Cutaway_Left: THREE.Mesh
    Body_Back_Two_Piece_Right: THREE.Mesh
    Body_Back_Two_Piece_Venetian_Cutaway_Right: THREE.Mesh
    Body_Back_Two_Piece_Florentine_Cutaway_Right: THREE.Mesh
    Body_Back_Three_Piece_Middle: THREE.Mesh
    Body_Back_Three_Piece_Venetian_Cutaway_Middle: THREE.Mesh
    Body_Back_Three_Piece_Florentine_Cutaway_Middle: THREE.Mesh
    Body_Back_Three_Piece_Left: THREE.Mesh
    Body_Back_Three_Piece_Venetian_Cutaway_Left: THREE.Mesh
    Body_Back_Three_Piece_Right: THREE.Mesh
    Body_Back_Three_Piece_Venetian_Cutaway_Right: THREE.Mesh
    Body_Back_Three_Piece_Florentine_Cutaway_Right: THREE.Mesh
    Body_Back_Three_Piece_Florentine_Cutaway_Left: THREE.Mesh
    Body_Fret1: THREE.Mesh
    Body_Fret2: THREE.Mesh
    Body_Fret3: THREE.Mesh
    Body_Fret4: THREE.Mesh
    Body_Fret5: THREE.Mesh
    Body_Fret6: THREE.Mesh
    Body_Fret7: THREE.Mesh
    Body_Fret8: THREE.Mesh
    Body_Fret9: THREE.Mesh
    Body_Fret10: THREE.Mesh
    Body_Fret11: THREE.Mesh
    Body_Fret12: THREE.Mesh
    Body_Fret13: THREE.Mesh
    Body_Fret14: THREE.Mesh
    Body_Fret15: THREE.Mesh
    Body_Fret16: THREE.Mesh
    Body_Fret17: THREE.Mesh
    Body_Fret18: THREE.Mesh
    Body_Fret19: THREE.Mesh
    Body_Fret20: THREE.Mesh
    Body_Nut: THREE.Mesh
    Body_Fretboard: THREE.Mesh
    Body_Fret_Marker_Fret17: THREE.Mesh
    Body_Fret_Marker_Fret21: THREE.Mesh
    Body_Fret_Marker_Fret7: THREE.Mesh
    ['Body_Fret_Marker_Fret12-2']: THREE.Mesh
    Body_Fret_Marker_Fret3: THREE.Mesh
    Body_Fret_Marker_Fret5: THREE.Mesh
    Body_Fret_Marker_Fret15: THREE.Mesh
    ['Body_Fret_Marker_Fret12-1']: THREE.Mesh
    Body_Fret_Marker_Fret9: THREE.Mesh
    ['Body_Fretboard_(1)']: THREE.Mesh
    ['Body_Fretboard_(1)_(2)']: THREE.Mesh
    ['Body_Fretboard_(1)_(3)']: THREE.Mesh
    Body_Side_Fret_Marker_Fret5: THREE.Mesh
    Body_Side_Fret_Marker_Fret7: THREE.Mesh
    Body_Side_Fret_Marker_Fret17: THREE.Mesh
    Body_Side_Fret_Marker_Fret21: THREE.Mesh
    Body_Side_Fret_Marker_Fret3: THREE.Mesh
    Body_Side_Fret_Marker_Fret9: THREE.Mesh
    ['Body_Fretboard_(1)_(1)']: THREE.Mesh
    Body_Fretboard_1: THREE.Mesh
    Body_Fretboard_Soundhole_Tangent: THREE.Mesh
    Surface_Neck_Profile: THREE.Mesh
    Body_Heel: THREE.Mesh
    Body_Neck: THREE.Mesh
    Body_Pickguard: THREE.Mesh
    Peg_Head: THREE.Mesh
    Peg_Head_1: THREE.Mesh
    Peg_Head_2: THREE.Mesh
    Peg_Head_3: THREE.Mesh
    Peg_Head_4: THREE.Mesh
    Peg_Head_5: THREE.Mesh
    Peg_Head_Tuner_Right: THREE.Mesh
    Peg_Head_Tuner_Right_1: THREE.Mesh
    Peg_Head_Tuner_Right_2: THREE.Mesh
    Peg_Head_Tuner_Right_3: THREE.Mesh
    Peg_Head_Tuner_Right_4: THREE.Mesh
    Peg_Head_Tuner_Right_5: THREE.Mesh
    Body_Headstock: THREE.Mesh
    Body_Purfling_Top: THREE.Mesh
    Body_Purfling_Bottom: THREE.Mesh
    Body_Purfling_Top_Venetian_Cutaway: THREE.Mesh
    Body_Purfling_Bottom_Venetian_Cutaway: THREE.Mesh
    Body_Purfling_Top_Florentine_Cutaway: THREE.Mesh
    Body_Purfling_Bottom_Florentine_Cutaway: THREE.Mesh
    Body_Purfling_Top_Arm_Bevel: THREE.Mesh
    Body_Purfling_Top_Arm_Bevel_Florentine_Cutaway: THREE.Mesh
    Body_Purfling_Top_Arm_Bevel_Venetian_Cutaway: THREE.Mesh
    Body_Binding_Top: THREE.Mesh
    Body_Binding_Bottom: THREE.Mesh
    Body_Binding_Top_Venetian_Cutaway: THREE.Mesh
    Body_Binding_Bottom_Venetian_Cutaway: THREE.Mesh
    Body_Binding_Top_Florentine_Cutaway: THREE.Mesh
    Body_Binding_Bottom_Florentine_Cutaway: THREE.Mesh
    Body_Binding_Top_Arm_Bevel: THREE.Mesh
    Body_Binding_Top_Arm_Bevel_Venetian_Cutaway: THREE.Mesh
    Body_Binding_Top_Arm_Bevel_Florentine_Cutaway: THREE.Mesh
    Body_String_LowE: THREE.Mesh
    Body_String_A: THREE.Mesh
    Body_String_D: THREE.Mesh
    Body_String_G: THREE.Mesh
    Body_String_B: THREE.Mesh
    Body_String_HighE: THREE.Mesh
  }
  materials: {
    ['Oak - Glossy']: THREE.MeshStandardMaterial
    ['Oak - Glossy']: THREE.MeshStandardMaterial
    ['Oak - Glossy']: THREE.MeshStandardMaterial
    ['Oak - Glossy']: THREE.MeshStandardMaterial
    ['Oak - Glossy']: THREE.MeshStandardMaterial
    ['Oak - Glossy']: THREE.MeshStandardMaterial
    ['Oak - Glossy']: THREE.MeshStandardMaterial
    ['Oak - Glossy']: THREE.MeshStandardMaterial
    ['Oak - Glossy']: THREE.MeshStandardMaterial
    ['Oak - Glossy']: THREE.MeshStandardMaterial
    ['Oak - Glossy']: THREE.MeshStandardMaterial
    ['Oak - Glossy']: THREE.MeshStandardMaterial
    ['Oak - Glossy']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    Mahogany: THREE.MeshStandardMaterial
    Mahogany: THREE.MeshStandardMaterial
    Mahogany: THREE.MeshStandardMaterial
    Mahogany: THREE.MeshStandardMaterial
    Mahogany: THREE.MeshStandardMaterial
    Mahogany: THREE.MeshStandardMaterial
    Mahogany: THREE.MeshStandardMaterial
    Mahogany: THREE.MeshStandardMaterial
    Mahogany: THREE.MeshStandardMaterial
    Mahogany: THREE.MeshStandardMaterial
    Mahogany: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['Acrylic (Red)']: THREE.MeshStandardMaterial
    ['Acrylic (Red)']: THREE.MeshStandardMaterial
    ['Acrylic (Red)']: THREE.MeshStandardMaterial
    ['Acrylic (Red)']: THREE.MeshStandardMaterial
    ['Acrylic (Red)']: THREE.MeshStandardMaterial
    ['Acrylic (Red)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['Plastic - Glossy (Black)']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['Plastic - Glossy (Black)']: THREE.MeshStandardMaterial
    ['Plastic - Glossy (Black)']: THREE.MeshStandardMaterial
    ['Plastic - Glossy (Black)']: THREE.MeshStandardMaterial
    ['Plastic - Glossy (Black)']: THREE.MeshStandardMaterial
    ['Plastic - Glossy (Black)']: THREE.MeshStandardMaterial
    ['Plastic - Glossy (Black)']: THREE.MeshStandardMaterial
    ['Plastic - Glossy (Black)']: THREE.MeshStandardMaterial
    ['Plastic - Glossy (Black)']: THREE.MeshStandardMaterial
    ['Plastic - Glossy (Black)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/luth-acoustic-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      BodyHeelBlock: nodes.Body_Heel_Block,
      BodyHeelBlock1: nodes.Body_Heel_Block_1,
      BodyHeelBlock2: nodes.Body_Heel_Block_2,
      BodyHeelBlock3: nodes.Body_Heel_Block_3,
      BodyHeelBlock4: nodes.Body_Heel_Block_4,
      BodyHeelBlock5: nodes.Body_Heel_Block_5,
      BodyHeelBlock6: nodes.Body_Heel_Block_6,
      BodyHeelBlock7: nodes.Body_Heel_Block_7,
      BodyHeelBlock8: nodes.Body_Heel_Block_8,
      BodyHeelBlock9: nodes.Body_Heel_Block_9,
      BodyHeelBlock10: nodes.Body_Heel_Block_10,
      BodyHeelBlock11: nodes.Body_Heel_Block_11,
      BodyHeelBlock12: nodes.Body_Heel_Block_12,
      BodyTailBlock: nodes.Body_Tail_Block,
      BodyTailBlock1: nodes.Body_Tail_Block_1,
      BodyTailBlock2: nodes.Body_Tail_Block_2,
      BodyTailBlock3: nodes.Body_Tail_Block_3,
      BodyTailBlock4: nodes.Body_Tail_Block_4,
      BodyTailBlock5: nodes.Body_Tail_Block_5,
      BodyLiningTop: nodes.Body_Lining_Top,
      BodyLiningTop1: nodes.Body_Lining_Top_1,
      BodyLiningTop2: nodes.Body_Lining_Top_2,
      BodyLiningTop3: nodes.Body_Lining_Top_3,
      BodyLiningTop4: nodes.Body_Lining_Top_4,
      BodyLiningBottom: nodes.Body_Lining_Bottom,
      BodyLiningBottom1: nodes.Body_Lining_Bottom_1,
      BodyLiningBottom2: nodes.Body_Lining_Bottom_2,
      BodyLiningBottom3: nodes.Body_Lining_Bottom_3,
      BodyLiningBottom4: nodes.Body_Lining_Bottom_4,
      BodyEndGraftWedge: nodes.Body_End_Graft_Wedge,
      BodyEndGraftWedge1: nodes.Body_End_Graft_Wedge_1,
      BodyEndGraftWedge2: nodes.Body_End_Graft_Wedge_2,
      BodyEndGraftWedge3: nodes.Body_End_Graft_Wedge_3,
      BodyEndGraftWedge4: nodes.Body_End_Graft_Wedge_4,
      BodyEndGraftWedge5: nodes.Body_End_Graft_Wedge_5,
      BodyEndGraftWedge6: nodes.Body_End_Graft_Wedge_6,
      BodyEndGraftWedge7: nodes.Body_End_Graft_Wedge_7,
      BodyEndGraftWedge8: nodes.Body_End_Graft_Wedge_8,
      BodyEndGraftWedge9: nodes.Body_End_Graft_Wedge_9,
      BodySides: nodes.Body_Sides,
      BodySides1: nodes.Body_Sides_1,
      BodySides2: nodes.Body_Sides_2,
      BodySides3: nodes.Body_Sides_3,
      BodySides4: nodes.Body_Sides_4,
      BodySides5: nodes.Body_Sides_5,
      BodySides6: nodes.Body_Sides_6,
      BodySides7: nodes.Body_Sides_7,
      BodySides8: nodes.Body_Sides_8,
      BodySidesVenetianCutaway: nodes.Body_Sides_Venetian_Cutaway,
      BodySidesVenetianCutaway1: nodes.Body_Sides_Venetian_Cutaway_1,
      BodySidesVenetianCutaway2: nodes.Body_Sides_Venetian_Cutaway_2,
      BodySidesVenetianCutaway3: nodes.Body_Sides_Venetian_Cutaway_3,
      BodySidesVenetianCutaway4: nodes.Body_Sides_Venetian_Cutaway_4,
      BodySidesVenetianCutaway5: nodes.Body_Sides_Venetian_Cutaway_5,
      BodySidesVenetianCutaway6: nodes.Body_Sides_Venetian_Cutaway_6,
      BodySidesVenetianCutaway7: nodes.Body_Sides_Venetian_Cutaway_7,
      BodySidesVenetianCutaway8: nodes.Body_Sides_Venetian_Cutaway_8,
      BodySidesFlorentineCutaway: nodes.Body_Sides_Florentine_Cutaway,
      BodySidesFlorentineCutaway1: nodes.Body_Sides_Florentine_Cutaway_1,
      BodySidesFlorentineCutaway2: nodes.Body_Sides_Florentine_Cutaway_2,
      BodySidesFlorentineCutaway3: nodes.Body_Sides_Florentine_Cutaway_3,
      BodySidesFlorentineCutaway4: nodes.Body_Sides_Florentine_Cutaway_4,
      BodySidesFlorentineCutaway5: nodes.Body_Sides_Florentine_Cutaway_5,
      BodySidesFlorentineCutaway6: nodes.Body_Sides_Florentine_Cutaway_6,
      BodySidesFlorentineCutaway7: nodes.Body_Sides_Florentine_Cutaway_7,
      BodySidesFlorentineCutaway8: nodes.Body_Sides_Florentine_Cutaway_8,
      BodySidesScallopedCutaway: nodes.Body_Sides_Scalloped_Cutaway,
      BodySidesScallopedCutaway1: nodes.Body_Sides_Scalloped_Cutaway_1,
      BodySidesScallopedCutaway2: nodes.Body_Sides_Scalloped_Cutaway_2,
      BodySidesScallopedCutaway3: nodes.Body_Sides_Scalloped_Cutaway_3,
      BodySidesScallopedCutaway4: nodes.Body_Sides_Scalloped_Cutaway_4,
      BodySidesScallopedCutaway5: nodes.Body_Sides_Scalloped_Cutaway_5,
      BodySidesScallopedCutaway6: nodes.Body_Sides_Scalloped_Cutaway_6,
      BodySidesScallopedCutaway7: nodes.Body_Sides_Scalloped_Cutaway_7,
      BodySidesScallopedCutaway8: nodes.Body_Sides_Scalloped_Cutaway_8,
      BodySidesScallopedCutaway9: nodes.Body_Sides_Scalloped_Cutaway_9,
      BodySidesScallopedCutaway10: nodes.Body_Sides_Scalloped_Cutaway_10,
      BodySidesArmBevel: nodes.Body_Sides_Arm_Bevel,
      BodySidesArmBevel1: nodes.Body_Sides_Arm_Bevel_1,
      BodySidesArmBevel2: nodes.Body_Sides_Arm_Bevel_2,
      BodySidesArmBevel3: nodes.Body_Sides_Arm_Bevel_3,
      BodySidesArmBevel4: nodes.Body_Sides_Arm_Bevel_4,
      BodySidesArmBevel5: nodes.Body_Sides_Arm_Bevel_5,
      BodySidesArmBevel6: nodes.Body_Sides_Arm_Bevel_6,
      BodySidesArmBevel7: nodes.Body_Sides_Arm_Bevel_7,
      BodySidesArmBevel8: nodes.Body_Sides_Arm_Bevel_8,
      BodySidesArmBevelFlorentineCutaway: nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway,
      BodySidesArmBevelFlorentineCutaway1: nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway_1,
      BodySidesArmBevelFlorentineCutaway2: nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway_2,
      BodySidesArmBevelFlorentineCutaway3: nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway_3,
      BodySidesArmBevelFlorentineCutaway4: nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway_4,
      BodySidesArmBevelFlorentineCutaway5: nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway_5,
      BodySidesArmBevelFlorentineCutaway6: nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway_6,
      BodySidesArmBevelFlorentineCutaway7: nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway_7,
      BodySidesArmBevelFlorentineCutaway8: nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway_8,
      BodySidesArmBevelVenetianCutaway: nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway,
      BodySidesArmBevelVenetianCutaway1: nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway_1,
      BodySidesArmBevelVenetianCutaway2: nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway_2,
      BodySidesArmBevelVenetianCutaway3: nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway_3,
      BodySidesArmBevelVenetianCutaway4: nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway_4,
      BodySidesArmBevelVenetianCutaway5: nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway_5,
      BodySidesArmBevelVenetianCutaway6: nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway_6,
      BodySidesArmBevelVenetianCutaway7: nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway_7,
      BodySidesArmBevelVenetianCutaway8: nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway_8,
      BodySidesArmBevelScallopedCutaway: nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway,
      BodySidesArmBevelScallopedCutaway1: nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway_1,
      BodySidesArmBevelScallopedCutaway2: nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway_2,
      BodySidesArmBevelScallopedCutaway3: nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway_3,
      BodySidesArmBevelScallopedCutaway4: nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway_4,
      BodySidesArmBevelScallopedCutaway5: nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway_5,
      BodySidesArmBevelScallopedCutaway6: nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway_6,
      BodySidesArmBevelScallopedCutaway7: nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway_7,
      BodySidesArmBevelScallopedCutaway8: nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway_8,
      BodyRosette: nodes.Body_Rosette,
      BodyRosette1: nodes['Body_Rosette_(1)'],
      BodyRosette2: nodes['Body_Rosette_(2)'],
      BodyRosette3: nodes['Body_Rosette_(3)'],
      BodyRosette4: nodes['Body_Rosette_(4)'],
      BodyBraceFretboardReinforcementRight: nodes.Body_Brace_Fretboard_Reinforcement_Right,
      BodyLateralBraceA: nodes.Body_Lateral_BraceA,
      BodyXBraceB: nodes.Body_X_BraceB,
      BodyXBraceC: nodes.Body_X_BraceC,
      BodyBraceD: nodes.Body_BraceD,
      BodyBraceE: nodes.Body_BraceE,
      BodyBraceFRight: nodes.Body_BraceF_Right,
      BodyBraceGRight: nodes.Body_BraceG_Right,
      BodyBraceGLeft: nodes.Body_BraceG_Left,
      BodyBraceFLeft: nodes.Body_BraceF_Left,
      BodyBraceHLeft: nodes.Body_BraceH_Left,
      BodyBraceHRight: nodes.Body_BraceH_Right,
      BodyBridgePlate: nodes.Body_Bridge_Plate,
      BodySoundboard: nodes.Body_Soundboard,
      BodySoundboardVenetianCutaway: nodes.Body_Soundboard_Venetian_Cutaway,
      BodySoundboardFlorentineCutaway: nodes.Body_Soundboard_Florentine_Cutaway,
      BodySoundboardArmBevel: nodes.Body_Soundboard_Arm_Bevel,
      BodySoundboardArmBevelCutawayVenetian: nodes.Body_Soundboard_Arm_Bevel_Cutaway_Venetian,
      BodySoundboardArmBevelCutawayFlorentine: nodes.Body_Soundboard_Arm_Bevel_Cutaway_Florentine,
      BodySaddle: nodes.Body_Saddle,
      BodyBridgePinInlay: nodes.Body_Bridge_Pin_Inlay,
      BodyBridgePin: nodes.Body_Bridge_Pin,
      BodyBridge: nodes.Body_Bridge,
      BodyBackCenterStrip: nodes.Body_Back_Center_Strip,
      BodyBackDoubleStripRight: nodes['Body_Back_Double_Strip_Right_(1)'],
      BodyBackDoubleStripLeft: nodes.Body_Back_Double_Strip_Left,
      BodyCenterBackStrip: nodes.Body_Center_Back_Strip,
      BodyDoubleBackStripLeft: nodes.Body_Double_Back_Strip_Left,
      BodyDoubleBackStripRight: nodes.Body_Double_Back_Strip_Right,
      BodyBack: nodes.Body_Back,
      BodyBackVenetianCutaway: nodes.Body_Back_Venetian_Cutaway,
      BodyBackFlorentineCutaway: nodes.Body_Back_Florentine_Cutaway,
      BodyBackTwoPieceLeft: nodes.Body_Back_Two_Piece_Left,
      BodyBackTwoPieceRight: nodes.Body_Back_Two_Piece_Right,
      BodyBackTwoPieceVenetianCutawayRight: nodes.Body_Back_Two_Piece_Venetian_Cutaway_Right,
      BodyBackTwoPieceFlorentineCutawayRight: nodes.Body_Back_Two_Piece_Florentine_Cutaway_Right,
      BodyBackThreePieceMiddle: nodes.Body_Back_Three_Piece_Middle,
      BodyBackThreePieceVenetianCutawayMiddle: nodes.Body_Back_Three_Piece_Venetian_Cutaway_Middle,
      BodyBackThreePieceFlorentineCutawayMiddle:
        nodes.Body_Back_Three_Piece_Florentine_Cutaway_Middle,
      BodyBackThreePieceLeft: nodes.Body_Back_Three_Piece_Left,
      BodyBackThreePieceRight: nodes.Body_Back_Three_Piece_Right,
      BodyBackThreePieceVenetianCutawayRight: nodes.Body_Back_Three_Piece_Venetian_Cutaway_Right,
      BodyBackThreePieceFlorentineCutawayRight:
        nodes.Body_Back_Three_Piece_Florentine_Cutaway_Right,
      BodyBackThreePieceFlorentineCutawayLeft: nodes.Body_Back_Three_Piece_Florentine_Cutaway_Left,
      BodyFret: nodes.Body_Fret1,
      BodyFret1: nodes.Body_Fret2,
      BodyFret2: nodes.Body_Fret3,
      BodyFret3: nodes.Body_Fret4,
      BodyFret4: nodes.Body_Fret5,
      BodyFret5: nodes.Body_Fret6,
      BodyFret6: nodes.Body_Fret7,
      BodyFret7: nodes.Body_Fret8,
      BodyFret8: nodes.Body_Fret9,
      BodyFret9: nodes.Body_Fret10,
      BodyFret10: nodes.Body_Fret11,
      BodyFret11: nodes.Body_Fret12,
      BodyFret12: nodes.Body_Fret13,
      BodyFret13: nodes.Body_Fret14,
      BodyFret14: nodes.Body_Fret15,
      BodyFret15: nodes.Body_Fret16,
      BodyFret16: nodes.Body_Fret17,
      BodyFret17: nodes.Body_Fret18,
      BodyFret18: nodes.Body_Fret19,
      BodyFret19: nodes.Body_Fret20,
      BodyNut: nodes.Body_Nut,
      BodyFretboard: nodes.Body_Fretboard,
      BodyFretMarkerFret: nodes.Body_Fret_Marker_Fret17,
      BodyFretMarkerFret1: nodes.Body_Fret_Marker_Fret21,
      BodyFretMarkerFret2: nodes.Body_Fret_Marker_Fret7,
      BodyFretMarkerFret3: nodes['Body_Fret_Marker_Fret12-2'],
      BodyFretMarkerFret4: nodes.Body_Fret_Marker_Fret3,
      BodyFretMarkerFret5: nodes.Body_Fret_Marker_Fret5,
      BodyFretMarkerFret6: nodes.Body_Fret_Marker_Fret15,
      BodyFretMarkerFret7: nodes['Body_Fret_Marker_Fret12-1'],
      BodyFretMarkerFret8: nodes.Body_Fret_Marker_Fret9,
      BodyFretboard1: nodes['Body_Fretboard_(1)'],
      BodyFretboard2: nodes['Body_Fretboard_(1)_(2)'],
      BodyFretboard3: nodes['Body_Fretboard_(1)_(3)'],
      BodySideFretMarkerFret: nodes.Body_Side_Fret_Marker_Fret5,
      BodySideFretMarkerFret1: nodes.Body_Side_Fret_Marker_Fret7,
      BodySideFretMarkerFret2: nodes.Body_Side_Fret_Marker_Fret17,
      BodySideFretMarkerFret3: nodes.Body_Side_Fret_Marker_Fret21,
      BodySideFretMarkerFret4: nodes.Body_Side_Fret_Marker_Fret3,
      BodySideFretMarkerFret5: nodes.Body_Side_Fret_Marker_Fret9,
      BodyFretboard4: nodes['Body_Fretboard_(1)_(1)'],
      BodyFretboard5: nodes.Body_Fretboard_1,
      BodyFretboardSoundholeTangent: nodes.Body_Fretboard_Soundhole_Tangent,
      SurfaceNeckProfile: nodes.Surface_Neck_Profile,
      BodyHeel: nodes.Body_Heel,
      BodyNeck: nodes.Body_Neck,
      BodyPickguard: nodes.Body_Pickguard,
      PegHead: nodes.Peg_Head,
      PegHeadTunerRight: nodes.Peg_Head_Tuner_Right,
      BodyHeadstock: nodes.Body_Headstock,
      BodyPurflingTop: nodes.Body_Purfling_Top,
      BodyPurflingBottom: nodes.Body_Purfling_Bottom,
      BodyPurflingTopVenetianCutaway: nodes.Body_Purfling_Top_Venetian_Cutaway,
      BodyPurflingBottomVenetianCutaway: nodes.Body_Purfling_Bottom_Venetian_Cutaway,
      BodyPurflingTopFlorentineCutaway: nodes.Body_Purfling_Top_Florentine_Cutaway,
      BodyPurflingBottomFlorentineCutaway: nodes.Body_Purfling_Bottom_Florentine_Cutaway,
      BodyPurflingTopArmBevel: nodes.Body_Purfling_Top_Arm_Bevel,
      BodyPurflingTopArmBevelFlorentineCutaway:
        nodes.Body_Purfling_Top_Arm_Bevel_Florentine_Cutaway,
      BodyPurflingTopArmBevelVenetianCutaway: nodes.Body_Purfling_Top_Arm_Bevel_Venetian_Cutaway,
      BodyBindingTop: nodes.Body_Binding_Top,
      BodyBindingBottom: nodes.Body_Binding_Bottom,
      BodyBindingTopVenetianCutaway: nodes.Body_Binding_Top_Venetian_Cutaway,
      BodyBindingBottomVenetianCutaway: nodes.Body_Binding_Bottom_Venetian_Cutaway,
      BodyBindingTopFlorentineCutaway: nodes.Body_Binding_Top_Florentine_Cutaway,
      BodyBindingBottomFlorentineCutaway: nodes.Body_Binding_Bottom_Florentine_Cutaway,
      BodyBindingTopArmBevel: nodes.Body_Binding_Top_Arm_Bevel,
      BodyBindingTopArmBevelVenetianCutaway: nodes.Body_Binding_Top_Arm_Bevel_Venetian_Cutaway,
      BodyBindingTopArmBevelFlorentineCutaway: nodes.Body_Binding_Top_Arm_Bevel_Florentine_Cutaway,
      BodyStringLowE: nodes.Body_String_LowE,
      BodyStringA: nodes.Body_String_A,
      BodyStringD: nodes.Body_String_D,
      BodyStringG: nodes.Body_String_G,
      BodyStringB: nodes.Body_String_B,
      BodyStringHighE: nodes.Body_String_HighE,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        name="active"
        makeDefault={false}
        far={1878.367}
        near={838.397}
        fov={22.62}
        position={[0.474, -1.033, -0.543]}
        rotation={[2.09, 0.368, -3.088]}
        scale={0.001}
        userData={{ name: 'active' }}
      />
      <PerspectiveCamera
        name="Active_Camera"
        makeDefault={false}
        far={1878.367}
        near={838.397}
        fov={22.62}
        position={[0.474, -1.033, -0.543]}
        rotation={[2.09, 0.368, -3.088]}
        scale={0.001}
        userData={{ name: 'Active Camera' }}
      />
      <instances.BodyHeelBlock
        name="Body_Heel_Block"
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <instances.BodyHeelBlock1
        name="Body_Heel_Block_1"
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <instances.BodyHeelBlock2
        name="Body_Heel_Block_2"
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <instances.BodyHeelBlock3
        name="Body_Heel_Block_3"
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <instances.BodyHeelBlock4
        name="Body_Heel_Block_4"
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <instances.BodyHeelBlock5
        name="Body_Heel_Block_5"
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <instances.BodyHeelBlock6
        name="Body_Heel_Block_6"
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <instances.BodyHeelBlock7
        name="Body_Heel_Block_7"
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <instances.BodyHeelBlock8
        name="Body_Heel_Block_8"
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <instances.BodyHeelBlock9
        name="Body_Heel_Block_9"
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <instances.BodyHeelBlock10
        name="Body_Heel_Block_10"
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <instances.BodyHeelBlock11
        name="Body_Heel_Block_11"
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <instances.BodyHeelBlock12
        name="Body_Heel_Block_12"
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <instances.BodyTailBlock
        name="Body_Tail_Block"
        scale={0.001}
        userData={{ name: 'Body_Tail_Block' }}
      />
      <instances.BodyTailBlock1
        name="Body_Tail_Block_1"
        scale={0.001}
        userData={{ name: 'Body_Tail_Block' }}
      />
      <instances.BodyTailBlock2
        name="Body_Tail_Block_2"
        scale={0.001}
        userData={{ name: 'Body_Tail_Block' }}
      />
      <instances.BodyTailBlock3
        name="Body_Tail_Block_3"
        scale={0.001}
        userData={{ name: 'Body_Tail_Block' }}
      />
      <instances.BodyTailBlock4
        name="Body_Tail_Block_4"
        scale={0.001}
        userData={{ name: 'Body_Tail_Block' }}
      />
      <instances.BodyTailBlock5
        name="Body_Tail_Block_5"
        scale={0.001}
        userData={{ name: 'Body_Tail_Block' }}
      />
      <instances.BodyLiningTop
        name="Body_Lining_Top"
        scale={0.001}
        userData={{ name: 'Body_Lining_Top' }}
      />
      <instances.BodyLiningTop1
        name="Body_Lining_Top_1"
        scale={0.001}
        userData={{ name: 'Body_Lining_Top' }}
      />
      <instances.BodyLiningTop2
        name="Body_Lining_Top_2"
        scale={0.001}
        userData={{ name: 'Body_Lining_Top' }}
      />
      <instances.BodyLiningTop3
        name="Body_Lining_Top_3"
        scale={0.001}
        userData={{ name: 'Body_Lining_Top' }}
      />
      <instances.BodyLiningTop4
        name="Body_Lining_Top_4"
        scale={0.001}
        userData={{ name: 'Body_Lining_Top' }}
      />
      <instances.BodyLiningBottom
        name="Body_Lining_Bottom"
        scale={0.001}
        userData={{ name: 'Body_Lining_Bottom' }}
      />
      <instances.BodyLiningBottom1
        name="Body_Lining_Bottom_1"
        scale={0.001}
        userData={{ name: 'Body_Lining_Bottom' }}
      />
      <instances.BodyLiningBottom2
        name="Body_Lining_Bottom_2"
        scale={0.001}
        userData={{ name: 'Body_Lining_Bottom' }}
      />
      <instances.BodyLiningBottom3
        name="Body_Lining_Bottom_3"
        scale={0.001}
        userData={{ name: 'Body_Lining_Bottom' }}
      />
      <instances.BodyLiningBottom4
        name="Body_Lining_Bottom_4"
        scale={0.001}
        userData={{ name: 'Body_Lining_Bottom' }}
      />
      <instances.BodyEndGraftWedge
        name="Body_End_Graft_Wedge"
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <instances.BodyEndGraftWedge1
        name="Body_End_Graft_Wedge_1"
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <instances.BodyEndGraftWedge2
        name="Body_End_Graft_Wedge_2"
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <instances.BodyEndGraftWedge3
        name="Body_End_Graft_Wedge_3"
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <instances.BodyEndGraftWedge4
        name="Body_End_Graft_Wedge_4"
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <instances.BodyEndGraftWedge5
        name="Body_End_Graft_Wedge_5"
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <instances.BodyEndGraftWedge6
        name="Body_End_Graft_Wedge_6"
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <instances.BodyEndGraftWedge7
        name="Body_End_Graft_Wedge_7"
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <instances.BodyEndGraftWedge8
        name="Body_End_Graft_Wedge_8"
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <instances.BodyEndGraftWedge9
        name="Body_End_Graft_Wedge_9"
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <instances.BodySides name="Body_Sides" scale={0.001} userData={{ name: 'Body_Sides' }} />
      <instances.BodySides1 name="Body_Sides_1" scale={0.001} userData={{ name: 'Body_Sides' }} />
      <instances.BodySides2 name="Body_Sides_2" scale={0.001} userData={{ name: 'Body_Sides' }} />
      <instances.BodySides3 name="Body_Sides_3" scale={0.001} userData={{ name: 'Body_Sides' }} />
      <instances.BodySides4 name="Body_Sides_4" scale={0.001} userData={{ name: 'Body_Sides' }} />
      <instances.BodySides5 name="Body_Sides_5" scale={0.001} userData={{ name: 'Body_Sides' }} />
      <instances.BodySides6 name="Body_Sides_6" scale={0.001} userData={{ name: 'Body_Sides' }} />
      <instances.BodySides7 name="Body_Sides_7" scale={0.001} userData={{ name: 'Body_Sides' }} />
      <instances.BodySides8 name="Body_Sides_8" scale={0.001} userData={{ name: 'Body_Sides' }} />
      <instances.BodySidesVenetianCutaway
        name="Body_Sides_Venetian_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <instances.BodySidesVenetianCutaway1
        name="Body_Sides_Venetian_Cutaway_1"
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <instances.BodySidesVenetianCutaway2
        name="Body_Sides_Venetian_Cutaway_2"
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <instances.BodySidesVenetianCutaway3
        name="Body_Sides_Venetian_Cutaway_3"
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <instances.BodySidesVenetianCutaway4
        name="Body_Sides_Venetian_Cutaway_4"
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <instances.BodySidesVenetianCutaway5
        name="Body_Sides_Venetian_Cutaway_5"
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <instances.BodySidesVenetianCutaway6
        name="Body_Sides_Venetian_Cutaway_6"
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <instances.BodySidesVenetianCutaway7
        name="Body_Sides_Venetian_Cutaway_7"
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <instances.BodySidesVenetianCutaway8
        name="Body_Sides_Venetian_Cutaway_8"
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <instances.BodySidesFlorentineCutaway
        name="Body_Sides_Florentine_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <instances.BodySidesFlorentineCutaway1
        name="Body_Sides_Florentine_Cutaway_1"
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <instances.BodySidesFlorentineCutaway2
        name="Body_Sides_Florentine_Cutaway_2"
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <instances.BodySidesFlorentineCutaway3
        name="Body_Sides_Florentine_Cutaway_3"
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <instances.BodySidesFlorentineCutaway4
        name="Body_Sides_Florentine_Cutaway_4"
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <instances.BodySidesFlorentineCutaway5
        name="Body_Sides_Florentine_Cutaway_5"
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <instances.BodySidesFlorentineCutaway6
        name="Body_Sides_Florentine_Cutaway_6"
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <instances.BodySidesFlorentineCutaway7
        name="Body_Sides_Florentine_Cutaway_7"
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <instances.BodySidesFlorentineCutaway8
        name="Body_Sides_Florentine_Cutaway_8"
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <instances.BodySidesScallopedCutaway
        name="Body_Sides_Scalloped_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <instances.BodySidesScallopedCutaway1
        name="Body_Sides_Scalloped_Cutaway_1"
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <instances.BodySidesScallopedCutaway2
        name="Body_Sides_Scalloped_Cutaway_2"
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <instances.BodySidesScallopedCutaway3
        name="Body_Sides_Scalloped_Cutaway_3"
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <instances.BodySidesScallopedCutaway4
        name="Body_Sides_Scalloped_Cutaway_4"
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <instances.BodySidesScallopedCutaway5
        name="Body_Sides_Scalloped_Cutaway_5"
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <instances.BodySidesScallopedCutaway6
        name="Body_Sides_Scalloped_Cutaway_6"
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <instances.BodySidesScallopedCutaway7
        name="Body_Sides_Scalloped_Cutaway_7"
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <instances.BodySidesScallopedCutaway8
        name="Body_Sides_Scalloped_Cutaway_8"
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <instances.BodySidesScallopedCutaway9
        name="Body_Sides_Scalloped_Cutaway_9"
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <instances.BodySidesScallopedCutaway10
        name="Body_Sides_Scalloped_Cutaway_10"
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <instances.BodySidesArmBevel
        name="Body_Sides_Arm_Bevel"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <instances.BodySidesArmBevel1
        name="Body_Sides_Arm_Bevel_1"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <instances.BodySidesArmBevel2
        name="Body_Sides_Arm_Bevel_2"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <instances.BodySidesArmBevel3
        name="Body_Sides_Arm_Bevel_3"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <instances.BodySidesArmBevel4
        name="Body_Sides_Arm_Bevel_4"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <instances.BodySidesArmBevel5
        name="Body_Sides_Arm_Bevel_5"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <instances.BodySidesArmBevel6
        name="Body_Sides_Arm_Bevel_6"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <instances.BodySidesArmBevel7
        name="Body_Sides_Arm_Bevel_7"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <instances.BodySidesArmBevel8
        name="Body_Sides_Arm_Bevel_8"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <instances.BodySidesArmBevelFlorentineCutaway
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <instances.BodySidesArmBevelFlorentineCutaway1
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway_1"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <instances.BodySidesArmBevelFlorentineCutaway2
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway_2"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <instances.BodySidesArmBevelFlorentineCutaway3
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway_3"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <instances.BodySidesArmBevelFlorentineCutaway4
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway_4"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <instances.BodySidesArmBevelFlorentineCutaway5
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway_5"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <instances.BodySidesArmBevelFlorentineCutaway6
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway_6"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <instances.BodySidesArmBevelFlorentineCutaway7
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway_7"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <instances.BodySidesArmBevelFlorentineCutaway8
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway_8"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <instances.BodySidesArmBevelVenetianCutaway
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <instances.BodySidesArmBevelVenetianCutaway1
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway_1"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <instances.BodySidesArmBevelVenetianCutaway2
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway_2"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <instances.BodySidesArmBevelVenetianCutaway3
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway_3"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <instances.BodySidesArmBevelVenetianCutaway4
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway_4"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <instances.BodySidesArmBevelVenetianCutaway5
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway_5"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <instances.BodySidesArmBevelVenetianCutaway6
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway_6"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <instances.BodySidesArmBevelVenetianCutaway7
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway_7"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <instances.BodySidesArmBevelVenetianCutaway8
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway_8"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <instances.BodySidesArmBevelScallopedCutaway
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <instances.BodySidesArmBevelScallopedCutaway1
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway_1"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <instances.BodySidesArmBevelScallopedCutaway2
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway_2"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <instances.BodySidesArmBevelScallopedCutaway3
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway_3"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <instances.BodySidesArmBevelScallopedCutaway4
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway_4"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <instances.BodySidesArmBevelScallopedCutaway5
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway_5"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <instances.BodySidesArmBevelScallopedCutaway6
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway_6"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <instances.BodySidesArmBevelScallopedCutaway7
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway_7"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <instances.BodySidesArmBevelScallopedCutaway8
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway_8"
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <instances.BodyRosette
        name="Body_Rosette"
        scale={0.001}
        userData={{ name: 'Body_Rosette' }}
      />
      <instances.BodyRosette1
        name="Body_Rosette_(1)"
        scale={0.001}
        userData={{ name: 'Body_Rosette (1)' }}
      />
      <instances.BodyRosette2
        name="Body_Rosette_(2)"
        scale={0.001}
        userData={{ name: 'Body_Rosette (2)' }}
      />
      <instances.BodyRosette3
        name="Body_Rosette_(3)"
        scale={0.001}
        userData={{ name: 'Body_Rosette (3)' }}
      />
      <instances.BodyRosette4
        name="Body_Rosette_(4)"
        scale={0.001}
        userData={{ name: 'Body_Rosette (4)' }}
      />
      <instances.BodyBraceFretboardReinforcementRight
        name="Body_Brace_Fretboard_Reinforcement_Right"
        scale={0.001}
        userData={{ name: 'Body_Brace_Fretboard_Reinforcement_Right' }}
      />
      <instances.BodyLateralBraceA
        name="Body_Lateral_BraceA"
        scale={0.001}
        userData={{ name: 'Body_Lateral_BraceA' }}
      />
      <instances.BodyXBraceB
        name="Body_X_BraceB"
        scale={0.001}
        userData={{ name: 'Body_X_BraceB' }}
      />
      <instances.BodyXBraceC
        name="Body_X_BraceC"
        scale={0.001}
        userData={{ name: 'Body_X_BraceC' }}
      />
      <instances.BodyBraceD name="Body_BraceD" scale={0.001} userData={{ name: 'Body_BraceD' }} />
      <instances.BodyBraceE name="Body_BraceE" scale={0.001} userData={{ name: 'Body_BraceE' }} />
      <instances.BodyBraceFRight
        name="Body_BraceF_Right"
        scale={0.001}
        userData={{ name: 'Body_BraceF_Right' }}
      />
      <instances.BodyBraceGRight
        name="Body_BraceG_Right"
        scale={0.001}
        userData={{ name: 'Body_BraceG_Right' }}
      />
      <instances.BodyBraceGLeft
        name="Body_BraceG_Left"
        scale={0.001}
        userData={{ name: 'Body_BraceG_Left' }}
      />
      <instances.BodyBraceFLeft
        name="Body_BraceF_Left"
        scale={0.001}
        userData={{ name: 'Body_BraceF_Left' }}
      />
      <instances.BodyBraceHLeft
        name="Body_BraceH_Left"
        scale={0.001}
        userData={{ name: 'Body_BraceH_Left' }}
      />
      <instances.BodyBraceHRight
        name="Body_BraceH_Right"
        scale={0.001}
        userData={{ name: 'Body_BraceH_Right' }}
      />
      <instances.BodyBridgePlate
        name="Body_Bridge_Plate"
        scale={0.001}
        userData={{ name: 'Body_Bridge_Plate' }}
      />
      <instances.BodySoundboard
        name="Body_Soundboard"
        scale={0.001}
        userData={{ name: 'Body_Soundboard' }}
      />
      <instances.BodySoundboardVenetianCutaway
        name="Body_Soundboard_Venetian_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Soundboard_Venetian_Cutaway' }}
      />
      <instances.BodySoundboardFlorentineCutaway
        name="Body_Soundboard_Florentine_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Soundboard_Florentine_Cutaway' }}
      />
      <instances.BodySoundboardArmBevel
        name="Body_Soundboard_Arm_Bevel"
        scale={0.001}
        userData={{ name: 'Body_Soundboard_Arm_Bevel' }}
      />
      <instances.BodySoundboardArmBevelCutawayVenetian
        name="Body_Soundboard_Arm_Bevel_Cutaway_Venetian"
        scale={0.001}
        userData={{ name: 'Body_Soundboard_Arm_Bevel_Cutaway_Venetian' }}
      />
      <instances.BodySoundboardArmBevelCutawayFlorentine
        name="Body_Soundboard_Arm_Bevel_Cutaway_Florentine"
        scale={0.001}
        userData={{ name: 'Body_Soundboard_Arm_Bevel_Cutaway_Florentine' }}
      />
      <instances.BodySaddle name="Body_Saddle" scale={0.001} userData={{ name: 'Body_Saddle' }} />
      <instances.BodyBridgePinInlay
        name="Body_Bridge_Pin_Inlay"
        position={[-0.027, -0.156, 0.008]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin_Inlay' }}
      />
      <instances.BodyBridgePinInlay
        name="Body_Bridge_Pin_Inlay_1"
        position={[-0.017, -0.156, 0.007]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin_Inlay' }}
      />
      <instances.BodyBridgePinInlay
        name="Body_Bridge_Pin_Inlay_2"
        position={[-0.006, -0.156, 0.008]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin_Inlay' }}
      />
      <instances.BodyBridgePinInlay
        name="Body_Bridge_Pin_Inlay_3"
        position={[0.005, -0.156, 0.007]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin_Inlay' }}
      />
      <instances.BodyBridgePinInlay
        name="Body_Bridge_Pin_Inlay_4"
        position={[0.016, -0.156, 0.007]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin_Inlay' }}
      />
      <instances.BodyBridgePinInlay
        name="Body_Bridge_Pin_Inlay_5"
        position={[0.027, -0.156, 0.007]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin_Inlay' }}
      />
      <instances.BodyBridgePin
        name="Body_Bridge_Pin"
        position={[-0.027, -0.156, 0.008]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin' }}
      />
      <instances.BodyBridgePin
        name="Body_Bridge_Pin_1"
        position={[-0.017, -0.156, 0.007]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin' }}
      />
      <instances.BodyBridgePin
        name="Body_Bridge_Pin_2"
        position={[-0.006, -0.156, 0.008]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin' }}
      />
      <instances.BodyBridgePin
        name="Body_Bridge_Pin_3"
        position={[0.005, -0.156, 0.007]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin' }}
      />
      <instances.BodyBridgePin
        name="Body_Bridge_Pin_4"
        position={[0.016, -0.156, 0.007]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin' }}
      />
      <instances.BodyBridgePin
        name="Body_Bridge_Pin_5"
        position={[0.027, -0.156, 0.007]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin' }}
      />
      <instances.BodyBridge name="Body_Bridge" scale={0.001} userData={{ name: 'Body_Bridge' }} />
      <instances.BodyBackCenterStrip
        name="Body_Back_Center_Strip"
        scale={0.001}
        userData={{ name: 'Body_Back_Center_Strip' }}
      />
      <instances.BodyBackDoubleStripRight
        name="Body_Back_Double_Strip_Right_(1)"
        scale={0.001}
        userData={{ name: 'Body_Back_Double_Strip_Right (1)' }}
      />
      <instances.BodyBackDoubleStripLeft
        name="Body_Back_Double_Strip_Left"
        scale={0.001}
        userData={{ name: 'Body_Back_Double_Strip_Left' }}
      />
      <instances.BodyCenterBackStrip
        name="Body_Center_Back_Strip"
        scale={0.001}
        userData={{ name: 'Body_Center_Back_Strip' }}
      />
      <instances.BodyDoubleBackStripLeft
        name="Body_Double_Back_Strip_Left"
        scale={0.001}
        userData={{ name: 'Body_Double_Back_Strip_Left' }}
      />
      <instances.BodyDoubleBackStripRight
        name="Body_Double_Back_Strip_Right"
        scale={0.001}
        userData={{ name: 'Body_Double_Back_Strip_Right' }}
      />
      <instances.BodyBack name="Body_Back" scale={0.001} userData={{ name: 'Body_Back' }} />
      <instances.BodyBackVenetianCutaway
        name="Body_Back_Venetian_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Back_Venetian_Cutaway' }}
      />
      <instances.BodyBackFlorentineCutaway
        name="Body_Back_Florentine_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Back_Florentine_Cutaway' }}
      />
      <instances.BodyBackTwoPieceLeft
        name="Body_Back_Two_Piece_Left"
        scale={0.001}
        userData={{ name: 'Body_Back_Two_Piece_Left' }}
      />
      <instances.BodyBackTwoPieceLeft
        name="Body_Back_Two_Piece_Venetian_Cutaway_Left"
        scale={0.001}
        userData={{ name: 'Body_Back_Two_Piece_Venetian_Cutaway_Left' }}
      />
      <instances.BodyBackTwoPieceLeft
        name="Body_Back_Two_Piece_Florentine_Cutaway_Left"
        scale={0.001}
        userData={{ name: 'Body_Back_Two_Piece_Florentine_Cutaway_Left' }}
      />
      <instances.BodyBackTwoPieceRight
        name="Body_Back_Two_Piece_Right"
        scale={0.001}
        userData={{ name: 'Body_Back_Two_Piece_Right' }}
      />
      <instances.BodyBackTwoPieceVenetianCutawayRight
        name="Body_Back_Two_Piece_Venetian_Cutaway_Right"
        scale={0.001}
        userData={{ name: 'Body_Back_Two_Piece_Venetian_Cutaway_Right' }}
      />
      <instances.BodyBackTwoPieceFlorentineCutawayRight
        name="Body_Back_Two_Piece_Florentine_Cutaway_Right"
        scale={0.001}
        userData={{ name: 'Body_Back_Two_Piece_Florentine_Cutaway_Right' }}
      />
      <instances.BodyBackThreePieceMiddle
        name="Body_Back_Three_Piece_Middle"
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Middle' }}
      />
      <instances.BodyBackThreePieceVenetianCutawayMiddle
        name="Body_Back_Three_Piece_Venetian_Cutaway_Middle"
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Venetian_Cutaway_Middle' }}
      />
      <instances.BodyBackThreePieceFlorentineCutawayMiddle
        name="Body_Back_Three_Piece_Florentine_Cutaway_Middle"
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Florentine_Cutaway_Middle' }}
      />
      <instances.BodyBackThreePieceLeft
        name="Body_Back_Three_Piece_Left"
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Left' }}
      />
      <instances.BodyBackThreePieceLeft
        name="Body_Back_Three_Piece_Venetian_Cutaway_Left"
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Venetian_Cutaway_Left' }}
      />
      <instances.BodyBackThreePieceRight
        name="Body_Back_Three_Piece_Right"
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Right' }}
      />
      <instances.BodyBackThreePieceVenetianCutawayRight
        name="Body_Back_Three_Piece_Venetian_Cutaway_Right"
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Venetian_Cutaway_Right' }}
      />
      <instances.BodyBackThreePieceFlorentineCutawayRight
        name="Body_Back_Three_Piece_Florentine_Cutaway_Right"
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Florentine_Cutaway_Right' }}
      />
      <instances.BodyBackThreePieceFlorentineCutawayLeft
        name="Body_Back_Three_Piece_Florentine_Cutaway_Left"
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Florentine_Cutaway_Left' }}
      />
      <instances.BodyFret name="Body_Fret1" scale={0.001} userData={{ name: 'Body_Fret1' }} />
      <instances.BodyFret1 name="Body_Fret2" scale={0.001} userData={{ name: 'Body_Fret2' }} />
      <instances.BodyFret2 name="Body_Fret3" scale={0.001} userData={{ name: 'Body_Fret3' }} />
      <instances.BodyFret3 name="Body_Fret4" scale={0.001} userData={{ name: 'Body_Fret4' }} />
      <instances.BodyFret4 name="Body_Fret5" scale={0.001} userData={{ name: 'Body_Fret5' }} />
      <instances.BodyFret5 name="Body_Fret6" scale={0.001} userData={{ name: 'Body_Fret6' }} />
      <instances.BodyFret6 name="Body_Fret7" scale={0.001} userData={{ name: 'Body_Fret7' }} />
      <instances.BodyFret7 name="Body_Fret8" scale={0.001} userData={{ name: 'Body_Fret8' }} />
      <instances.BodyFret8 name="Body_Fret9" scale={0.001} userData={{ name: 'Body_Fret9' }} />
      <instances.BodyFret9 name="Body_Fret10" scale={0.001} userData={{ name: 'Body_Fret10' }} />
      <instances.BodyFret10 name="Body_Fret11" scale={0.001} userData={{ name: 'Body_Fret11' }} />
      <instances.BodyFret11 name="Body_Fret12" scale={0.001} userData={{ name: 'Body_Fret12' }} />
      <instances.BodyFret12 name="Body_Fret13" scale={0.001} userData={{ name: 'Body_Fret13' }} />
      <instances.BodyFret13 name="Body_Fret14" scale={0.001} userData={{ name: 'Body_Fret14' }} />
      <instances.BodyFret14 name="Body_Fret15" scale={0.001} userData={{ name: 'Body_Fret15' }} />
      <instances.BodyFret15 name="Body_Fret16" scale={0.001} userData={{ name: 'Body_Fret16' }} />
      <instances.BodyFret16 name="Body_Fret17" scale={0.001} userData={{ name: 'Body_Fret17' }} />
      <instances.BodyFret17 name="Body_Fret18" scale={0.001} userData={{ name: 'Body_Fret18' }} />
      <instances.BodyFret18 name="Body_Fret19" scale={0.001} userData={{ name: 'Body_Fret19' }} />
      <instances.BodyFret19 name="Body_Fret20" scale={0.001} userData={{ name: 'Body_Fret20' }} />
      <instances.BodyNut name="Body_Nut" scale={0.001} userData={{ name: 'Body_Nut' }} />
      <instances.BodyFretboard
        name="Body_Fretboard"
        scale={0.001}
        userData={{ name: 'Body_Fretboard' }}
      />
      <instances.BodyFretMarkerFret
        name="Body_Fret_Marker_Fret17"
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret17' }}
      />
      <instances.BodyFretMarkerFret1
        name="Body_Fret_Marker_Fret21"
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret21' }}
      />
      <instances.BodyFretMarkerFret2
        name="Body_Fret_Marker_Fret7"
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret7' }}
      />
      <instances.BodyFretMarkerFret3
        name="Body_Fret_Marker_Fret12-2"
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret12-2' }}
      />
      <instances.BodyFretMarkerFret4
        name="Body_Fret_Marker_Fret3"
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret3' }}
      />
      <instances.BodyFretMarkerFret5
        name="Body_Fret_Marker_Fret5"
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret5' }}
      />
      <instances.BodyFretMarkerFret6
        name="Body_Fret_Marker_Fret15"
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret15' }}
      />
      <instances.BodyFretMarkerFret7
        name="Body_Fret_Marker_Fret12-1"
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret12-1' }}
      />
      <instances.BodyFretMarkerFret8
        name="Body_Fret_Marker_Fret9"
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret9' }}
      />
      <instances.BodyFretboard1
        name="Body_Fretboard_(1)"
        scale={0.001}
        userData={{ name: 'Body_Fretboard (1)' }}
      />
      <instances.BodyFretboard2
        name="Body_Fretboard_(1)_(2)"
        scale={0.001}
        userData={{ name: 'Body_Fretboard (1) (2)' }}
      />
      <instances.BodyFretboard3
        name="Body_Fretboard_(1)_(3)"
        scale={0.001}
        userData={{ name: 'Body_Fretboard (1) (3)' }}
      />
      <instances.BodySideFretMarkerFret
        name="Body_Side_Fret_Marker_Fret5"
        scale={0.001}
        userData={{ name: 'Body_Side_Fret_Marker_Fret5' }}
      />
      <instances.BodySideFretMarkerFret1
        name="Body_Side_Fret_Marker_Fret7"
        scale={0.001}
        userData={{ name: 'Body_Side_Fret_Marker_Fret7' }}
      />
      <instances.BodySideFretMarkerFret2
        name="Body_Side_Fret_Marker_Fret17"
        scale={0.001}
        userData={{ name: 'Body_Side_Fret_Marker_Fret17' }}
      />
      <instances.BodySideFretMarkerFret3
        name="Body_Side_Fret_Marker_Fret21"
        scale={0.001}
        userData={{ name: 'Body_Side_Fret_Marker_Fret21' }}
      />
      <instances.BodySideFretMarkerFret4
        name="Body_Side_Fret_Marker_Fret3"
        scale={0.001}
        userData={{ name: 'Body_Side_Fret_Marker_Fret3' }}
      />
      <instances.BodySideFretMarkerFret5
        name="Body_Side_Fret_Marker_Fret9"
        scale={0.001}
        userData={{ name: 'Body_Side_Fret_Marker_Fret9' }}
      />
      <instances.BodyFretboard4
        name="Body_Fretboard_(1)_(1)"
        scale={0.001}
        userData={{ name: 'Body_Fretboard (1) (1)' }}
      />
      <instances.BodyFretboard5
        name="Body_Fretboard_1"
        scale={0.001}
        userData={{ name: 'Body_Fretboard' }}
      />
      <instances.BodyFretboardSoundholeTangent
        name="Body_Fretboard_Soundhole_Tangent"
        scale={0.001}
        userData={{ name: 'Body_Fretboard_Soundhole_Tangent' }}
      />
      <instances.SurfaceNeckProfile
        name="Surface_Neck_Profile"
        scale={0.001}
        userData={{ name: 'Surface_Neck_Profile' }}
      />
      <instances.BodyHeel name="Body_Heel" scale={0.001} userData={{ name: 'Body_Heel' }} />
      <instances.BodyNeck name="Body_Neck" scale={0.001} userData={{ name: 'Body_Neck' }} />
      <instances.BodyPickguard
        name="Body_Pickguard"
        scale={0.001}
        userData={{ name: 'Body_Pickguard' }}
      />
      <instances.PegHead
        name="Peg_Head"
        position={[-0.02, 0.544, -0.02]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head' }}
      />
      <instances.PegHead
        name="Peg_Head_1"
        position={[-0.022, 0.583, -0.031]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head' }}
      />
      <instances.PegHead
        name="Peg_Head_2"
        position={[-0.024, 0.624, -0.04]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head' }}
      />
      <instances.PegHead
        name="Peg_Head_3"
        position={[0.02, 0.543, -0.02]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head' }}
      />
      <instances.PegHead
        name="Peg_Head_4"
        position={[0.022, 0.584, -0.028]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head' }}
      />
      <instances.PegHead
        name="Peg_Head_5"
        position={[0.024, 0.624, -0.037]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head' }}
      />
      <instances.PegHeadTunerRight
        name="Peg_Head_Tuner_Right"
        position={[-0.02, 0.544, -0.02]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head_Tuner_Right' }}
      />
      <instances.PegHeadTunerRight
        name="Peg_Head_Tuner_Right_1"
        position={[-0.022, 0.583, -0.031]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head_Tuner_Right' }}
      />
      <instances.PegHeadTunerRight
        name="Peg_Head_Tuner_Right_2"
        position={[-0.024, 0.624, -0.04]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head_Tuner_Right' }}
      />
      <instances.PegHeadTunerRight
        name="Peg_Head_Tuner_Right_3"
        position={[0.02, 0.543, -0.02]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head_Tuner_Right' }}
      />
      <instances.PegHeadTunerRight
        name="Peg_Head_Tuner_Right_4"
        position={[0.022, 0.584, -0.028]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head_Tuner_Right' }}
      />
      <instances.PegHeadTunerRight
        name="Peg_Head_Tuner_Right_5"
        position={[0.024, 0.624, -0.037]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head_Tuner_Right' }}
      />
      <instances.BodyHeadstock
        name="Body_Headstock"
        scale={0.001}
        userData={{ name: 'Body_Headstock' }}
      />
      <instances.BodyPurflingTop
        name="Body_Purfling_Top"
        scale={0.001}
        userData={{ name: 'Body_Purfling_Top' }}
      />
      <instances.BodyPurflingBottom
        name="Body_Purfling_Bottom"
        scale={0.001}
        userData={{ name: 'Body_Purfling_Bottom' }}
      />
      <instances.BodyPurflingTopVenetianCutaway
        name="Body_Purfling_Top_Venetian_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Purfling_Top_Venetian_Cutaway' }}
      />
      <instances.BodyPurflingBottomVenetianCutaway
        name="Body_Purfling_Bottom_Venetian_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Purfling_Bottom_Venetian_Cutaway' }}
      />
      <instances.BodyPurflingTopFlorentineCutaway
        name="Body_Purfling_Top_Florentine_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Purfling_Top_Florentine_Cutaway' }}
      />
      <instances.BodyPurflingBottomFlorentineCutaway
        name="Body_Purfling_Bottom_Florentine_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Purfling_Bottom_Florentine_Cutaway' }}
      />
      <instances.BodyPurflingTopArmBevel
        name="Body_Purfling_Top_Arm_Bevel"
        scale={0.001}
        userData={{ name: 'Body_Purfling_Top_Arm_Bevel' }}
      />
      <instances.BodyPurflingTopArmBevelFlorentineCutaway
        name="Body_Purfling_Top_Arm_Bevel_Florentine_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Purfling_Top_Arm_Bevel_Florentine_Cutaway' }}
      />
      <instances.BodyPurflingTopArmBevelVenetianCutaway
        name="Body_Purfling_Top_Arm_Bevel_Venetian_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Purfling_Top_Arm_Bevel_Venetian_Cutaway' }}
      />
      <instances.BodyBindingTop
        name="Body_Binding_Top"
        scale={0.001}
        userData={{ name: 'Body_Binding_Top' }}
      />
      <instances.BodyBindingBottom
        name="Body_Binding_Bottom"
        scale={0.001}
        userData={{ name: 'Body_Binding_Bottom' }}
      />
      <instances.BodyBindingTopVenetianCutaway
        name="Body_Binding_Top_Venetian_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Binding_Top_Venetian_Cutaway' }}
      />
      <instances.BodyBindingBottomVenetianCutaway
        name="Body_Binding_Bottom_Venetian_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Binding_Bottom_Venetian_Cutaway' }}
      />
      <instances.BodyBindingTopFlorentineCutaway
        name="Body_Binding_Top_Florentine_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Binding_Top_Florentine_Cutaway' }}
      />
      <instances.BodyBindingBottomFlorentineCutaway
        name="Body_Binding_Bottom_Florentine_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Binding_Bottom_Florentine_Cutaway' }}
      />
      <instances.BodyBindingTopArmBevel
        name="Body_Binding_Top_Arm_Bevel"
        scale={0.001}
        userData={{ name: 'Body_Binding_Top_Arm_Bevel' }}
      />
      <instances.BodyBindingTopArmBevelVenetianCutaway
        name="Body_Binding_Top_Arm_Bevel_Venetian_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Binding_Top_Arm_Bevel_Venetian_Cutaway' }}
      />
      <instances.BodyBindingTopArmBevelFlorentineCutaway
        name="Body_Binding_Top_Arm_Bevel_Florentine_Cutaway"
        scale={0.001}
        userData={{ name: 'Body_Binding_Top_Arm_Bevel_Florentine_Cutaway' }}
      />
      <instances.BodyStringLowE
        name="Body_String_LowE"
        scale={0.001}
        userData={{ name: 'Body_String_LowE' }}
      />
      <instances.BodyStringA
        name="Body_String_A"
        scale={0.001}
        userData={{ name: 'Body_String_A' }}
      />
      <instances.BodyStringD
        name="Body_String_D"
        scale={0.001}
        userData={{ name: 'Body_String_D' }}
      />
      <instances.BodyStringG
        name="Body_String_G"
        scale={0.001}
        userData={{ name: 'Body_String_G' }}
      />
      <instances.BodyStringB
        name="Body_String_B"
        scale={0.001}
        userData={{ name: 'Body_String_B' }}
      />
      <instances.BodyStringHighE
        name="Body_String_HighE"
        scale={0.001}
        userData={{ name: 'Body_String_HighE' }}
      />
    </group>
  )
}

useGLTF.preload('/luth-acoustic-transformed.glb')
