/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/End_Graft_Collection.glb --types --transform --instanceall --keepmeshes --keepmaterials --keepattributes --keepnames --draco --meta --shadows --exportdefault --output ./src/_generated/LuthEndGraft.tsx 
Files: ./public/End_Graft_Collection.glb [11.87KB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/End_Graft_Collection-transformed.glb [2.48KB] (79%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Body_End_Graft_Wedge: THREE.Mesh
  }
  materials: {
    F_cd43ce48b091467a855ac29a4e33b11d: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/End_Graft_Collection-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      BodyEndGraftWedge: nodes.Body_End_Graft_Wedge,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.BodyEndGraftWedge
        name="Body_End_Graft_Wedge"
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
    </group>
  )
}

useGLTF.preload('/End_Graft_Collection-transformed.glb')
