/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Rosette_Collection.glb --types --transform --instanceall --keepmeshes --keepmaterials --keepattributes --keepnames --draco --meta --shadows --exportdefault --output ./src/_generated/LuthRosette.tsx 
Files: ./public/Rosette_Collection.glb [47.41KB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/Rosette_Collection-transformed.glb [7.01KB] (85%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Body_Rosette: THREE.Mesh
    Body_Rosette_Half: THREE.Mesh
    Body_Rosette_Half1: THREE.Mesh
  }
  materials: {
    F_3e3f3a2972784f38b09e6dd1ea94cda9: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Rosette_Collection-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      BodyRosette: nodes.Body_Rosette,
      BodyRosetteHalf: nodes.Body_Rosette_Half,
      BodyRosetteHalf1: nodes.Body_Rosette_Half1,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.BodyRosette name="Body_Rosette" userData={{ name: 'Body_Rosette' }} />
      <instances.BodyRosetteHalf
        name="Body_Rosette_Half"
        userData={{ name: 'Body_Rosette_Half' }}
      />
      <instances.BodyRosetteHalf1
        name="Body_Rosette_Half1"
        userData={{ name: 'Body_Rosette_Half1' }}
      />
    </group>
  )
}

useGLTF.preload('/Rosette_Collection-transformed.glb')
