/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Heel_Tail_Blocks_Collection.glb --types --transform --instanceall --keepmeshes --keepmaterials --keepattributes --keepnames --draco --meta --shadows --exportdefault --output ./src/_generated/LuthHeelTailBlocks.tsx 
Files: ./public/Heel_Tail_Blocks_Collection.glb [75.85KB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/Heel_Tail_Blocks_Collection-transformed.glb [9.67KB] (87%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Body_Heel_Block004: THREE.Mesh
    Body_Tail_Block004: THREE.Mesh
    Body_Heel_Block005: THREE.Mesh
    Body_Tail_Block005: THREE.Mesh
  }
  materials: {
    FiestaRed: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Heel_Tail_Blocks_Collection-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      BodyHeelBlock: nodes.Body_Heel_Block004,
      BodyTailBlock: nodes.Body_Tail_Block004,
      BodyHeelBlock1: nodes.Body_Heel_Block005,
      BodyTailBlock1: nodes.Body_Tail_Block005,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.BodyHeelBlock name="Body_Heel_Block004" userData={{ name: 'Body_Heel_Block.004' }} />
      <instances.BodyTailBlock name="Body_Tail_Block004" userData={{ name: 'Body_Tail_Block.004' }} />
      <instances.BodyHeelBlock1 name="Body_Heel_Block005" userData={{ name: 'Body_Heel_Block.005' }} />
      <instances.BodyTailBlock1 name="Body_Tail_Block005" userData={{ name: 'Body_Tail_Block.005' }} />
    </group>
  )
}

useGLTF.preload('/Heel_Tail_Blocks_Collection-transformed.glb')
