/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Strings_Collection.glb --types --transform --instanceall --keepmeshes --keepmaterials --keepattributes --keepnames --draco --meta --shadows --exportdefault --output ./src/_generated/LuthStrings.tsx 
Files: ./public/Strings_Collection.glb [65.36KB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/Strings_Collection-transformed.glb [10.45KB] (84%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Body_String_A: THREE.Mesh
    Body_String_B: THREE.Mesh
    Body_String_D: THREE.Mesh
    Body_String_G: THREE.Mesh
    Body_String_HighE: THREE.Mesh
    Body_String_LowE: THREE.Mesh
  }
  materials: {
    F_a7ee474f40ff4ad8b80f21654ce1c2b2: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Strings_Collection-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      BodyStringA: nodes.Body_String_A,
      BodyStringB: nodes.Body_String_B,
      BodyStringD: nodes.Body_String_D,
      BodyStringG: nodes.Body_String_G,
      BodyStringHighE: nodes.Body_String_HighE,
      BodyStringLowE: nodes.Body_String_LowE,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.BodyStringA name="Body_String_A" userData={{ name: 'Body_String_A' }} />
      <instances.BodyStringB name="Body_String_B" userData={{ name: 'Body_String_B' }} />
      <instances.BodyStringD name="Body_String_D" userData={{ name: 'Body_String_D' }} />
      <instances.BodyStringG name="Body_String_G" userData={{ name: 'Body_String_G' }} />
      <instances.BodyStringHighE
        name="Body_String_HighE"
        userData={{ name: 'Body_String_HighE' }}
      />
      <instances.BodyStringLowE name="Body_String_LowE" userData={{ name: 'Body_String_LowE' }} />
    </group>
  )
}

useGLTF.preload('/Strings_Collection-transformed.glb')
