/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Kerfling_Collection.glb --types --transform --instanceall --keepmeshes --keepmaterials --keepattributes --keepnames --draco --meta --shadows --exportdefault --output ./src/_generated/LuthKerfling.tsx 
Files: ./public/Kerfling_Collection.glb [547.26KB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/Kerfling_Collection-transformed.glb [42.63KB] (92%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Body_Kerfling_Bottom: THREE.Mesh
    Body_Kerfling_Top: THREE.Mesh
    Body_Lining_Bottom004: THREE.Mesh
    Body_Lining_Top004: THREE.Mesh
  }
  materials: {
    F_d08a78a0100b42e8b928a6abdd36ad9f: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Kerfling_Collection-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      BodyKerflingBottom: nodes.Body_Kerfling_Bottom,
      BodyKerflingTop: nodes.Body_Kerfling_Top,
      BodyLiningBottom: nodes.Body_Lining_Bottom004,
      BodyLiningTop: nodes.Body_Lining_Top004,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.BodyKerflingBottom name="Body_Kerfling_Bottom" userData={{ name: 'Body_Kerfling_Bottom' }} />
      <instances.BodyKerflingTop name="Body_Kerfling_Top" userData={{ name: 'Body_Kerfling_Top' }} />
      <instances.BodyLiningBottom name="Body_Lining_Bottom004" userData={{ name: 'Body_Lining_Bottom.004' }} />
      <instances.BodyLiningTop name="Body_Lining_Top004" userData={{ name: 'Body_Lining_Top.004' }} />
    </group>
  )
}

useGLTF.preload('/Kerfling_Collection-transformed.glb')
