/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Fretboard_Collection.glb --types --transform --instanceall --keepmeshes --keepmaterials --keepattributes --keepnames --draco --meta --shadows --exportdefault --output ./src/_generated/LuthFretboard.tsx 
Files: ./public/Fretboard_Collection.glb [1.01MB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/Fretboard_Collection-transformed.glb [136.2KB] (87%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Fretboard__Scale24_Fret14__ExtStd__Mesh: THREE.Mesh
    Fretboard__Scale24_Fret14__ExtTan__Mesh: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret11__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret12__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret13__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret14__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret15__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret16__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret17__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret18__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret19__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret20__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret2__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Nut__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fretboard__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret17__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret21__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret7__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret12_2__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret3__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret5__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret15__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret12_1__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret3__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret9__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fretboard__1___Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fretboard__1___2___Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fretboard__1___3___Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret5__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret7__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret17__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret21__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret3__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret9__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret4__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fretboard__1___1___Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__ExtStd__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__ExtTan__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret5__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret6__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret7__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret8__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret9__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret10__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret14__Body_Fret1__Mesh']: THREE.Mesh
    Fretboard__Scale24_Fret12__ExtStd__Mesh: THREE.Mesh
    Fretboard__Scale24_Fret12__ExtTan__Mesh: THREE.Mesh
    ['Fretboard__Scale25-4_Fret12__ExtStd__Mesh']: THREE.Mesh
    ['Fretboard__Scale25-4_Fret12__ExtTan__Mesh']: THREE.Mesh
  }
  materials: {
    F_e16ce2efe0614df6a2b8e376aaa7e444: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Fretboard_Collection-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      FretboardScaleFretExtStdMesh: nodes.Fretboard__Scale24_Fret14__ExtStd__Mesh,
      FretboardScaleFretExtTanMesh: nodes.Fretboard__Scale24_Fret14__ExtTan__Mesh,
      FretboardScaleFretBodyFretMesh: nodes['Fretboard__Scale25-4_Fret14__Body_Fret11__Mesh'],
      FretboardScaleFretBodyFretMesh1: nodes['Fretboard__Scale25-4_Fret14__Body_Fret12__Mesh'],
      FretboardScaleFretBodyFretMesh2: nodes['Fretboard__Scale25-4_Fret14__Body_Fret13__Mesh'],
      FretboardScaleFretBodyFretMesh3: nodes['Fretboard__Scale25-4_Fret14__Body_Fret14__Mesh'],
      FretboardScaleFretBodyFretMesh4: nodes['Fretboard__Scale25-4_Fret14__Body_Fret15__Mesh'],
      FretboardScaleFretBodyFretMesh5: nodes['Fretboard__Scale25-4_Fret14__Body_Fret16__Mesh'],
      FretboardScaleFretBodyFretMesh6: nodes['Fretboard__Scale25-4_Fret14__Body_Fret17__Mesh'],
      FretboardScaleFretBodyFretMesh7: nodes['Fretboard__Scale25-4_Fret14__Body_Fret18__Mesh'],
      FretboardScaleFretBodyFretMesh8: nodes['Fretboard__Scale25-4_Fret14__Body_Fret19__Mesh'],
      FretboardScaleFretBodyFretMesh9: nodes['Fretboard__Scale25-4_Fret14__Body_Fret20__Mesh'],
      FretboardScaleFretBodyFretMesh10: nodes['Fretboard__Scale25-4_Fret14__Body_Fret2__Mesh'],
      FretboardScaleFretBodyNutMesh: nodes['Fretboard__Scale25-4_Fret14__Body_Nut__Mesh'],
      FretboardScaleFretBodyFretboardMesh:
        nodes['Fretboard__Scale25-4_Fret14__Body_Fretboard__Mesh'],
      FretboardScaleFretBodyFretMarkerFretMesh:
        nodes['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret17__Mesh'],
      FretboardScaleFretBodyFretMarkerFretMesh1:
        nodes['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret21__Mesh'],
      FretboardScaleFretBodyFretMarkerFretMesh2:
        nodes['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret7__Mesh'],
      FretboardScaleFretBodyFretMarkerFretMesh3:
        nodes['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret12_2__Mesh'],
      FretboardScaleFretBodyFretMarkerFretMesh4:
        nodes['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret3__Mesh'],
      FretboardScaleFretBodyFretMarkerFretMesh5:
        nodes['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret5__Mesh'],
      FretboardScaleFretBodyFretMarkerFretMesh6:
        nodes['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret15__Mesh'],
      FretboardScaleFretBodyFretMarkerFretMesh7:
        nodes['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret12_1__Mesh'],
      FretboardScaleFretBodyFretMesh11: nodes['Fretboard__Scale25-4_Fret14__Body_Fret3__Mesh'],
      FretboardScaleFretBodyFretMarkerFretMesh8:
        nodes['Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret9__Mesh'],
      FretboardScaleFretBodyFretboardMesh1:
        nodes['Fretboard__Scale25-4_Fret14__Body_Fretboard__1___Mesh'],
      FretboardScaleFretBodyFretboardMesh2:
        nodes['Fretboard__Scale25-4_Fret14__Body_Fretboard__1___2___Mesh'],
      FretboardScaleFretBodyFretboardMesh3:
        nodes['Fretboard__Scale25-4_Fret14__Body_Fretboard__1___3___Mesh'],
      FretboardScaleFretBodySideFretMarkerFretMesh:
        nodes['Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret5__Mesh'],
      FretboardScaleFretBodySideFretMarkerFretMesh1:
        nodes['Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret7__Mesh'],
      FretboardScaleFretBodySideFretMarkerFretMesh2:
        nodes['Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret17__Mesh'],
      FretboardScaleFretBodySideFretMarkerFretMesh3:
        nodes['Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret21__Mesh'],
      FretboardScaleFretBodySideFretMarkerFretMesh4:
        nodes['Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret3__Mesh'],
      FretboardScaleFretBodySideFretMarkerFretMesh5:
        nodes['Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret9__Mesh'],
      FretboardScaleFretBodyFretMesh12: nodes['Fretboard__Scale25-4_Fret14__Body_Fret4__Mesh'],
      FretboardScaleFretBodyFretboardMesh4:
        nodes['Fretboard__Scale25-4_Fret14__Body_Fretboard__1___1___Mesh'],
      FretboardScaleFretExtStdMesh1: nodes['Fretboard__Scale25-4_Fret14__ExtStd__Mesh'],
      FretboardScaleFretExtTanMesh1: nodes['Fretboard__Scale25-4_Fret14__ExtTan__Mesh'],
      FretboardScaleFretBodyFretMesh13: nodes['Fretboard__Scale25-4_Fret14__Body_Fret5__Mesh'],
      FretboardScaleFretBodyFretMesh14: nodes['Fretboard__Scale25-4_Fret14__Body_Fret6__Mesh'],
      FretboardScaleFretBodyFretMesh15: nodes['Fretboard__Scale25-4_Fret14__Body_Fret7__Mesh'],
      FretboardScaleFretBodyFretMesh16: nodes['Fretboard__Scale25-4_Fret14__Body_Fret8__Mesh'],
      FretboardScaleFretBodyFretMesh17: nodes['Fretboard__Scale25-4_Fret14__Body_Fret9__Mesh'],
      FretboardScaleFretBodyFretMesh18: nodes['Fretboard__Scale25-4_Fret14__Body_Fret10__Mesh'],
      FretboardScaleFretBodyFretMesh19: nodes['Fretboard__Scale25-4_Fret14__Body_Fret1__Mesh'],
      FretboardScaleFretExtStdMesh2: nodes.Fretboard__Scale24_Fret12__ExtStd__Mesh,
      FretboardScaleFretExtTanMesh2: nodes.Fretboard__Scale24_Fret12__ExtTan__Mesh,
      FretboardScaleFretExtStdMesh3: nodes['Fretboard__Scale25-4_Fret12__ExtStd__Mesh'],
      FretboardScaleFretExtTanMesh3: nodes['Fretboard__Scale25-4_Fret12__ExtTan__Mesh'],
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.FretboardScaleFretExtStdMesh
        name="Fretboard__Scale24_Fret14__ExtStd__Mesh"
        userData={{ name: 'Fretboard__Scale24_Fret14__ExtStd__Mesh' }}
      />
      <instances.FretboardScaleFretExtTanMesh
        name="Fretboard__Scale24_Fret14__ExtTan__Mesh"
        userData={{ name: 'Fretboard__Scale24_Fret14__ExtTan__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh
        name="Fretboard__Scale25-4_Fret14__Body_Fret11__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret11__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh1
        name="Fretboard__Scale25-4_Fret14__Body_Fret12__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret12__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh2
        name="Fretboard__Scale25-4_Fret14__Body_Fret13__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret13__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh3
        name="Fretboard__Scale25-4_Fret14__Body_Fret14__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret14__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh4
        name="Fretboard__Scale25-4_Fret14__Body_Fret15__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret15__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh5
        name="Fretboard__Scale25-4_Fret14__Body_Fret16__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret16__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh6
        name="Fretboard__Scale25-4_Fret14__Body_Fret17__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret17__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh7
        name="Fretboard__Scale25-4_Fret14__Body_Fret18__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret18__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh8
        name="Fretboard__Scale25-4_Fret14__Body_Fret19__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret19__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh9
        name="Fretboard__Scale25-4_Fret14__Body_Fret20__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret20__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh10
        name="Fretboard__Scale25-4_Fret14__Body_Fret2__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret2__Mesh' }}
      />
      <instances.FretboardScaleFretBodyNutMesh
        name="Fretboard__Scale25-4_Fret14__Body_Nut__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Nut__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretboardMesh
        name="Fretboard__Scale25-4_Fret14__Body_Fretboard__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fretboard__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMarkerFretMesh
        name="Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret17__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret17__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMarkerFretMesh1
        name="Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret21__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret21__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMarkerFretMesh2
        name="Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret7__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret7__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMarkerFretMesh3
        name="Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret12_2__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret12_2__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMarkerFretMesh4
        name="Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret3__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret3__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMarkerFretMesh5
        name="Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret5__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret5__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMarkerFretMesh6
        name="Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret15__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret15__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMarkerFretMesh7
        name="Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret12_1__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret12_1__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh11
        name="Fretboard__Scale25-4_Fret14__Body_Fret3__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret3__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMarkerFretMesh8
        name="Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret9__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret_Marker_Fret9__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretboardMesh1
        name="Fretboard__Scale25-4_Fret14__Body_Fretboard__1___Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fretboard__1___Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretboardMesh2
        name="Fretboard__Scale25-4_Fret14__Body_Fretboard__1___2___Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fretboard__1___2___Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretboardMesh3
        name="Fretboard__Scale25-4_Fret14__Body_Fretboard__1___3___Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fretboard__1___3___Mesh' }}
      />
      <instances.FretboardScaleFretBodySideFretMarkerFretMesh
        name="Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret5__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret5__Mesh' }}
      />
      <instances.FretboardScaleFretBodySideFretMarkerFretMesh1
        name="Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret7__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret7__Mesh' }}
      />
      <instances.FretboardScaleFretBodySideFretMarkerFretMesh2
        name="Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret17__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret17__Mesh' }}
      />
      <instances.FretboardScaleFretBodySideFretMarkerFretMesh3
        name="Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret21__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret21__Mesh' }}
      />
      <instances.FretboardScaleFretBodySideFretMarkerFretMesh4
        name="Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret3__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret3__Mesh' }}
      />
      <instances.FretboardScaleFretBodySideFretMarkerFretMesh5
        name="Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret9__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Side_Fret_Marker_Fret9__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh12
        name="Fretboard__Scale25-4_Fret14__Body_Fret4__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret4__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretboardMesh4
        name="Fretboard__Scale25-4_Fret14__Body_Fretboard__1___1___Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fretboard__1___1___Mesh' }}
      />
      <instances.FretboardScaleFretExtStdMesh1
        name="Fretboard__Scale25-4_Fret14__ExtStd__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__ExtStd__Mesh' }}
      />
      <instances.FretboardScaleFretExtTanMesh1
        name="Fretboard__Scale25-4_Fret14__ExtTan__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__ExtTan__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh13
        name="Fretboard__Scale25-4_Fret14__Body_Fret5__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret5__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh14
        name="Fretboard__Scale25-4_Fret14__Body_Fret6__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret6__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh15
        name="Fretboard__Scale25-4_Fret14__Body_Fret7__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret7__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh16
        name="Fretboard__Scale25-4_Fret14__Body_Fret8__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret8__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh17
        name="Fretboard__Scale25-4_Fret14__Body_Fret9__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret9__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh18
        name="Fretboard__Scale25-4_Fret14__Body_Fret10__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret10__Mesh' }}
      />
      <instances.FretboardScaleFretBodyFretMesh19
        name="Fretboard__Scale25-4_Fret14__Body_Fret1__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret14__Body_Fret1__Mesh' }}
      />
      <instances.FretboardScaleFretExtStdMesh2
        name="Fretboard__Scale24_Fret12__ExtStd__Mesh"
        userData={{ name: 'Fretboard__Scale24_Fret12__ExtStd__Mesh' }}
      />
      <instances.FretboardScaleFretExtTanMesh2
        name="Fretboard__Scale24_Fret12__ExtTan__Mesh"
        userData={{ name: 'Fretboard__Scale24_Fret12__ExtTan__Mesh' }}
      />
      <instances.FretboardScaleFretExtStdMesh3
        name="Fretboard__Scale25-4_Fret12__ExtStd__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret12__ExtStd__Mesh' }}
      />
      <instances.FretboardScaleFretExtTanMesh3
        name="Fretboard__Scale25-4_Fret12__ExtTan__Mesh"
        userData={{ name: 'Fretboard__Scale25-4_Fret12__ExtTan__Mesh' }}
      />
    </group>
  )
}

useGLTF.preload('/Fretboard_Collection-transformed.glb')
