/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Back_Collection.glb --types --transform --instanceall --keepmeshes --keepmaterials --keepattributes --keepnames --draco --meta --shadows --exportdefault --output ./src/_generated/LuthBack.tsx 
Files: ./public/Back_Collection.glb [461.93KB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/Back_Collection-transformed.glb [58.4KB] (87%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Body_Back_Center_Strip: THREE.Mesh
    Body_Back_Double_Strip_Right__1_: THREE.Mesh
    Back_2Piece_Left: THREE.Mesh
    Back_2Piece_Left_CW_Vene: THREE.Mesh
    Back_2Piece_Left_CW_Flor: THREE.Mesh
    Back_2Piece_Right: THREE.Mesh
    Back_2Piece_Right_CW_Vene: THREE.Mesh
    Back_2Piece_Right_CW_Flor: THREE.Mesh
    Back_3Piece_Middle: THREE.Mesh
    Body_Back_Three_Piece_Venetian_Cutaway_Middle: THREE.Mesh
    Body_Back_Three_Piece_Florentine_Cutaway_Middle: THREE.Mesh
    Back_3Piece_Left: THREE.Mesh
    Body_Back_Three_Piece_Venetian_Cutaway_Left: THREE.Mesh
    Body_Back_Double_Strip_Left: THREE.Mesh
    Back_3Piece_Right: THREE.Mesh
    Body_Back_Three_Piece_Venetian_Cutaway_Right: THREE.Mesh
    Body_Back_Three_Piece_Florentine_Cutaway_Right: THREE.Mesh
    Body_Back_Three_Piece_Florentine_Cutaway_Left: THREE.Mesh
    Body_Center_Back_Strip: THREE.Mesh
    Body_Double_Back_Strip_Left: THREE.Mesh
    Body_Double_Back_Strip_Right: THREE.Mesh
    Surface_Back: THREE.Mesh
    Back_CW_None: THREE.Mesh
    Back_CW_Vene: THREE.Mesh
    Back_CW_Flor: THREE.Mesh
  }
  materials: {
    ['F_789549acb60840db9e32b194f96035d1.002']: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Back_Collection-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      BodyBackCenterStrip: nodes.Body_Back_Center_Strip,
      BodyBackDoubleStripRight: nodes.Body_Back_Double_Strip_Right__1_,
      BackPieceLeft: nodes.Back_2Piece_Left,
      BackPieceRight: nodes.Back_2Piece_Right,
      BackPieceRightCWVene: nodes.Back_2Piece_Right_CW_Vene,
      BackPieceRightCWFlor: nodes.Back_2Piece_Right_CW_Flor,
      BackPieceMiddle: nodes.Back_3Piece_Middle,
      BodyBackThreePieceVenetianCutawayMiddle: nodes.Body_Back_Three_Piece_Venetian_Cutaway_Middle,
      BodyBackThreePieceFlorentineCutawayMiddle: nodes.Body_Back_Three_Piece_Florentine_Cutaway_Middle,
      BackPieceLeft1: nodes.Back_3Piece_Left,
      BodyBackDoubleStripLeft: nodes.Body_Back_Double_Strip_Left,
      BackPieceRight1: nodes.Back_3Piece_Right,
      BodyBackThreePieceVenetianCutawayRight: nodes.Body_Back_Three_Piece_Venetian_Cutaway_Right,
      BodyBackThreePieceFlorentineCutawayRight: nodes.Body_Back_Three_Piece_Florentine_Cutaway_Right,
      BodyBackThreePieceFlorentineCutawayLeft: nodes.Body_Back_Three_Piece_Florentine_Cutaway_Left,
      BodyCenterBackStrip: nodes.Body_Center_Back_Strip,
      BodyDoubleBackStripLeft: nodes.Body_Double_Back_Strip_Left,
      BodyDoubleBackStripRight: nodes.Body_Double_Back_Strip_Right,
      SurfaceBack: nodes.Surface_Back,
      BackCWNone: nodes.Back_CW_None,
      BackCWVene: nodes.Back_CW_Vene,
      BackCWFlor: nodes.Back_CW_Flor,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.BodyBackCenterStrip name="Body_Back_Center_Strip" userData={{ name: 'Body_Back_Center_Strip' }} />
      <instances.BodyBackDoubleStripRight name="Body_Back_Double_Strip_Right__1_" userData={{ name: 'Body_Back_Double_Strip_Right__1_' }} />
      <instances.BackPieceLeft name="Back_2Piece_Left" userData={{ name: 'Back_2Piece_Left' }} />
      <instances.BackPieceLeft name="Back_2Piece_Left_CW_Vene" userData={{ name: 'Back_2Piece_Left_CW_Vene' }} />
      <instances.BackPieceLeft name="Back_2Piece_Left_CW_Flor" userData={{ name: 'Back_2Piece_Left_CW_Flor' }} />
      <instances.BackPieceRight name="Back_2Piece_Right" userData={{ name: 'Back_2Piece_Right' }} />
      <instances.BackPieceRightCWVene name="Back_2Piece_Right_CW_Vene" userData={{ name: 'Back_2Piece_Right_CW_Vene' }} />
      <instances.BackPieceRightCWFlor name="Back_2Piece_Right_CW_Flor" userData={{ name: 'Back_2Piece_Right_CW_Flor' }} />
      <instances.BackPieceMiddle name="Back_3Piece_Middle" userData={{ name: 'Back_3Piece_Middle' }} />
      <instances.BodyBackThreePieceVenetianCutawayMiddle name="Body_Back_Three_Piece_Venetian_Cutaway_Middle" userData={{ name: 'Body_Back_Three_Piece_Venetian_Cutaway_Middle' }} />
      <instances.BodyBackThreePieceFlorentineCutawayMiddle name="Body_Back_Three_Piece_Florentine_Cutaway_Middle" userData={{ name: 'Body_Back_Three_Piece_Florentine_Cutaway_Middle' }} />
      <instances.BackPieceLeft1 name="Back_3Piece_Left" userData={{ name: 'Back_3Piece_Left' }} />
      <instances.BackPieceLeft1 name="Body_Back_Three_Piece_Venetian_Cutaway_Left" userData={{ name: 'Body_Back_Three_Piece_Venetian_Cutaway_Left' }} />
      <instances.BodyBackDoubleStripLeft name="Body_Back_Double_Strip_Left" userData={{ name: 'Body_Back_Double_Strip_Left' }} />
      <instances.BackPieceRight1 name="Back_3Piece_Right" userData={{ name: 'Back_3Piece_Right' }} />
      <instances.BodyBackThreePieceVenetianCutawayRight name="Body_Back_Three_Piece_Venetian_Cutaway_Right" userData={{ name: 'Body_Back_Three_Piece_Venetian_Cutaway_Right' }} />
      <instances.BodyBackThreePieceFlorentineCutawayRight name="Body_Back_Three_Piece_Florentine_Cutaway_Right" userData={{ name: 'Body_Back_Three_Piece_Florentine_Cutaway_Right' }} />
      <instances.BodyBackThreePieceFlorentineCutawayLeft name="Body_Back_Three_Piece_Florentine_Cutaway_Left" userData={{ name: 'Body_Back_Three_Piece_Florentine_Cutaway_Left' }} />
      <instances.BodyCenterBackStrip name="Body_Center_Back_Strip" userData={{ name: 'Body_Center_Back_Strip' }} />
      <instances.BodyDoubleBackStripLeft name="Body_Double_Back_Strip_Left" userData={{ name: 'Body_Double_Back_Strip_Left' }} />
      <instances.BodyDoubleBackStripRight name="Body_Double_Back_Strip_Right" userData={{ name: 'Body_Double_Back_Strip_Right' }} />
      <instances.SurfaceBack name="Surface_Back" userData={{ name: 'Surface_Back' }} />
      <instances.BackCWNone name="Back_CW_None" userData={{ name: 'Back_CW_None' }} />
      <instances.BackCWVene name="Back_CW_Vene" userData={{ name: 'Back_CW_Vene' }} />
      <instances.BackCWFlor name="Back_CW_Flor" userData={{ name: 'Back_CW_Flor' }} />
    </group>
  )
}

useGLTF.preload('/Back_Collection-transformed.glb')
