/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@7.1.3 ./public/luth-acoustic.glb --types --keepnames --draco --meta --transform --exportdefault --output ./src/_generated/LuthAcousticParlor.tsx 
*/

import {
  useAnimations,
  useGLTF,
  Merged,
  PerspectiveCamera,
  OrthographicCamera,
} from '@react-three/drei'
import { GroupProps, MeshProps, useGraph } from '@react-three/fiber'
import * as React from 'react'
import { AnimationClip, Material, Mesh, MeshPhysicalMaterial, MeshStandardMaterial } from 'three'
import { GLTF, SkeletonUtils } from 'three-stdlib'

interface LuthAcousticParlorGLTF extends GLTF {
  materials: {
    ['Oak - Glossy']: MeshStandardMaterial
    ['Oak - Glossy']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Oak - Glossy']: MeshStandardMaterial
    ['Oak - Glossy']: MeshStandardMaterial
    ['Oak - Glossy']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['Oak - Glossy']: MeshStandardMaterial
    ['Oak - Glossy']: MeshStandardMaterial
    ['Oak - Glossy']: MeshStandardMaterial
    ['Oak - Glossy']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Oak - Glossy']: MeshStandardMaterial
    ['Oak - Glossy']: MeshStandardMaterial
    ['Oak - Glossy']: MeshStandardMaterial
    ['Oak - Glossy']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    Mahogany: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    Mahogany: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    Mahogany: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    Mahogany: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    Mahogany: MeshStandardMaterial
    Mahogany: MeshStandardMaterial
    Mahogany: MeshStandardMaterial
    Mahogany: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    Mahogany: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    Mahogany: MeshStandardMaterial
    Mahogany: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['Acrylic (Red)']: MeshStandardMaterial
    ['Acrylic (Red)']: MeshStandardMaterial
    ['Acrylic (Red)']: MeshStandardMaterial
    ['Acrylic (Red)']: MeshStandardMaterial
    ['Acrylic (Red)']: MeshStandardMaterial
    ['Acrylic (Red)']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['Plastic - Glossy (Black)']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['Plastic - Glossy (Black)']: MeshStandardMaterial
    ['Plastic - Glossy (Black)']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Plastic - Glossy (Black)']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Plastic - Glossy (Black)']: MeshStandardMaterial
    ['Plastic - Glossy (Black)']: MeshStandardMaterial
    ['3D Ash - Unfinished']: MeshStandardMaterial
    ['Walnut - Semigloss']: MeshStandardMaterial
    ['Plastic - Glossy (Black)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['Plastic - Glossy (Black)']: MeshStandardMaterial
    ['Plastic - Glossy (Black)']: MeshStandardMaterial
    ['Plastic - Glossy (Black)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['Steel - Satin']: MeshStandardMaterial
    ['ABS (White)']: MeshStandardMaterial
  }
  nodes: {
    Body_Heel_Block: Mesh
    Body_Heel_Block_12: Mesh
    Body_Tail_Block_2: Mesh
    Body_Tail_Block_4: Mesh
    Body_Lining_Top_1: Mesh
    Body_Lining_Top_4: Mesh
    Body_Lining_Bottom_2: Mesh
    Body_Heel_Block_1: Mesh
    Body_Heel_Block_6: Mesh
    Body_Heel_Block_9: Mesh
    Body_Tail_Block_1: Mesh
    Body_Heel_Block_2: Mesh
    Body_Heel_Block_4: Mesh
    Body_Heel_Block_7: Mesh
    Body_Heel_Block_10: Mesh
    Body_Tail_Block_3: Mesh
    Body_Lining_Top_2: Mesh
    Body_Heel_Block_3: Mesh
    Body_Heel_Block_5: Mesh
    Body_Heel_Block_8: Mesh
    Body_Heel_Block_11: Mesh
    Body_Tail_Block: Mesh
    Body_Lining_Top_3: Mesh
    Body_End_Graft_Wedge: Mesh
    Body_End_Graft_Wedge_5: Mesh
    Body_Sides: Mesh
    Body_Sides_Venetian_Cutaway_1: Mesh
    Body_Lining_Top: Mesh
    Body_Lining_Bottom_1: Mesh
    Body_Sides_Venetian_Cutaway_6: Mesh
    Body_Sides_Venetian_Cutaway_8: Mesh
    Body_Lining_Bottom_4: Mesh
    Body_Lining_Bottom_3: Mesh
    Body_Sides_Florentine_Cutaway_2: Mesh
    Body_Sides_Florentine_Cutaway_5: Mesh
    Body_End_Graft_Wedge_3: Mesh
    Body_End_Graft_Wedge_1: Mesh
    Body_Sides_Florentine_Cutaway_8: Mesh
    Body_End_Graft_Wedge_6: Mesh
    Body_Lining_Bottom: Mesh
    Body_Sides_Scalloped_Cutaway_3: Mesh
    Body_End_Graft_Wedge_4: Mesh
    Body_End_Graft_Wedge_2: Mesh
    Body_Sides_Scalloped_Cutaway_4: Mesh
    Body_Sides_3: Mesh
    Body_Sides_1: Mesh
    Body_Sides_Scalloped_Cutaway_7: Mesh
    Body_Sides_2: Mesh
    Body_Sides_4: Mesh
    Body_Sides_Scalloped_Cutaway_10: Mesh
    Body_Sides_5: Mesh
    Body_Sides_6: Mesh
    Body_Sides_Arm_Bevel_2: Mesh
    Body_Sides_8: Mesh
    Body_Sides_7: Mesh
    Body_Sides_Arm_Bevel_4: Mesh
    Body_Sides_Venetian_Cutaway_3: Mesh
    Body_Sides_Venetian_Cutaway_2: Mesh
    Body_Sides_Venetian_Cutaway_5: Mesh
    Body_Sides_Arm_Bevel_6: Mesh
    Body_Sides_Venetian_Cutaway: Mesh
    Body_Sides_Venetian_Cutaway_4: Mesh
    Body_Sides_Venetian_Cutaway_7: Mesh
    Body_Sides_Florentine_Cutaway_1: Mesh
    Body_Sides_Florentine_Cutaway_3: Mesh
    Body_Sides_Florentine_Cutaway_4: Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway: Mesh
    Body_Sides_Florentine_Cutaway_7: Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway_2: Mesh
    Body_Sides_Florentine_Cutaway_6: Mesh
    Body_Sides_Florentine_Cutaway: Mesh
    Body_Sides_Scalloped_Cutaway_1: Mesh
    Body_Sides_Scalloped_Cutaway_6: Mesh
    Body_Sides_Scalloped_Cutaway_8: Mesh
    Body_Sides_Scalloped_Cutaway_2: Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway_7: Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway_8: Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway_3: Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway_5: Mesh
    Body_Rosette: Mesh
    Body_Sides_Scalloped_Cutaway: Mesh
    Body_Sides_Arm_Bevel_5: Mesh
    Body_Sides_Arm_Bevel_7: Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway_3: Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway_5: Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway_8: Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway_4: Mesh
    Body_Sides_Arm_Bevel: Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway_2: Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway_6: Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway_1: Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway_3: Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway_5: Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway: Mesh
    Body_Sides_Scalloped_Cutaway_5: Mesh
    Body_Sides_Scalloped_Cutaway_9: Mesh
    Body_Sides_Arm_Bevel_1: Mesh
    Body_Sides_Arm_Bevel_3: Mesh
    Body_Sides_Arm_Bevel_8: Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway_1: Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway_4: Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway_7: Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway: Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway_2: Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway_6: Mesh
    ['Body_Rosette_(1)']: Mesh
    Body_Brace_Fretboard_Reinforcement_Right: Mesh
    ['Body_Rosette_(4)']: Mesh
    Body_X_BraceC: Mesh
    Body_BraceG_Left: Mesh
    Body_Bridge_Plate: Mesh
    Body_Soundboard_Venetian_Cutaway: Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway_6: Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway_1: Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway_4: Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway_7: Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway_8: Mesh
    ['Body_Rosette_(2)']: Mesh
    Body_X_BraceB: Mesh
    Body_BraceG_Right: Mesh
    Body_BraceH_Right: Mesh
    Body_Soundboard_Arm_Bevel: Mesh
    ['Body_Rosette_(3)']: Mesh
    Body_Lateral_BraceA: Mesh
    Body_BraceE: Mesh
    Body_BraceF_Left: Mesh
    Body_Soundboard: Mesh
    Body_BraceD: Mesh
    Body_BraceF_Right: Mesh
    Body_BraceH_Left: Mesh
    Body_Soundboard_Arm_Bevel_Cutaway_Florentine: Mesh
    ['Body_Back_Double_Strip_Right_(1)']: Mesh
    Body_Center_Back_Strip: Mesh
    Body_Double_Back_Strip_Right: Mesh
    Body_Back_Venetian_Cutaway: Mesh
    Body_Back_Two_Piece_Florentine_Cutaway_Right: Mesh
    Body_Saddle: Mesh
    Body_Bridge_Pin_Inlay: Mesh
    Body_Bridge_Pin_Inlay_1: Mesh
    Body_Bridge_Pin_Inlay_2: Mesh
    Body_Bridge_Pin_Inlay_3: Mesh
    Body_Bridge_Pin_Inlay_4: Mesh
    Body_Bridge_Pin_Inlay_5: Mesh
    Body_Bridge: Mesh
    Body_Soundboard_Arm_Bevel_Cutaway_Venetian: Mesh
    Body_Back_Center_Strip: Mesh
    Body_Back_Double_Strip_Left: Mesh
    Body_Double_Back_Strip_Left: Mesh
    Body_Back: Mesh
    Body_Soundboard_Florentine_Cutaway: Mesh
    Body_Back_Three_Piece_Left: Mesh
    Body_Back_Three_Piece_Venetian_Cutaway_Left: Mesh
    Body_Back_Three_Piece_Florentine_Cutaway_Left: Mesh
    Body_Fret5: Mesh
    Body_Back_Florentine_Cutaway: Mesh
    Body_Back_Three_Piece_Florentine_Cutaway_Middle: Mesh
    Body_Back_Two_Piece_Venetian_Cutaway_Right: Mesh
    Body_Back_Three_Piece_Venetian_Cutaway_Middle: Mesh
    Body_Back_Three_Piece_Venetian_Cutaway_Right: Mesh
    Body_Bridge_Pin: Mesh
    Body_Bridge_Pin_1: Mesh
    Body_Bridge_Pin_2: Mesh
    Body_Bridge_Pin_3: Mesh
    Body_Bridge_Pin_4: Mesh
    Body_Bridge_Pin_5: Mesh
    Body_Back_Two_Piece_Left: Mesh
    Body_Back_Two_Piece_Venetian_Cutaway_Left: Mesh
    Body_Back_Two_Piece_Florentine_Cutaway_Left: Mesh
    Body_Back_Two_Piece_Right: Mesh
    Body_Back_Three_Piece_Middle: Mesh
    Body_Fret9: Mesh
    Body_Fret13: Mesh
    Body_Fret17: Mesh
    Body_Back_Three_Piece_Florentine_Cutaway_Right: Mesh
    Body_Fret3: Mesh
    Body_Fret7: Mesh
    Body_Fret2: Mesh
    Body_Fret6: Mesh
    Body_Fret10: Mesh
    Body_Back_Three_Piece_Right: Mesh
    Body_Fret1: Mesh
    Body_Fret4: Mesh
    Body_Nut: Mesh
    Body_Fret_Marker_Fret3: Mesh
    Body_Fret_Marker_Fret9: Mesh
    Body_Side_Fret_Marker_Fret7: Mesh
    ['Body_Fretboard_(1)_(1)']: Mesh
    Body_Fret11: Mesh
    Body_Fret15: Mesh
    Body_Fret19: Mesh
    Body_Fret_Marker_Fret17: Mesh
    Body_Fret14: Mesh
    Body_Fret18: Mesh
    Body_Fretboard: Mesh
    Body_Fret_Marker_Fret21: Mesh
    Body_Fret_Marker_Fret5: Mesh
    ['Body_Fretboard_(1)']: Mesh
    Body_Side_Fret_Marker_Fret5: Mesh
    Body_Side_Fret_Marker_Fret3: Mesh
    Body_Fret8: Mesh
    Body_Fret12: Mesh
    Body_Fret16: Mesh
    Body_Fret20: Mesh
    Body_Fret_Marker_Fret7: Mesh
    Body_Heel: Mesh
    ['Body_Fret_Marker_Fret12-2']: Mesh
    Body_Fret_Marker_Fret15: Mesh
    ['Body_Fretboard_(1)_(2)']: Mesh
    Body_Side_Fret_Marker_Fret17: Mesh
    Body_Side_Fret_Marker_Fret9: Mesh
    Surface_Neck_Profile: Mesh
    Body_Neck: Mesh
    Body_Pickguard: Mesh
    Body_Fretboard_Soundhole_Tangent: Mesh
    ['Body_Fret_Marker_Fret12-1']: Mesh
    ['Body_Fretboard_(1)_(3)']: Mesh
    Body_Side_Fret_Marker_Fret21: Mesh
    Body_Purfling_Top: Mesh
    Body_Purfling_Bottom_Venetian_Cutaway: Mesh
    Peg_Head_Tuner_Right: Mesh
    Peg_Head_Tuner_Right_1: Mesh
    Peg_Head_Tuner_Right_2: Mesh
    Peg_Head_Tuner_Right_3: Mesh
    Peg_Head_Tuner_Right_4: Mesh
    Peg_Head_Tuner_Right_5: Mesh
    Body_Purfling_Top_Arm_Bevel_Florentine_Cutaway: Mesh
    Peg_Head: Mesh
    Peg_Head_1: Mesh
    Peg_Head_2: Mesh
    Peg_Head_3: Mesh
    Peg_Head_4: Mesh
    Peg_Head_5: Mesh
    Body_Purfling_Bottom: Mesh
    Body_Purfling_Top_Florentine_Cutaway: Mesh
    Body_Headstock: Mesh
    Body_Fretboard_1: Mesh
    Body_Purfling_Top_Arm_Bevel: Mesh
    Body_Binding_Top_Venetian_Cutaway: Mesh
    Body_Purfling_Top_Arm_Bevel_Venetian_Cutaway: Mesh
    Body_Purfling_Top_Venetian_Cutaway: Mesh
    Body_Purfling_Bottom_Florentine_Cutaway: Mesh
    Body_Binding_Top: Mesh
    Body_Binding_Bottom_Venetian_Cutaway: Mesh
    Body_Binding_Top_Arm_Bevel: Mesh
    Body_String_A: Mesh
    Body_String_G: Mesh
    Body_Binding_Bottom: Mesh
    Body_Binding_Top_Florentine_Cutaway: Mesh
    Body_Binding_Top_Arm_Bevel_Venetian_Cutaway: Mesh
    Body_String_B: Mesh
    Body_Binding_Bottom_Florentine_Cutaway: Mesh
    Body_String_LowE: Mesh
    Body_String_D: Mesh
    Body_String_HighE: Mesh
    Body_Binding_Top_Arm_Bevel_Florentine_Cutaway: Mesh
  }
}

export interface LuthAcousticParlorProps extends GroupProps {}

const modelLoadPath = 'luth-acoustic.glb'
const draco = true

export function LuthAcousticParlor(props: LuthAcousticParlorProps) {
  const { nodes, materials } = useGLTF(modelLoadPath, draco) as LuthAcousticParlorGLTF

  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        name="active"
        makeDefault={false}
        far={1878.367}
        near={838.397}
        fov={22.62}
        position={[0.474, -1.033, -0.543]}
        rotation={[2.09, 0.368, -3.088]}
        scale={0.001}
        userData={{ name: 'active' }}
      />
      <PerspectiveCamera
        name="Active_Camera"
        makeDefault={false}
        far={1878.367}
        near={838.397}
        fov={22.62}
        position={[0.474, -1.033, -0.543]}
        rotation={[2.09, 0.368, -3.088]}
        scale={0.001}
        userData={{ name: 'Active Camera' }}
      />
      <mesh
        name="Body_Heel_Block"
        geometry={nodes.Body_Heel_Block.geometry}
        material={materials['Oak - Glossy']}
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <mesh
        name="Body_Heel_Block_12"
        geometry={nodes.Body_Heel_Block_12.geometry}
        material={materials['Oak - Glossy']}
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <mesh
        name="Body_Tail_Block_2"
        geometry={nodes.Body_Tail_Block_2.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Tail_Block' }}
      />
      <mesh
        name="Body_Tail_Block_4"
        geometry={nodes.Body_Tail_Block_4.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Tail_Block' }}
      />
      <mesh
        name="Body_Lining_Top_1"
        geometry={nodes.Body_Lining_Top_1.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Lining_Top' }}
      />
      <mesh
        name="Body_Lining_Top_4"
        geometry={nodes.Body_Lining_Top_4.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Lining_Top' }}
      />
      <mesh
        name="Body_Lining_Bottom_2"
        geometry={nodes.Body_Lining_Bottom_2.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Lining_Bottom' }}
      />
      <mesh
        name="Body_Heel_Block_1"
        geometry={nodes.Body_Heel_Block_1.geometry}
        material={materials['Oak - Glossy']}
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <mesh
        name="Body_Heel_Block_6"
        geometry={nodes.Body_Heel_Block_6.geometry}
        material={materials['Oak - Glossy']}
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <mesh
        name="Body_Heel_Block_9"
        geometry={nodes.Body_Heel_Block_9.geometry}
        material={materials['Oak - Glossy']}
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <mesh
        name="Body_Tail_Block_1"
        geometry={nodes.Body_Tail_Block_1.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Tail_Block' }}
      />
      <mesh
        name="Body_Heel_Block_2"
        geometry={nodes.Body_Heel_Block_2.geometry}
        material={materials['Oak - Glossy']}
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <mesh
        name="Body_Heel_Block_4"
        geometry={nodes.Body_Heel_Block_4.geometry}
        material={materials['Oak - Glossy']}
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <mesh
        name="Body_Heel_Block_7"
        geometry={nodes.Body_Heel_Block_7.geometry}
        material={materials['Oak - Glossy']}
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <mesh
        name="Body_Heel_Block_10"
        geometry={nodes.Body_Heel_Block_10.geometry}
        material={materials['Oak - Glossy']}
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <mesh
        name="Body_Tail_Block_3"
        geometry={nodes.Body_Tail_Block_3.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Tail_Block' }}
      />
      <mesh
        name="Body_Lining_Top_2"
        geometry={nodes.Body_Lining_Top_2.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Lining_Top' }}
      />
      <mesh
        name="Body_Heel_Block_3"
        geometry={nodes.Body_Heel_Block_3.geometry}
        material={materials['Oak - Glossy']}
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <mesh
        name="Body_Heel_Block_5"
        geometry={nodes.Body_Heel_Block_5.geometry}
        material={materials['Oak - Glossy']}
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <mesh
        name="Body_Heel_Block_8"
        geometry={nodes.Body_Heel_Block_8.geometry}
        material={materials['Oak - Glossy']}
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <mesh
        name="Body_Heel_Block_11"
        geometry={nodes.Body_Heel_Block_11.geometry}
        material={materials['Oak - Glossy']}
        scale={0.001}
        userData={{ name: 'Body_Heel_Block' }}
      />
      <mesh
        name="Body_Tail_Block"
        geometry={nodes.Body_Tail_Block.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Tail_Block' }}
      />
      <mesh
        name="Body_Lining_Top_3"
        geometry={nodes.Body_Lining_Top_3.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Lining_Top' }}
      />
      <mesh
        name="Body_End_Graft_Wedge"
        geometry={nodes.Body_End_Graft_Wedge.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <mesh
        name="Body_End_Graft_Wedge_5"
        geometry={nodes.Body_End_Graft_Wedge_5.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <mesh
        name="Body_Sides"
        geometry={nodes.Body_Sides.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides' }}
      />
      <mesh
        name="Body_Sides_Venetian_Cutaway_1"
        geometry={nodes.Body_Sides_Venetian_Cutaway_1.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Lining_Top"
        geometry={nodes.Body_Lining_Top.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Lining_Top' }}
      />
      <mesh
        name="Body_Lining_Bottom_1"
        geometry={nodes.Body_Lining_Bottom_1.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Lining_Bottom' }}
      />
      <mesh
        name="Body_Sides_Venetian_Cutaway_6"
        geometry={nodes.Body_Sides_Venetian_Cutaway_6.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Venetian_Cutaway_8"
        geometry={nodes.Body_Sides_Venetian_Cutaway_8.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Lining_Bottom_4"
        geometry={nodes.Body_Lining_Bottom_4.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Lining_Bottom' }}
      />
      <mesh
        name="Body_Lining_Bottom_3"
        geometry={nodes.Body_Lining_Bottom_3.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Lining_Bottom' }}
      />
      <mesh
        name="Body_Sides_Florentine_Cutaway_2"
        geometry={nodes.Body_Sides_Florentine_Cutaway_2.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Florentine_Cutaway_5"
        geometry={nodes.Body_Sides_Florentine_Cutaway_5.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_End_Graft_Wedge_3"
        geometry={nodes.Body_End_Graft_Wedge_3.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <mesh
        name="Body_End_Graft_Wedge_1"
        geometry={nodes.Body_End_Graft_Wedge_1.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <mesh
        name="Body_Sides_Florentine_Cutaway_8"
        geometry={nodes.Body_Sides_Florentine_Cutaway_8.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_End_Graft_Wedge_6"
        geometry={nodes.Body_End_Graft_Wedge_6.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <mesh
        name="Body_Lining_Bottom"
        geometry={nodes.Body_Lining_Bottom.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Lining_Bottom' }}
      />
      <mesh
        name="Body_Sides_Scalloped_Cutaway_3"
        geometry={nodes.Body_Sides_Scalloped_Cutaway_3.geometry}
        material={materials.Mahogany}
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_End_Graft_Wedge_4"
        geometry={nodes.Body_End_Graft_Wedge_4.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <mesh
        name="Body_End_Graft_Wedge_2"
        geometry={nodes.Body_End_Graft_Wedge_2.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <mesh
        name="Body_Sides_Scalloped_Cutaway_4"
        geometry={nodes.Body_Sides_Scalloped_Cutaway_4.geometry}
        material={materials.Mahogany}
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Sides_3"
        geometry={nodes.Body_Sides_3.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides' }}
      />
      <mesh
        name="Body_Sides_1"
        geometry={nodes.Body_Sides_1.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides' }}
      />
      <mesh
        name="Body_Sides_Scalloped_Cutaway_7"
        geometry={nodes.Body_Sides_Scalloped_Cutaway_7.geometry}
        material={materials.Mahogany}
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Sides_2"
        geometry={nodes.Body_Sides_2.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides' }}
      />
      <mesh
        name="Body_Sides_4"
        geometry={nodes.Body_Sides_4.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides' }}
      />
      <mesh
        name="Body_Sides_Scalloped_Cutaway_10"
        geometry={nodes.Body_Sides_Scalloped_Cutaway_10.geometry}
        material={materials.Mahogany}
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Sides_5"
        geometry={nodes.Body_Sides_5.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides' }}
      />
      <mesh
        name="Body_Sides_6"
        geometry={nodes.Body_Sides_6.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_2"
        geometry={nodes.Body_Sides_Arm_Bevel_2.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <mesh
        name="Body_Sides_8"
        geometry={nodes.Body_Sides_8.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides' }}
      />
      <mesh
        name="Body_Sides_7"
        geometry={nodes.Body_Sides_7.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_4"
        geometry={nodes.Body_Sides_Arm_Bevel_4.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <mesh
        name="Body_Sides_Venetian_Cutaway_3"
        geometry={nodes.Body_Sides_Venetian_Cutaway_3.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Venetian_Cutaway_2"
        geometry={nodes.Body_Sides_Venetian_Cutaway_2.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Venetian_Cutaway_5"
        geometry={nodes.Body_Sides_Venetian_Cutaway_5.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_6"
        geometry={nodes.Body_Sides_Arm_Bevel_6.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <mesh
        name="Body_Sides_Venetian_Cutaway"
        geometry={nodes.Body_Sides_Venetian_Cutaway.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Venetian_Cutaway_4"
        geometry={nodes.Body_Sides_Venetian_Cutaway_4.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Venetian_Cutaway_7"
        geometry={nodes.Body_Sides_Venetian_Cutaway_7.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Florentine_Cutaway_1"
        geometry={nodes.Body_Sides_Florentine_Cutaway_1.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Florentine_Cutaway_3"
        geometry={nodes.Body_Sides_Florentine_Cutaway_3.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Florentine_Cutaway_4"
        geometry={nodes.Body_Sides_Florentine_Cutaway_4.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway"
        geometry={nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Florentine_Cutaway_7"
        geometry={nodes.Body_Sides_Florentine_Cutaway_7.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway_2"
        geometry={nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway_2.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Florentine_Cutaway_6"
        geometry={nodes.Body_Sides_Florentine_Cutaway_6.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Florentine_Cutaway"
        geometry={nodes.Body_Sides_Florentine_Cutaway.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Scalloped_Cutaway_1"
        geometry={nodes.Body_Sides_Scalloped_Cutaway_1.geometry}
        material={materials.Mahogany}
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Scalloped_Cutaway_6"
        geometry={nodes.Body_Sides_Scalloped_Cutaway_6.geometry}
        material={materials.Mahogany}
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Scalloped_Cutaway_8"
        geometry={nodes.Body_Sides_Scalloped_Cutaway_8.geometry}
        material={materials.Mahogany}
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Scalloped_Cutaway_2"
        geometry={nodes.Body_Sides_Scalloped_Cutaway_2.geometry}
        material={materials.Mahogany}
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway_7"
        geometry={nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway_7.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway_8"
        geometry={nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway_8.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway_3"
        geometry={nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway_3.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway_5"
        geometry={nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway_5.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Rosette"
        geometry={nodes.Body_Rosette.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Rosette' }}
      />
      <mesh
        name="Body_Sides_Scalloped_Cutaway"
        geometry={nodes.Body_Sides_Scalloped_Cutaway.geometry}
        material={materials.Mahogany}
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_5"
        geometry={nodes.Body_Sides_Arm_Bevel_5.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_7"
        geometry={nodes.Body_Sides_Arm_Bevel_7.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway_3"
        geometry={nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway_3.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway_5"
        geometry={nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway_5.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway_8"
        geometry={nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway_8.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway_4"
        geometry={nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway_4.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel"
        geometry={nodes.Body_Sides_Arm_Bevel.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway_2"
        geometry={nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway_2.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway_6"
        geometry={nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway_6.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway_1"
        geometry={nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway_1.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway_3"
        geometry={nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway_3.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway_5"
        geometry={nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway_5.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway"
        geometry={nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Scalloped_Cutaway_5"
        geometry={nodes.Body_Sides_Scalloped_Cutaway_5.geometry}
        material={materials.Mahogany}
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Scalloped_Cutaway_9"
        geometry={nodes.Body_Sides_Scalloped_Cutaway_9.geometry}
        material={materials.Mahogany}
        scale={0.001}
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_1"
        geometry={nodes.Body_Sides_Arm_Bevel_1.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_3"
        geometry={nodes.Body_Sides_Arm_Bevel_3.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_8"
        geometry={nodes.Body_Sides_Arm_Bevel_8.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway_1"
        geometry={nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway_1.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway_4"
        geometry={nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway_4.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway_7"
        geometry={nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway_7.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway"
        geometry={nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway_2"
        geometry={nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway_2.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway_6"
        geometry={nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway_6.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Rosette_(1)"
        geometry={nodes['Body_Rosette_(1)'].geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Rosette (1)' }}
      />
      <mesh
        name="Body_Brace_Fretboard_Reinforcement_Right"
        geometry={nodes.Body_Brace_Fretboard_Reinforcement_Right.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Brace_Fretboard_Reinforcement_Right' }}
      />
      <mesh
        name="Body_Rosette_(4)"
        geometry={nodes['Body_Rosette_(4)'].geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Rosette (4)' }}
      />
      <mesh
        name="Body_X_BraceC"
        geometry={nodes.Body_X_BraceC.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_X_BraceC' }}
      />
      <mesh
        name="Body_BraceG_Left"
        geometry={nodes.Body_BraceG_Left.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_BraceG_Left' }}
      />
      <mesh
        name="Body_Bridge_Plate"
        geometry={nodes.Body_Bridge_Plate.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Plate' }}
      />
      <mesh
        name="Body_Soundboard_Venetian_Cutaway"
        geometry={nodes.Body_Soundboard_Venetian_Cutaway.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Soundboard_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway_6"
        geometry={nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway_6.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway_1"
        geometry={nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway_1.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway_4"
        geometry={nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway_4.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway_7"
        geometry={nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway_7.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway_8"
        geometry={nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway_8.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <mesh
        name="Body_Rosette_(2)"
        geometry={nodes['Body_Rosette_(2)'].geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Rosette (2)' }}
      />
      <mesh
        name="Body_X_BraceB"
        geometry={nodes.Body_X_BraceB.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_X_BraceB' }}
      />
      <mesh
        name="Body_BraceG_Right"
        geometry={nodes.Body_BraceG_Right.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_BraceG_Right' }}
      />
      <mesh
        name="Body_BraceH_Right"
        geometry={nodes.Body_BraceH_Right.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_BraceH_Right' }}
      />
      <mesh
        name="Body_Soundboard_Arm_Bevel"
        geometry={nodes.Body_Soundboard_Arm_Bevel.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Soundboard_Arm_Bevel' }}
      />
      <mesh
        name="Body_Rosette_(3)"
        geometry={nodes['Body_Rosette_(3)'].geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Rosette (3)' }}
      />
      <mesh
        name="Body_Lateral_BraceA"
        geometry={nodes.Body_Lateral_BraceA.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Lateral_BraceA' }}
      />
      <mesh
        name="Body_BraceE"
        geometry={nodes.Body_BraceE.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_BraceE' }}
      />
      <mesh
        name="Body_BraceF_Left"
        geometry={nodes.Body_BraceF_Left.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_BraceF_Left' }}
      />
      <mesh
        name="Body_Soundboard"
        geometry={nodes.Body_Soundboard.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Soundboard' }}
      />
      <mesh
        name="Body_BraceD"
        geometry={nodes.Body_BraceD.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_BraceD' }}
      />
      <mesh
        name="Body_BraceF_Right"
        geometry={nodes.Body_BraceF_Right.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_BraceF_Right' }}
      />
      <mesh
        name="Body_BraceH_Left"
        geometry={nodes.Body_BraceH_Left.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_BraceH_Left' }}
      />
      <mesh
        name="Body_Soundboard_Arm_Bevel_Cutaway_Florentine"
        geometry={nodes.Body_Soundboard_Arm_Bevel_Cutaway_Florentine.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Soundboard_Arm_Bevel_Cutaway_Florentine' }}
      />
      <mesh
        name="Body_Back_Double_Strip_Right_(1)"
        geometry={nodes['Body_Back_Double_Strip_Right_(1)'].geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Back_Double_Strip_Right (1)' }}
      />
      <mesh
        name="Body_Center_Back_Strip"
        geometry={nodes.Body_Center_Back_Strip.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Center_Back_Strip' }}
      />
      <mesh
        name="Body_Double_Back_Strip_Right"
        geometry={nodes.Body_Double_Back_Strip_Right.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Double_Back_Strip_Right' }}
      />
      <mesh
        name="Body_Back_Venetian_Cutaway"
        geometry={nodes.Body_Back_Venetian_Cutaway.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Back_Two_Piece_Florentine_Cutaway_Right"
        geometry={nodes.Body_Back_Two_Piece_Florentine_Cutaway_Right.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Two_Piece_Florentine_Cutaway_Right' }}
      />
      <mesh
        name="Body_Saddle"
        geometry={nodes.Body_Saddle.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Saddle' }}
      />
      <mesh
        name="Body_Bridge_Pin_Inlay"
        geometry={nodes.Body_Bridge_Pin_Inlay.geometry}
        material={materials['Acrylic (Red)']}
        position={[-0.027, -0.156, 0.008]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin_Inlay' }}
      />
      <mesh
        name="Body_Bridge_Pin_Inlay_1"
        geometry={nodes.Body_Bridge_Pin_Inlay_1.geometry}
        material={materials['Acrylic (Red)']}
        position={[-0.017, -0.156, 0.007]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin_Inlay' }}
      />
      <mesh
        name="Body_Bridge_Pin_Inlay_2"
        geometry={nodes.Body_Bridge_Pin_Inlay_2.geometry}
        material={materials['Acrylic (Red)']}
        position={[-0.006, -0.156, 0.008]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin_Inlay' }}
      />
      <mesh
        name="Body_Bridge_Pin_Inlay_3"
        geometry={nodes.Body_Bridge_Pin_Inlay_3.geometry}
        material={materials['Acrylic (Red)']}
        position={[0.005, -0.156, 0.007]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin_Inlay' }}
      />
      <mesh
        name="Body_Bridge_Pin_Inlay_4"
        geometry={nodes.Body_Bridge_Pin_Inlay_4.geometry}
        material={materials['Acrylic (Red)']}
        position={[0.016, -0.156, 0.007]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin_Inlay' }}
      />
      <mesh
        name="Body_Bridge_Pin_Inlay_5"
        geometry={nodes.Body_Bridge_Pin_Inlay_5.geometry}
        material={materials['Acrylic (Red)']}
        position={[0.027, -0.156, 0.007]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin_Inlay' }}
      />
      <mesh
        name="Body_Bridge"
        geometry={nodes.Body_Bridge.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Bridge' }}
      />
      <mesh
        name="Body_Soundboard_Arm_Bevel_Cutaway_Venetian"
        geometry={nodes.Body_Soundboard_Arm_Bevel_Cutaway_Venetian.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Soundboard_Arm_Bevel_Cutaway_Venetian' }}
      />
      <mesh
        name="Body_Back_Center_Strip"
        geometry={nodes.Body_Back_Center_Strip.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Center_Strip' }}
      />
      <mesh
        name="Body_Back_Double_Strip_Left"
        geometry={nodes.Body_Back_Double_Strip_Left.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Back_Double_Strip_Left' }}
      />
      <mesh
        name="Body_Double_Back_Strip_Left"
        geometry={nodes.Body_Double_Back_Strip_Left.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Double_Back_Strip_Left' }}
      />
      <mesh
        name="Body_Back"
        geometry={nodes.Body_Back.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back' }}
      />
      <mesh
        name="Body_Soundboard_Florentine_Cutaway"
        geometry={nodes.Body_Soundboard_Florentine_Cutaway.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Soundboard_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Back_Three_Piece_Left"
        geometry={nodes.Body_Back_Three_Piece_Left.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Left' }}
      />
      <mesh
        name="Body_Back_Three_Piece_Venetian_Cutaway_Left"
        geometry={nodes.Body_Back_Three_Piece_Venetian_Cutaway_Left.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Venetian_Cutaway_Left' }}
      />
      <mesh
        name="Body_Back_Three_Piece_Florentine_Cutaway_Left"
        geometry={nodes.Body_Back_Three_Piece_Florentine_Cutaway_Left.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Florentine_Cutaway_Left' }}
      />
      <mesh
        name="Body_Fret5"
        geometry={nodes.Body_Fret5.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret5' }}
      />
      <mesh
        name="Body_Back_Florentine_Cutaway"
        geometry={nodes.Body_Back_Florentine_Cutaway.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Back_Three_Piece_Florentine_Cutaway_Middle"
        geometry={nodes.Body_Back_Three_Piece_Florentine_Cutaway_Middle.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Florentine_Cutaway_Middle' }}
      />
      <mesh
        name="Body_Back_Two_Piece_Venetian_Cutaway_Right"
        geometry={nodes.Body_Back_Two_Piece_Venetian_Cutaway_Right.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Two_Piece_Venetian_Cutaway_Right' }}
      />
      <mesh
        name="Body_Back_Three_Piece_Venetian_Cutaway_Middle"
        geometry={nodes.Body_Back_Three_Piece_Venetian_Cutaway_Middle.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Venetian_Cutaway_Middle' }}
      />
      <mesh
        name="Body_Back_Three_Piece_Venetian_Cutaway_Right"
        geometry={nodes.Body_Back_Three_Piece_Venetian_Cutaway_Right.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Venetian_Cutaway_Right' }}
      />
      <mesh
        name="Body_Bridge_Pin"
        geometry={nodes.Body_Bridge_Pin.geometry}
        material={materials['ABS (White)']}
        position={[-0.027, -0.156, 0.008]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin' }}
      />
      <mesh
        name="Body_Bridge_Pin_1"
        geometry={nodes.Body_Bridge_Pin_1.geometry}
        material={materials['ABS (White)']}
        position={[-0.017, -0.156, 0.007]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin' }}
      />
      <mesh
        name="Body_Bridge_Pin_2"
        geometry={nodes.Body_Bridge_Pin_2.geometry}
        material={materials['ABS (White)']}
        position={[-0.006, -0.156, 0.008]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin' }}
      />
      <mesh
        name="Body_Bridge_Pin_3"
        geometry={nodes.Body_Bridge_Pin_3.geometry}
        material={materials['ABS (White)']}
        position={[0.005, -0.156, 0.007]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin' }}
      />
      <mesh
        name="Body_Bridge_Pin_4"
        geometry={nodes.Body_Bridge_Pin_4.geometry}
        material={materials['ABS (White)']}
        position={[0.016, -0.156, 0.007]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin' }}
      />
      <mesh
        name="Body_Bridge_Pin_5"
        geometry={nodes.Body_Bridge_Pin_5.geometry}
        material={materials['ABS (White)']}
        position={[0.027, -0.156, 0.007]}
        scale={0.001}
        userData={{ name: 'Body_Bridge_Pin' }}
      />
      <mesh
        name="Body_Back_Two_Piece_Left"
        geometry={nodes.Body_Back_Two_Piece_Left.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Two_Piece_Left' }}
      />
      <mesh
        name="Body_Back_Two_Piece_Venetian_Cutaway_Left"
        geometry={nodes.Body_Back_Two_Piece_Venetian_Cutaway_Left.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Two_Piece_Venetian_Cutaway_Left' }}
      />
      <mesh
        name="Body_Back_Two_Piece_Florentine_Cutaway_Left"
        geometry={nodes.Body_Back_Two_Piece_Florentine_Cutaway_Left.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Two_Piece_Florentine_Cutaway_Left' }}
      />
      <mesh
        name="Body_Back_Two_Piece_Right"
        geometry={nodes.Body_Back_Two_Piece_Right.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Two_Piece_Right' }}
      />
      <mesh
        name="Body_Back_Three_Piece_Middle"
        geometry={nodes.Body_Back_Three_Piece_Middle.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Middle' }}
      />
      <mesh
        name="Body_Fret9"
        geometry={nodes.Body_Fret9.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret9' }}
      />
      <mesh
        name="Body_Fret13"
        geometry={nodes.Body_Fret13.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret13' }}
      />
      <mesh
        name="Body_Fret17"
        geometry={nodes.Body_Fret17.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret17' }}
      />
      <mesh
        name="Body_Back_Three_Piece_Florentine_Cutaway_Right"
        geometry={nodes.Body_Back_Three_Piece_Florentine_Cutaway_Right.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Florentine_Cutaway_Right' }}
      />
      <mesh
        name="Body_Fret3"
        geometry={nodes.Body_Fret3.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret3' }}
      />
      <mesh
        name="Body_Fret7"
        geometry={nodes.Body_Fret7.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret7' }}
      />
      <mesh
        name="Body_Fret2"
        geometry={nodes.Body_Fret2.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret2' }}
      />
      <mesh
        name="Body_Fret6"
        geometry={nodes.Body_Fret6.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret6' }}
      />
      <mesh
        name="Body_Fret10"
        geometry={nodes.Body_Fret10.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret10' }}
      />
      <mesh
        name="Body_Back_Three_Piece_Right"
        geometry={nodes.Body_Back_Three_Piece_Right.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Back_Three_Piece_Right' }}
      />
      <mesh
        name="Body_Fret1"
        geometry={nodes.Body_Fret1.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret1' }}
      />
      <mesh
        name="Body_Fret4"
        geometry={nodes.Body_Fret4.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret4' }}
      />
      <mesh
        name="Body_Nut"
        geometry={nodes.Body_Nut.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Nut' }}
      />
      <mesh
        name="Body_Fret_Marker_Fret3"
        geometry={nodes.Body_Fret_Marker_Fret3.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret3' }}
      />
      <mesh
        name="Body_Fret_Marker_Fret9"
        geometry={nodes.Body_Fret_Marker_Fret9.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret9' }}
      />
      <mesh
        name="Body_Side_Fret_Marker_Fret7"
        geometry={nodes.Body_Side_Fret_Marker_Fret7.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Side_Fret_Marker_Fret7' }}
      />
      <mesh
        name="Body_Fretboard_(1)_(1)"
        geometry={nodes['Body_Fretboard_(1)_(1)'].geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Fretboard (1) (1)' }}
      />
      <mesh
        name="Body_Fret11"
        geometry={nodes.Body_Fret11.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret11' }}
      />
      <mesh
        name="Body_Fret15"
        geometry={nodes.Body_Fret15.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret15' }}
      />
      <mesh
        name="Body_Fret19"
        geometry={nodes.Body_Fret19.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret19' }}
      />
      <mesh
        name="Body_Fret_Marker_Fret17"
        geometry={nodes.Body_Fret_Marker_Fret17.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret17' }}
      />
      <mesh
        name="Body_Fret14"
        geometry={nodes.Body_Fret14.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret14' }}
      />
      <mesh
        name="Body_Fret18"
        geometry={nodes.Body_Fret18.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret18' }}
      />
      <mesh
        name="Body_Fretboard"
        geometry={nodes.Body_Fretboard.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Fretboard' }}
      />
      <mesh
        name="Body_Fret_Marker_Fret21"
        geometry={nodes.Body_Fret_Marker_Fret21.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret21' }}
      />
      <mesh
        name="Body_Fret_Marker_Fret5"
        geometry={nodes.Body_Fret_Marker_Fret5.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret5' }}
      />
      <mesh
        name="Body_Fretboard_(1)"
        geometry={nodes['Body_Fretboard_(1)'].geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Fretboard (1)' }}
      />
      <mesh
        name="Body_Side_Fret_Marker_Fret5"
        geometry={nodes.Body_Side_Fret_Marker_Fret5.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Side_Fret_Marker_Fret5' }}
      />
      <mesh
        name="Body_Side_Fret_Marker_Fret3"
        geometry={nodes.Body_Side_Fret_Marker_Fret3.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Side_Fret_Marker_Fret3' }}
      />
      <mesh
        name="Body_Fret8"
        geometry={nodes.Body_Fret8.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret8' }}
      />
      <mesh
        name="Body_Fret12"
        geometry={nodes.Body_Fret12.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret12' }}
      />
      <mesh
        name="Body_Fret16"
        geometry={nodes.Body_Fret16.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret16' }}
      />
      <mesh
        name="Body_Fret20"
        geometry={nodes.Body_Fret20.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_Fret20' }}
      />
      <mesh
        name="Body_Fret_Marker_Fret7"
        geometry={nodes.Body_Fret_Marker_Fret7.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret7' }}
      />
      <mesh
        name="Body_Heel"
        geometry={nodes.Body_Heel.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Heel' }}
      />
      <mesh
        name="Body_Fret_Marker_Fret12-2"
        geometry={nodes['Body_Fret_Marker_Fret12-2'].geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret12-2' }}
      />
      <mesh
        name="Body_Fret_Marker_Fret15"
        geometry={nodes.Body_Fret_Marker_Fret15.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret15' }}
      />
      <mesh
        name="Body_Fretboard_(1)_(2)"
        geometry={nodes['Body_Fretboard_(1)_(2)'].geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Fretboard (1) (2)' }}
      />
      <mesh
        name="Body_Side_Fret_Marker_Fret17"
        geometry={nodes.Body_Side_Fret_Marker_Fret17.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Side_Fret_Marker_Fret17' }}
      />
      <mesh
        name="Body_Side_Fret_Marker_Fret9"
        geometry={nodes.Body_Side_Fret_Marker_Fret9.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Side_Fret_Marker_Fret9' }}
      />
      <mesh
        name="Surface_Neck_Profile"
        geometry={nodes.Surface_Neck_Profile.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Surface_Neck_Profile' }}
      />
      <mesh
        name="Body_Neck"
        geometry={nodes.Body_Neck.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Neck' }}
      />
      <mesh
        name="Body_Pickguard"
        geometry={nodes.Body_Pickguard.geometry}
        material={materials['Plastic - Glossy (Black)']}
        scale={0.001}
        userData={{ name: 'Body_Pickguard' }}
      />
      <mesh
        name="Body_Fretboard_Soundhole_Tangent"
        geometry={nodes.Body_Fretboard_Soundhole_Tangent.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Fretboard_Soundhole_Tangent' }}
      />
      <mesh
        name="Body_Fret_Marker_Fret12-1"
        geometry={nodes['Body_Fret_Marker_Fret12-1'].geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Fret_Marker_Fret12-1' }}
      />
      <mesh
        name="Body_Fretboard_(1)_(3)"
        geometry={nodes['Body_Fretboard_(1)_(3)'].geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Fretboard (1) (3)' }}
      />
      <mesh
        name="Body_Side_Fret_Marker_Fret21"
        geometry={nodes.Body_Side_Fret_Marker_Fret21.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Side_Fret_Marker_Fret21' }}
      />
      <mesh
        name="Body_Purfling_Top"
        geometry={nodes.Body_Purfling_Top.geometry}
        material={materials['Plastic - Glossy (Black)']}
        scale={0.001}
        userData={{ name: 'Body_Purfling_Top' }}
      />
      <mesh
        name="Body_Purfling_Bottom_Venetian_Cutaway"
        geometry={nodes.Body_Purfling_Bottom_Venetian_Cutaway.geometry}
        material={materials['Plastic - Glossy (Black)']}
        scale={0.001}
        userData={{ name: 'Body_Purfling_Bottom_Venetian_Cutaway' }}
      />
      <mesh
        name="Peg_Head_Tuner_Right"
        geometry={nodes.Peg_Head_Tuner_Right.geometry}
        material={materials['Steel - Satin']}
        position={[-0.02, 0.544, -0.02]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head_Tuner_Right' }}
      />
      <mesh
        name="Peg_Head_Tuner_Right_1"
        geometry={nodes.Peg_Head_Tuner_Right_1.geometry}
        material={materials['Steel - Satin']}
        position={[-0.022, 0.583, -0.031]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head_Tuner_Right' }}
      />
      <mesh
        name="Peg_Head_Tuner_Right_2"
        geometry={nodes.Peg_Head_Tuner_Right_2.geometry}
        material={materials['Steel - Satin']}
        position={[-0.024, 0.624, -0.04]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head_Tuner_Right' }}
      />
      <mesh
        name="Peg_Head_Tuner_Right_3"
        geometry={nodes.Peg_Head_Tuner_Right_3.geometry}
        material={materials['Steel - Satin']}
        position={[0.02, 0.543, -0.02]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head_Tuner_Right' }}
      />
      <mesh
        name="Peg_Head_Tuner_Right_4"
        geometry={nodes.Peg_Head_Tuner_Right_4.geometry}
        material={materials['Steel - Satin']}
        position={[0.022, 0.584, -0.028]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head_Tuner_Right' }}
      />
      <mesh
        name="Peg_Head_Tuner_Right_5"
        geometry={nodes.Peg_Head_Tuner_Right_5.geometry}
        material={materials['Steel - Satin']}
        position={[0.024, 0.624, -0.037]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head_Tuner_Right' }}
      />
      <mesh
        name="Body_Purfling_Top_Arm_Bevel_Florentine_Cutaway"
        geometry={nodes.Body_Purfling_Top_Arm_Bevel_Florentine_Cutaway.geometry}
        material={materials['Plastic - Glossy (Black)']}
        scale={0.001}
        userData={{ name: 'Body_Purfling_Top_Arm_Bevel_Florentine_Cutaway' }}
      />
      <mesh
        name="Peg_Head"
        geometry={nodes.Peg_Head.geometry}
        material={materials['Steel - Satin']}
        position={[-0.02, 0.544, -0.02]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head' }}
      />
      <mesh
        name="Peg_Head_1"
        geometry={nodes.Peg_Head_1.geometry}
        material={materials['Steel - Satin']}
        position={[-0.022, 0.583, -0.031]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head' }}
      />
      <mesh
        name="Peg_Head_2"
        geometry={nodes.Peg_Head_2.geometry}
        material={materials['Steel - Satin']}
        position={[-0.024, 0.624, -0.04]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head' }}
      />
      <mesh
        name="Peg_Head_3"
        geometry={nodes.Peg_Head_3.geometry}
        material={materials['Steel - Satin']}
        position={[0.02, 0.543, -0.02]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head' }}
      />
      <mesh
        name="Peg_Head_4"
        geometry={nodes.Peg_Head_4.geometry}
        material={materials['Steel - Satin']}
        position={[0.022, 0.584, -0.028]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head' }}
      />
      <mesh
        name="Peg_Head_5"
        geometry={nodes.Peg_Head_5.geometry}
        material={materials['Steel - Satin']}
        position={[0.024, 0.624, -0.037]}
        rotation={[-0.211, 0, 0]}
        scale={0.001}
        userData={{ name: 'Peg_Head' }}
      />
      <mesh
        name="Body_Purfling_Bottom"
        geometry={nodes.Body_Purfling_Bottom.geometry}
        material={materials['Plastic - Glossy (Black)']}
        scale={0.001}
        userData={{ name: 'Body_Purfling_Bottom' }}
      />
      <mesh
        name="Body_Purfling_Top_Florentine_Cutaway"
        geometry={nodes.Body_Purfling_Top_Florentine_Cutaway.geometry}
        material={materials['Plastic - Glossy (Black)']}
        scale={0.001}
        userData={{ name: 'Body_Purfling_Top_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Headstock"
        geometry={nodes.Body_Headstock.geometry}
        material={materials['3D Ash - Unfinished']}
        scale={0.001}
        userData={{ name: 'Body_Headstock' }}
      />
      <mesh
        name="Body_Fretboard_1"
        geometry={nodes.Body_Fretboard_1.geometry}
        material={materials['Walnut - Semigloss']}
        scale={0.001}
        userData={{ name: 'Body_Fretboard' }}
      />
      <mesh
        name="Body_Purfling_Top_Arm_Bevel"
        geometry={nodes.Body_Purfling_Top_Arm_Bevel.geometry}
        material={materials['Plastic - Glossy (Black)']}
        scale={0.001}
        userData={{ name: 'Body_Purfling_Top_Arm_Bevel' }}
      />
      <mesh
        name="Body_Binding_Top_Venetian_Cutaway"
        geometry={nodes.Body_Binding_Top_Venetian_Cutaway.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Binding_Top_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Purfling_Top_Arm_Bevel_Venetian_Cutaway"
        geometry={nodes.Body_Purfling_Top_Arm_Bevel_Venetian_Cutaway.geometry}
        material={materials['Plastic - Glossy (Black)']}
        scale={0.001}
        userData={{ name: 'Body_Purfling_Top_Arm_Bevel_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Purfling_Top_Venetian_Cutaway"
        geometry={nodes.Body_Purfling_Top_Venetian_Cutaway.geometry}
        material={materials['Plastic - Glossy (Black)']}
        scale={0.001}
        userData={{ name: 'Body_Purfling_Top_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Purfling_Bottom_Florentine_Cutaway"
        geometry={nodes.Body_Purfling_Bottom_Florentine_Cutaway.geometry}
        material={materials['Plastic - Glossy (Black)']}
        scale={0.001}
        userData={{ name: 'Body_Purfling_Bottom_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Binding_Top"
        geometry={nodes.Body_Binding_Top.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Binding_Top' }}
      />
      <mesh
        name="Body_Binding_Bottom_Venetian_Cutaway"
        geometry={nodes.Body_Binding_Bottom_Venetian_Cutaway.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Binding_Bottom_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_Binding_Top_Arm_Bevel"
        geometry={nodes.Body_Binding_Top_Arm_Bevel.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Binding_Top_Arm_Bevel' }}
      />
      <mesh
        name="Body_String_A"
        geometry={nodes.Body_String_A.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_String_A' }}
      />
      <mesh
        name="Body_String_G"
        geometry={nodes.Body_String_G.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_String_G' }}
      />
      <mesh
        name="Body_Binding_Bottom"
        geometry={nodes.Body_Binding_Bottom.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Binding_Bottom' }}
      />
      <mesh
        name="Body_Binding_Top_Florentine_Cutaway"
        geometry={nodes.Body_Binding_Top_Florentine_Cutaway.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Binding_Top_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_Binding_Top_Arm_Bevel_Venetian_Cutaway"
        geometry={nodes.Body_Binding_Top_Arm_Bevel_Venetian_Cutaway.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Binding_Top_Arm_Bevel_Venetian_Cutaway' }}
      />
      <mesh
        name="Body_String_B"
        geometry={nodes.Body_String_B.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_String_B' }}
      />
      <mesh
        name="Body_Binding_Bottom_Florentine_Cutaway"
        geometry={nodes.Body_Binding_Bottom_Florentine_Cutaway.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Binding_Bottom_Florentine_Cutaway' }}
      />
      <mesh
        name="Body_String_LowE"
        geometry={nodes.Body_String_LowE.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_String_LowE' }}
      />
      <mesh
        name="Body_String_D"
        geometry={nodes.Body_String_D.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_String_D' }}
      />
      <mesh
        name="Body_String_HighE"
        geometry={nodes.Body_String_HighE.geometry}
        material={materials['Steel - Satin']}
        scale={0.001}
        userData={{ name: 'Body_String_HighE' }}
      />
      <mesh
        name="Body_Binding_Top_Arm_Bevel_Florentine_Cutaway"
        geometry={nodes.Body_Binding_Top_Arm_Bevel_Florentine_Cutaway.geometry}
        material={materials['ABS (White)']}
        scale={0.001}
        userData={{ name: 'Body_Binding_Top_Arm_Bevel_Florentine_Cutaway' }}
      />
    </group>
  )
}

useGLTF.preload(modelLoadPath, draco)
