/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Neck_Collection.glb --types --transform --instanceall --keepmeshes --keepmaterials --keepattributes --keepnames --draco --meta --shadows --exportdefault --output ./src/_generated/LuthNeck.tsx 
Files: ./public/Neck_Collection.glb [116.54KB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/Neck_Collection-transformed.glb [15.75KB] (86%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Surface_Neck_Profile: THREE.Mesh
    Body_Heel: THREE.Mesh
    Body_Neck: THREE.Mesh
  }
  materials: {
    ['F_9a9c2ceecbc14c2b8217545c4d2a4e58.003']: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Neck_Collection-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      SurfaceNeckProfile: nodes.Surface_Neck_Profile,
      BodyHeel: nodes.Body_Heel,
      BodyNeck: nodes.Body_Neck,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.SurfaceNeckProfile
        name="Surface_Neck_Profile"
        userData={{ name: 'Surface_Neck_Profile' }}
      />
      <instances.BodyHeel name="Body_Heel" userData={{ name: 'Body_Heel' }} />
      <instances.BodyNeck name="Body_Neck" userData={{ name: 'Body_Neck' }} />
    </group>
  )
}

useGLTF.preload('/Neck_Collection-transformed.glb')
