/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@7.1.3 ./public/Sides_Collection.glb --transform --types --keepnames --keepmeshes --draco --meta --shadows --exportdefault --instanceall --output ./src/_generated/LuthSides.tsx 
*/

import {
  useAnimations,
  useGLTF,
  Merged,
  PerspectiveCamera,
  OrthographicCamera,
} from '@react-three/drei'
import { GroupProps, MeshProps, useGraph } from '@react-three/fiber'
import * as React from 'react'
import { AnimationClip, Material, Mesh, MeshPhysicalMaterial, MeshStandardMaterial } from 'three'
import { GLTF, SkeletonUtils } from 'three-stdlib'

interface LuthSidesGLTF extends GLTF {
  materials: { FiestaRed: MeshStandardMaterial }
  nodes: {
    Body_Heel_Block: Mesh
    Body_Lining_Top: Mesh
    Body_Lining_Bottom: Mesh
    Body_Tail_Block: Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway: Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway: Mesh
    Body_Sides: Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway: Mesh
    Body_End_Graft_Wedge: Mesh
    Body_Sides_Venetian_Cutaway: Mesh
    Body_Heel_Block001: Mesh
    Body_Lining_Bottom001: Mesh
    Body_Sides_Scalloped_Cutaway: Mesh
    Body_End_Graft_Wedge001: Mesh
    Body_Sides001: Mesh
    Body_Sides_Florentine_Cutaway: Mesh
    Body_Tail_Block001: Mesh
    Body_Lining_Top001: Mesh
    Body_Sides_Arm_Bevel: Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway001: Mesh
  }
}

export interface LuthSidesProps extends GroupProps {}

const modelLoadPath = 'Sides_Collection.glb'
const draco = true

type ContextType = Record<string, React.ForwardRefExoticComponent<MeshProps>>

export const context = React.createContext<ContextType>({})

export function LuthSidesInstances({ children, ...props }: LuthSidesProps) {
  const { nodes } = useGLTF(modelLoadPath, draco) as LuthSidesGLTF
  const instances = React.useMemo(
    () => ({
      Body_Heel_Block: nodes.Body_Heel_Block,
      Body_Lining_Top: nodes.Body_Lining_Top,
      Body_Lining_Bottom: nodes.Body_Lining_Bottom,
      Body_Tail_Block: nodes.Body_Tail_Block,
      Body_Sides_Arm_Bevel_Scalloped_Cutaway: nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway,
      Body_Sides_Arm_Bevel_Florentine_Cutaway: nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway,
      Body_Sides: nodes.Body_Sides,
      Body_Sides_Arm_Bevel_Venetian_Cutaway: nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway,
      Body_End_Graft_Wedge: nodes.Body_End_Graft_Wedge,
      Body_Sides_Venetian_Cutaway: nodes.Body_Sides_Venetian_Cutaway,
      Body_Heel_Block1: nodes.Body_Heel_Block001,
      Body_Lining_Bottom1: nodes.Body_Lining_Bottom001,
      Body_Sides_Scalloped_Cutaway: nodes.Body_Sides_Scalloped_Cutaway,
      Body_End_Graft_Wedge1: nodes.Body_End_Graft_Wedge001,
      Body_Sides1: nodes.Body_Sides001,
      Body_Sides_Florentine_Cutaway: nodes.Body_Sides_Florentine_Cutaway,
      Body_Tail_Block1: nodes.Body_Tail_Block001,
      Body_Lining_Top1: nodes.Body_Lining_Top001,
      Body_Sides_Arm_Bevel: nodes.Body_Sides_Arm_Bevel,
      Body_Sides_Arm_Bevel_Scalloped_Cutaway1: nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway001,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function LuthSides(props: LuthSidesProps) {
  const instances = React.useContext(context)

  return (
    <group {...props} dispose={null}>
      <instances.Body_Heel_Block
        name="Body_Heel_Block"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Heel_Block' }}
      />
      <instances.Body_Lining_Top
        name="Body_Lining_Top"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Lining_Top' }}
      />
      <instances.Body_Lining_Bottom
        name="Body_Lining_Bottom"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Lining_Bottom' }}
      />
      <instances.Body_Tail_Block
        name="Body_Tail_Block"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Tail_Block' }}
      />
      <instances.Body_Sides_Arm_Bevel_Scalloped_Cutaway
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }}
      />
      <instances.Body_Sides_Arm_Bevel_Florentine_Cutaway
        name="Body_Sides_Arm_Bevel_Florentine_Cutaway"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }}
      />
      <instances.Body_Sides
        name="Body_Sides"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Sides' }}
      />
      <instances.Body_Sides_Arm_Bevel_Venetian_Cutaway
        name="Body_Sides_Arm_Bevel_Venetian_Cutaway"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }}
      />
      <instances.Body_End_Graft_Wedge
        name="Body_End_Graft_Wedge"
        castShadow
        receiveShadow
        userData={{ name: 'Body_End_Graft_Wedge' }}
      />
      <instances.Body_Sides_Venetian_Cutaway
        name="Body_Sides_Venetian_Cutaway"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Sides_Venetian_Cutaway' }}
      />
      <instances.Body_Heel_Block1
        name="Body_Heel_Block001"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Heel_Block.001' }}
      />
      <instances.Body_Lining_Bottom1
        name="Body_Lining_Bottom001"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Lining_Bottom.001' }}
      />
      <instances.Body_Sides_Scalloped_Cutaway
        name="Body_Sides_Scalloped_Cutaway"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Sides_Scalloped_Cutaway' }}
      />
      <instances.Body_End_Graft_Wedge1
        name="Body_End_Graft_Wedge001"
        castShadow
        receiveShadow
        userData={{ name: 'Body_End_Graft_Wedge.001' }}
      />
      <instances.Body_Sides1
        name="Body_Sides001"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Sides.001' }}
      />
      <instances.Body_Sides_Florentine_Cutaway
        name="Body_Sides_Florentine_Cutaway"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Sides_Florentine_Cutaway' }}
      />
      <instances.Body_Tail_Block1
        name="Body_Tail_Block001"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Tail_Block.001' }}
      />
      <instances.Body_Lining_Top1
        name="Body_Lining_Top001"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Lining_Top.001' }}
      />
      <instances.Body_Sides_Arm_Bevel
        name="Body_Sides_Arm_Bevel"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Sides_Arm_Bevel' }}
      />
      <instances.Body_Sides_Arm_Bevel_Scalloped_Cutaway1
        name="Body_Sides_Arm_Bevel_Scalloped_Cutaway001"
        castShadow
        receiveShadow
        userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway.001' }}
      />
    </group>
  )
}

useGLTF.preload(modelLoadPath, draco)
