/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Frets_Collection.glb --types --transform --instanceall --keepmeshes --keepmaterials --keepattributes --keepnames --draco --meta --shadows --exportdefault --output ./src/_generated/LuthFrets.tsx 
Files: ./public/Frets_Collection.glb [484.33KB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/Frets_Collection-transformed.glb [75.69KB] (84%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Body_Fret1: THREE.Mesh
    Body_Fret10: THREE.Mesh
    Body_Fret11: THREE.Mesh
    Body_Fret12: THREE.Mesh
    Body_Fret13: THREE.Mesh
    Body_Fret14: THREE.Mesh
    Body_Fret15: THREE.Mesh
    Body_Fret16: THREE.Mesh
    Body_Fret17: THREE.Mesh
    Body_Fret18: THREE.Mesh
    Body_Fret19: THREE.Mesh
    Body_Fret2: THREE.Mesh
    Body_Fret20: THREE.Mesh
    Body_Fret21: THREE.Mesh
    Body_Fret22: THREE.Mesh
    Body_Fret23: THREE.Mesh
    Body_Fret24: THREE.Mesh
    Body_Fret3: THREE.Mesh
    Body_Fret4: THREE.Mesh
    Body_Fret5: THREE.Mesh
    Body_Fret6: THREE.Mesh
    Body_Fret7: THREE.Mesh
    Body_Fret8: THREE.Mesh
    Body_Fret9: THREE.Mesh
  }
  materials: {
    F_d3bf780ac3334f6c90a3f1e6b18d32e8: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Frets_Collection-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      BodyFret: nodes.Body_Fret1,
      BodyFret1: nodes.Body_Fret10,
      BodyFret2: nodes.Body_Fret11,
      BodyFret3: nodes.Body_Fret12,
      BodyFret4: nodes.Body_Fret13,
      BodyFret5: nodes.Body_Fret14,
      BodyFret6: nodes.Body_Fret15,
      BodyFret7: nodes.Body_Fret16,
      BodyFret8: nodes.Body_Fret17,
      BodyFret9: nodes.Body_Fret18,
      BodyFret10: nodes.Body_Fret19,
      BodyFret11: nodes.Body_Fret2,
      BodyFret12: nodes.Body_Fret20,
      BodyFret13: nodes.Body_Fret21,
      BodyFret14: nodes.Body_Fret22,
      BodyFret15: nodes.Body_Fret23,
      BodyFret16: nodes.Body_Fret24,
      BodyFret17: nodes.Body_Fret3,
      BodyFret18: nodes.Body_Fret4,
      BodyFret19: nodes.Body_Fret5,
      BodyFret20: nodes.Body_Fret6,
      BodyFret21: nodes.Body_Fret7,
      BodyFret22: nodes.Body_Fret8,
      BodyFret23: nodes.Body_Fret9,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.BodyFret name="Body_Fret1" userData={{ name: 'Body_Fret1' }} />
      <instances.BodyFret1 name="Body_Fret10" userData={{ name: 'Body_Fret10' }} />
      <instances.BodyFret2 name="Body_Fret11" userData={{ name: 'Body_Fret11' }} />
      <instances.BodyFret3 name="Body_Fret12" userData={{ name: 'Body_Fret12' }} />
      <instances.BodyFret4 name="Body_Fret13" userData={{ name: 'Body_Fret13' }} />
      <instances.BodyFret5 name="Body_Fret14" userData={{ name: 'Body_Fret14' }} />
      <instances.BodyFret6 name="Body_Fret15" userData={{ name: 'Body_Fret15' }} />
      <instances.BodyFret7 name="Body_Fret16" userData={{ name: 'Body_Fret16' }} />
      <instances.BodyFret8 name="Body_Fret17" userData={{ name: 'Body_Fret17' }} />
      <instances.BodyFret9 name="Body_Fret18" userData={{ name: 'Body_Fret18' }} />
      <instances.BodyFret10 name="Body_Fret19" userData={{ name: 'Body_Fret19' }} />
      <instances.BodyFret11 name="Body_Fret2" userData={{ name: 'Body_Fret2' }} />
      <instances.BodyFret12 name="Body_Fret20" userData={{ name: 'Body_Fret20' }} />
      <instances.BodyFret13 name="Body_Fret21" userData={{ name: 'Body_Fret21' }} />
      <instances.BodyFret14 name="Body_Fret22" userData={{ name: 'Body_Fret22' }} />
      <instances.BodyFret15 name="Body_Fret23" userData={{ name: 'Body_Fret23' }} />
      <instances.BodyFret16 name="Body_Fret24" userData={{ name: 'Body_Fret24' }} />
      <instances.BodyFret17 name="Body_Fret3" userData={{ name: 'Body_Fret3' }} />
      <instances.BodyFret18 name="Body_Fret4" userData={{ name: 'Body_Fret4' }} />
      <instances.BodyFret19 name="Body_Fret5" userData={{ name: 'Body_Fret5' }} />
      <instances.BodyFret20 name="Body_Fret6" userData={{ name: 'Body_Fret6' }} />
      <instances.BodyFret21 name="Body_Fret7" userData={{ name: 'Body_Fret7' }} />
      <instances.BodyFret22 name="Body_Fret8" userData={{ name: 'Body_Fret8' }} />
      <instances.BodyFret23 name="Body_Fret9" userData={{ name: 'Body_Fret9' }} />
    </group>
  )
}

useGLTF.preload('/Frets_Collection-transformed.glb')
