/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/variants/acou_drea_25-4in_6str_collection_binding_variants.glb --types --transform --instanceall --keepmeshes --keepmaterials --keepattributes --keepnames --draco --meta --shadows --exportdefault --output ./src/_generated/LuthAcousticDreadnaught_25-4in_6str_Binding.tsx 
Files: ./public/variants/acou_drea_25-4in_6str_collection_binding_variants.glb [1.08MB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/acou_drea_25-4in_6str_collection_binding_variants-transformed.glb [111.2KB] (90%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Body_Purfling_Top001: THREE.Mesh
    Body_Purfling_Bottom001: THREE.Mesh
    Binding_Bottom001: THREE.Mesh
    Bind_Top_CW_Vene001: THREE.Mesh
    Binding_Bottom_CW_Vene001: THREE.Mesh
    Binding_Top_CW_Flor001: THREE.Mesh
    Binding_Bottom_CW_Flor001: THREE.Mesh
    Binding_Top_CW_None_AB_Std001: THREE.Mesh
    Binding_Top_CW_Vene_AB_Std001: THREE.Mesh
    Binding_Top_CW_Flor_AB_Std001: THREE.Mesh
    Body_Purfling_Top_Venetian_Cutaway: THREE.Mesh
    Body_Purfling_Bottom_Venetian_Cutaway: THREE.Mesh
    Body_Purfling_Top_Florentine_Cutaway: THREE.Mesh
    Body_Purfling_Bottom_Florentine_Cutaway: THREE.Mesh
    Body_Purfling_Top_Arm_Bevel: THREE.Mesh
    Body_Purfling_Top_Arm_Bevel_Florentine_Cutaway: THREE.Mesh
    Body_Purfling_Top_Arm_Bevel_Venetian_Cutaway: THREE.Mesh
    Binding_Top001: THREE.Mesh
  }
  materials: {
    F_15e167ceab1241c5822a7fc86c308293: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF(
    '/acou_drea_25-4in_6str_collection_binding_variants-transformed.glb',
  ) as GLTFResult
  const instances = React.useMemo(
    () => ({
      // BodyPurflingTop: nodes.Body_Purfling_Top001,
      // BodyPurflingBottom: nodes.Body_Purfling_Bottom001,
      BindingBottom: nodes.Binding_Bottom001,
      BindTopCWVene: nodes.Bind_Top_CW_Vene001,
      BindingBottomCWVene: nodes.Binding_Bottom_CW_Vene001,
      BindingTopCWFlor: nodes.Binding_Top_CW_Flor001,
      BindingBottomCWFlor: nodes.Binding_Bottom_CW_Flor001,
      BindingTopCWNoneABStd: nodes.Binding_Top_CW_None_AB_Std001,
      BindingTopCWVeneABStd: nodes.Binding_Top_CW_Vene_AB_Std001,
      BindingTopCWFlorABStd: nodes.Binding_Top_CW_Flor_AB_Std001,
      // BodyPurflingTopVenetianCutaway: nodes.Body_Purfling_Top_Venetian_Cutaway,
      // BodyPurflingBottomVenetianCutaway: nodes.Body_Purfling_Bottom_Venetian_Cutaway,
      // BodyPurflingTopFlorentineCutaway: nodes.Body_Purfling_Top_Florentine_Cutaway,
      // BodyPurflingBottomFlorentineCutaway: nodes.Body_Purfling_Bottom_Florentine_Cutaway,
      // BodyPurflingTopArmBevel: nodes.Body_Purfling_Top_Arm_Bevel,
      // BodyPurflingTopArmBevelFlorentineCutaway: nodes.Body_Purfling_Top_Arm_Bevel_Florentine_Cutaway,
      // BodyPurflingTopArmBevelVenetianCutaway: nodes.Body_Purfling_Top_Arm_Bevel_Venetian_Cutaway,
      BindingTop: nodes.Binding_Top001,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      {/* <instances.BodyPurflingTop name="Body_Purfling_Top001" rotation={[Math.PI / 2, 0, 0]} scale={0.01} userData={{ name: 'Body_Purfling_Top.001' }} />
      <instances.BodyPurflingBottom name="Body_Purfling_Bottom001" rotation={[Math.PI / 2, 0, 0]} scale={0.01} userData={{ name: 'Body_Purfling_Bottom.001' }} /> */}
      <instances.BindingBottom
        name="Binding_Bottom001"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
        userData={{ name: 'Binding_Bottom.001' }}
      />
      <instances.BindTopCWVene
        name="Bind_Top_CW_Vene001"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
        userData={{ name: 'Bind_Top_CW_Vene.001' }}
      />
      <instances.BindingBottomCWVene
        name="Binding_Bottom_CW_Vene001"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
        userData={{ name: 'Binding_Bottom_CW_Vene.001' }}
      />
      <instances.BindingTopCWFlor
        name="Binding_Top_CW_Flor001"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
        userData={{ name: 'Binding_Top_CW_Flor.001' }}
      />
      <instances.BindingBottomCWFlor
        name="Binding_Bottom_CW_Flor001"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
        userData={{ name: 'Binding_Bottom_CW_Flor.001' }}
      />
      <instances.BindingTopCWNoneABStd
        name="Binding_Top_CW_None_AB_Std001"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
        userData={{ name: 'Binding_Top_CW_None_AB_Std.001' }}
      />
      <instances.BindingTopCWVeneABStd
        name="Binding_Top_CW_Vene_AB_Std001"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
        userData={{ name: 'Binding_Top_CW_Vene_AB_Std.001' }}
      />
      <instances.BindingTopCWFlorABStd
        name="Binding_Top_CW_Flor_AB_Std001"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
        userData={{ name: 'Binding_Top_CW_Flor_AB_Std.001' }}
      />
      {/* <instances.BodyPurflingTopVenetianCutaway name="Body_Purfling_Top_Venetian_Cutaway" rotation={[Math.PI / 2, 0, 0]} scale={0.01} userData={{ name: 'Body_Purfling_Top_Venetian_Cutaway' }} />
      <instances.BodyPurflingBottomVenetianCutaway name="Body_Purfling_Bottom_Venetian_Cutaway" rotation={[Math.PI / 2, 0, 0]} scale={0.01} userData={{ name: 'Body_Purfling_Bottom_Venetian_Cutaway' }} />
      <instances.BodyPurflingTopFlorentineCutaway name="Body_Purfling_Top_Florentine_Cutaway" rotation={[Math.PI / 2, 0, 0]} scale={0.01} userData={{ name: 'Body_Purfling_Top_Florentine_Cutaway' }} />
      <instances.BodyPurflingBottomFlorentineCutaway name="Body_Purfling_Bottom_Florentine_Cutaway" rotation={[Math.PI / 2, 0, 0]} scale={0.01} userData={{ name: 'Body_Purfling_Bottom_Florentine_Cutaway' }} />
      <instances.BodyPurflingTopArmBevel name="Body_Purfling_Top_Arm_Bevel" rotation={[Math.PI / 2, 0, 0]} scale={0.01} userData={{ name: 'Body_Purfling_Top_Arm_Bevel' }} />
      <instances.BodyPurflingTopArmBevelFlorentineCutaway name="Body_Purfling_Top_Arm_Bevel_Florentine_Cutaway" rotation={[Math.PI / 2, 0, 0]} scale={0.01} userData={{ name: 'Body_Purfling_Top_Arm_Bevel_Florentine_Cutaway' }} />
      <instances.BodyPurflingTopArmBevelVenetianCutaway name="Body_Purfling_Top_Arm_Bevel_Venetian_Cutaway" rotation={[Math.PI / 2, 0, 0]} scale={0.01} userData={{ name: 'Body_Purfling_Top_Arm_Bevel_Venetian_Cutaway' }} /> */}
      <instances.BindingTop
        name="Binding_Top001"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
        userData={{ name: 'Binding_Top.001' }}
      />
    </group>
  )
}

useGLTF.preload('/acou_drea_25-4in_6str_collection_binding_variants-transformed.glb')
