/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Nut_Collection.glb --types --transform --instanceall --keepmeshes --keepmaterials --keepattributes --keepnames --draco --meta --shadows --exportdefault --output ./src/_generated/LuthNut.tsx 
Files: ./public/Nut_Collection.glb [28.53KB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/Nut_Collection-transformed.glb [4.37KB] (85%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Body_Nut001: THREE.Mesh
  }
  materials: {
    F_a523920d80694645b4c65a8f651f3908: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Nut_Collection-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      BodyNut: nodes.Body_Nut001,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.BodyNut name="Body_Nut001" userData={{ name: 'Body_Nut.001' }} />
    </group>
  )
}

useGLTF.preload('/Nut_Collection-transformed.glb')
