/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/luth-acoustic-parlor.glb --types --keepnames --draco --meta --transform --keepmaterials --exportdefault --debug --instanceall --output ./src/_generated/LuthAcousticParlor.tsx 
Files: ./public/luth-acoustic-parlor.glb [21.73MB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/luth-acoustic-parlor-transformed.glb [1.54MB] (93%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged, PerspectiveCamera } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body_Heel_Block: THREE.Mesh
    Body4: THREE.Mesh
    Body_Sides: THREE.Mesh
    Body_Sides_Venetian_Cutaway: THREE.Mesh
    Body_Sides_Florentine_Cutaway: THREE.Mesh
    Body_Sides_Scalloped_Cutaway: THREE.Mesh
    Body_Sides_Arm_Bevel: THREE.Mesh
    Body_Sides_Arm_Bevel_Florentine_Cutaway: THREE.Mesh
    Body_Sides_Arm_Bevel_Venetian_Cutaway: THREE.Mesh
    Body_Sides_Arm_Bevel_Scalloped_Cutaway: THREE.Mesh
    Body_Rosette: THREE.Mesh
    Body_Bridge_Plate: THREE.Mesh
    Body_Bridge: THREE.Mesh
    Body_Back_Center_Strip: THREE.Mesh
    Body_Back: THREE.Mesh
    Body_Back_Venetian_Cutaway: THREE.Mesh
    Body_Back_Florentine_Cutaway: THREE.Mesh
    Body_Back_2Piece_Left: THREE.Mesh
    Body_Back_2Piece_Right: THREE.Mesh
    Body_Back_2Piece_Venetian_Cutaway_Right: THREE.Mesh
    Body_Back_2Piece_Florentine_Cutaway_Right: THREE.Mesh
    Body_Back_3Piece_Middle: THREE.Mesh
    Body_Back_3Piece_Venetian_Cutaway_Middle: THREE.Mesh
    Body_Back_3Piece_Florentine_Cutaway_Middle: THREE.Mesh
    Body_Back_3Piece_Left: THREE.Mesh
    Body_Back_3Piece_Right: THREE.Mesh
    Body_Back_3Piece_Venetian_Cutaway_Right: THREE.Mesh
    Body_Back_3Piece_Florentine_Cutaway_Right: THREE.Mesh
    Body_Back_3Piece_Florentine_Cutaway_Left: THREE.Mesh
    ['Body_Fretboard_(1)']: THREE.Mesh
    ['Body_Fretboard_(1)_(1)']: THREE.Mesh
    ['Body_Fretboard_(1)_(2)']: THREE.Mesh
    ['Body_Fretboard_(1)_(3)']: THREE.Mesh
    Body_Fretboard: THREE.Mesh
    Body_Pickguard: THREE.Mesh
    Body_Bridge_Pin_Inlay: THREE.Mesh
    Body_Bridge_Pin: THREE.Mesh
    Peg_Head: THREE.Mesh
    Peg_Head_Tuner_Right: THREE.Mesh
  }
  materials: {
    ['Oak - Glossy']: THREE.MeshStandardMaterial
    ['3D Ash - Unfinished']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Walnut - Semigloss']: THREE.MeshStandardMaterial
    ['Plastic - Glossy (Black)']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/luth-acoustic-parlor-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      BodyHeelBlock: nodes.Body_Heel_Block,
      Body: nodes.Body4,
      BodySides: nodes.Body_Sides,
      BodySidesVenetianCutaway: nodes.Body_Sides_Venetian_Cutaway,
      BodySidesFlorentineCutaway: nodes.Body_Sides_Florentine_Cutaway,
      BodySidesScallopedCutaway: nodes.Body_Sides_Scalloped_Cutaway,
      BodySidesArmBevel: nodes.Body_Sides_Arm_Bevel,
      BodySidesArmBevelFlorentineCutaway: nodes.Body_Sides_Arm_Bevel_Florentine_Cutaway,
      BodySidesArmBevelVenetianCutaway: nodes.Body_Sides_Arm_Bevel_Venetian_Cutaway,
      BodySidesArmBevelScallopedCutaway: nodes.Body_Sides_Arm_Bevel_Scalloped_Cutaway,
      BodyRosette: nodes.Body_Rosette,
      BodyBridgePlate: nodes.Body_Bridge_Plate,
      BodyBridge: nodes.Body_Bridge,
      BodyBackCenterStrip: nodes.Body_Back_Center_Strip,
      BodyBack: nodes.Body_Back,
      BodyBackVenetianCutaway: nodes.Body_Back_Venetian_Cutaway,
      BodyBackFlorentineCutaway: nodes.Body_Back_Florentine_Cutaway,
      BodyBackPieceLeft: nodes.Body_Back_2Piece_Left,
      BodyBackPieceRight: nodes.Body_Back_2Piece_Right,
      BodyBackPieceVenetianCutawayRight: nodes.Body_Back_2Piece_Venetian_Cutaway_Right,
      BodyBackPieceFlorentineCutawayRight: nodes.Body_Back_2Piece_Florentine_Cutaway_Right,
      BodyBackPieceMiddle: nodes.Body_Back_3Piece_Middle,
      BodyBackPieceVenetianCutawayMiddle: nodes.Body_Back_3Piece_Venetian_Cutaway_Middle,
      BodyBackPieceFlorentineCutawayMiddle: nodes.Body_Back_3Piece_Florentine_Cutaway_Middle,
      BodyBackPieceLeft1: nodes.Body_Back_3Piece_Left,
      BodyBackPieceRight1: nodes.Body_Back_3Piece_Right,
      BodyBackPieceVenetianCutawayRight1: nodes.Body_Back_3Piece_Venetian_Cutaway_Right,
      BodyBackPieceFlorentineCutawayRight1: nodes.Body_Back_3Piece_Florentine_Cutaway_Right,
      BodyBackPieceFlorentineCutawayLeft: nodes.Body_Back_3Piece_Florentine_Cutaway_Left,
      BodyFretboard: nodes['Body_Fretboard_(1)'],
      BodyFretboard1: nodes['Body_Fretboard_(1)_(1)'],
      BodyFretboard2: nodes['Body_Fretboard_(1)_(2)'],
      BodyFretboard3: nodes['Body_Fretboard_(1)_(3)'],
      BodyFretboard4: nodes.Body_Fretboard,
      BodyPickguard: nodes.Body_Pickguard,
      BodyBridgePinInlay: nodes.Body_Bridge_Pin_Inlay,
      BodyBridgePin: nodes.Body_Bridge_Pin,
      PegHead: nodes.Peg_Head,
      PegHeadTunerRight: nodes.Peg_Head_Tuner_Right,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera name="active" makeDefault={false} far={1794.933} near={1247.788} fov={39.598} position={[-0.945, 0.568, 1.078]} rotation={[-0.336, -0.67, -0.214]} scale={0.001} userData={{ name: 'active' }} />
      <instances.BodyHeelBlock name="Body_Heel_Block" scale={0.001} userData={{ name: 'Body_Heel_Block' }} />
      <instances.Body name="Body4" scale={0.001} userData={{ name: 'Body4' }} />
      <instances.BodySides name="Body_Sides" scale={0.001} userData={{ name: 'Body_Sides' }} />
      <instances.BodySidesVenetianCutaway name="Body_Sides_Venetian_Cutaway" scale={0.001} userData={{ name: 'Body_Sides_Venetian_Cutaway' }} />
      <instances.BodySidesFlorentineCutaway name="Body_Sides_Florentine_Cutaway" scale={0.001} userData={{ name: 'Body_Sides_Florentine_Cutaway' }} />
      <instances.BodySidesScallopedCutaway name="Body_Sides_Scalloped_Cutaway" scale={0.001} userData={{ name: 'Body_Sides_Scalloped_Cutaway' }} />
      <instances.BodySidesArmBevel name="Body_Sides_Arm_Bevel" scale={0.001} userData={{ name: 'Body_Sides_Arm_Bevel' }} />
      <instances.BodySidesArmBevelFlorentineCutaway name="Body_Sides_Arm_Bevel_Florentine_Cutaway" scale={0.001} userData={{ name: 'Body_Sides_Arm_Bevel_Florentine_Cutaway' }} />
      <instances.BodySidesArmBevelVenetianCutaway name="Body_Sides_Arm_Bevel_Venetian_Cutaway" scale={0.001} userData={{ name: 'Body_Sides_Arm_Bevel_Venetian_Cutaway' }} />
      <instances.BodySidesArmBevelScallopedCutaway name="Body_Sides_Arm_Bevel_Scalloped_Cutaway" scale={0.001} userData={{ name: 'Body_Sides_Arm_Bevel_Scalloped_Cutaway' }} />
      <instances.BodyRosette name="Body_Rosette" scale={0.001} userData={{ name: 'Body_Rosette' }} />
      <instances.BodyBridgePlate name="Body_Bridge_Plate" scale={0.001} userData={{ name: 'Body_Bridge_Plate' }} />
      <instances.BodyBridge name="Body_Bridge" scale={0.001} userData={{ name: 'Body_Bridge' }} />
      <instances.BodyBackCenterStrip name="Body_Back_Center_Strip" scale={0.001} userData={{ name: 'Body_Back_Center_Strip' }} />
      <instances.BodyBack name="Body_Back" scale={0.001} userData={{ name: 'Body_Back' }} />
      <instances.BodyBackVenetianCutaway name="Body_Back_Venetian_Cutaway" scale={0.001} userData={{ name: 'Body_Back_Venetian_Cutaway' }} />
      <instances.BodyBackFlorentineCutaway name="Body_Back_Florentine_Cutaway" scale={0.001} userData={{ name: 'Body_Back_Florentine_Cutaway' }} />
      <instances.BodyBackPieceLeft name="Body_Back_2Piece_Left" scale={0.001} userData={{ name: 'Body_Back_2Piece_Left' }} />
      <instances.BodyBackPieceRight name="Body_Back_2Piece_Right" scale={0.001} userData={{ name: 'Body_Back_2Piece_Right' }} />
      <instances.BodyBackPieceVenetianCutawayRight name="Body_Back_2Piece_Venetian_Cutaway_Right" scale={0.001} userData={{ name: 'Body_Back_2Piece_Venetian_Cutaway_Right' }} />
      <instances.BodyBackPieceFlorentineCutawayRight name="Body_Back_2Piece_Florentine_Cutaway_Right" scale={0.001} userData={{ name: 'Body_Back_2Piece_Florentine_Cutaway_Right' }} />
      <instances.BodyBackPieceMiddle name="Body_Back_3Piece_Middle" scale={0.001} userData={{ name: 'Body_Back_3Piece_Middle' }} />
      <instances.BodyBackPieceVenetianCutawayMiddle name="Body_Back_3Piece_Venetian_Cutaway_Middle" scale={0.001} userData={{ name: 'Body_Back_3Piece_Venetian_Cutaway_Middle' }} />
      <instances.BodyBackPieceFlorentineCutawayMiddle name="Body_Back_3Piece_Florentine_Cutaway_Middle" scale={0.001} userData={{ name: 'Body_Back_3Piece_Florentine_Cutaway_Middle' }} />
      <instances.BodyBackPieceLeft1 name="Body_Back_3Piece_Left" scale={0.001} userData={{ name: 'Body_Back_3Piece_Left' }} />
      <instances.BodyBackPieceRight1 name="Body_Back_3Piece_Right" scale={0.001} userData={{ name: 'Body_Back_3Piece_Right' }} />
      <instances.BodyBackPieceVenetianCutawayRight1 name="Body_Back_3Piece_Venetian_Cutaway_Right" scale={0.001} userData={{ name: 'Body_Back_3Piece_Venetian_Cutaway_Right' }} />
      <instances.BodyBackPieceFlorentineCutawayRight1 name="Body_Back_3Piece_Florentine_Cutaway_Right" scale={0.001} userData={{ name: 'Body_Back_3Piece_Florentine_Cutaway_Right' }} />
      <instances.BodyBackPieceFlorentineCutawayLeft name="Body_Back_3Piece_Florentine_Cutaway_Left" scale={0.001} userData={{ name: 'Body_Back_3Piece_Florentine_Cutaway_Left' }} />
      <instances.BodyFretboard name="Body_Fretboard_(1)" scale={0.001} userData={{ name: 'Body_Fretboard (1)' }} />
      <instances.BodyFretboard1 name="Body_Fretboard_(1)_(1)" scale={0.001} userData={{ name: 'Body_Fretboard (1) (1)' }} />
      <instances.BodyFretboard2 name="Body_Fretboard_(1)_(2)" scale={0.001} userData={{ name: 'Body_Fretboard (1) (2)' }} />
      <instances.BodyFretboard3 name="Body_Fretboard_(1)_(3)" scale={0.001} userData={{ name: 'Body_Fretboard (1) (3)' }} />
      <instances.BodyFretboard4 name="Body_Fretboard" scale={0.001} userData={{ name: 'Body_Fretboard' }} />
      <instances.BodyPickguard name="Body_Pickguard" scale={0.001} userData={{ name: 'Body_Pickguard' }} />
      <instances.BodyBridgePinInlay name="Body_Bridge_Pin_Inlay" />
      <instances.BodyBridgePin name="Body_Bridge_Pin" />
      <instances.PegHead name="Peg_Head" />
      <instances.PegHeadTunerRight name="Peg_Head_Tuner_Right" />
    </group>
  )
}

useGLTF.preload('/luth-acoustic-parlor-transformed.glb')
