/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Binding_Collection.glb --types --transform --instanceall --keepmeshes --keepmaterials --keepattributes --keepnames --draco --meta --shadows --exportdefault --output ./src/_generated/LuthBinding.tsx 
Files: ./public/Binding_Collection.glb [1.31MB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/Binding_Collection-transformed.glb [133.59KB] (90%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Purfling_Top002: THREE.Mesh
    Purfling_Bottom002: THREE.Mesh
    Binding_Bottom: THREE.Mesh
    Binding_Top_CW_Vene: THREE.Mesh
    Binding_Bottom_CW_Vene: THREE.Mesh
    Binding_Top_CW_Flor: THREE.Mesh
    Binding_Bottom_CW_Flor: THREE.Mesh
    Binding_Top_CW_None_AB_Std: THREE.Mesh
    Binding_Top_CW_Vene_AB_Std: THREE.Mesh
    Binding_Top_CW_Flor_AB_Std: THREE.Mesh
    Purfling_Top_CW_Vene002: THREE.Mesh
    Purfling_Bottom_CW_Vene002: THREE.Mesh
    Purfling_Top_CW_Flor002: THREE.Mesh
    Purfling_Bottom_CW_Flor002: THREE.Mesh
    Purfling_Top_CW_None_AB_Std002: THREE.Mesh
    Purfling_Top_CW_Flor_AB_Std002: THREE.Mesh
    Body_Purfling_Top_CW_Vene_AB_Std002: THREE.Mesh
    Binding_Top: THREE.Mesh
    Purfling_Top003: THREE.Mesh
    Purfling_Bottom003: THREE.Mesh
    Binding_Top001: THREE.Mesh
    Binding_Bottom001: THREE.Mesh
  }
  materials: {
    F_9f372627b7554df69bf32fec63089ee6: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Binding_Collection-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      PurflingTop: nodes.Purfling_Top002,
      PurflingBottom: nodes.Purfling_Bottom002,
      BindingBottom: nodes.Binding_Bottom,
      BindingTopCWVene: nodes.Binding_Top_CW_Vene,
      BindingBottomCWVene: nodes.Binding_Bottom_CW_Vene,
      BindingTopCWFlor: nodes.Binding_Top_CW_Flor,
      BindingBottomCWFlor: nodes.Binding_Bottom_CW_Flor,
      BindingTopCWNoneABStd: nodes.Binding_Top_CW_None_AB_Std,
      BindingTopCWVeneABStd: nodes.Binding_Top_CW_Vene_AB_Std,
      BindingTopCWFlorABStd: nodes.Binding_Top_CW_Flor_AB_Std,
      PurflingTopCWVene: nodes.Purfling_Top_CW_Vene002,
      PurflingBottomCWVene: nodes.Purfling_Bottom_CW_Vene002,
      PurflingTopCWFlor: nodes.Purfling_Top_CW_Flor002,
      PurflingBottomCWFlor: nodes.Purfling_Bottom_CW_Flor002,
      PurflingTopCWNoneABStd: nodes.Purfling_Top_CW_None_AB_Std002,
      PurflingTopCWFlorABStd: nodes.Purfling_Top_CW_Flor_AB_Std002,
      BodyPurflingTopCWVeneABStd: nodes.Body_Purfling_Top_CW_Vene_AB_Std002,
      BindingTop: nodes.Binding_Top,
      PurflingTop1: nodes.Purfling_Top003,
      PurflingBottom1: nodes.Purfling_Bottom003,
      BindingTop1: nodes.Binding_Top001,
      BindingBottom1: nodes.Binding_Bottom001,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.PurflingTop name="Purfling_Top002" userData={{ name: 'Purfling_Top.002' }} />
      <instances.PurflingBottom name="Purfling_Bottom002" userData={{ name: 'Purfling_Bottom.002' }} />
      <instances.BindingBottom name="Binding_Bottom" userData={{ name: 'Binding_Bottom' }} />
      <instances.BindingTopCWVene name="Binding_Top_CW_Vene" userData={{ name: 'Binding_Top_CW_Vene' }} />
      <instances.BindingBottomCWVene name="Binding_Bottom_CW_Vene" userData={{ name: 'Binding_Bottom_CW_Vene' }} />
      <instances.BindingTopCWFlor name="Binding_Top_CW_Flor" userData={{ name: 'Binding_Top_CW_Flor' }} />
      <instances.BindingBottomCWFlor name="Binding_Bottom_CW_Flor" userData={{ name: 'Binding_Bottom_CW_Flor' }} />
      <instances.BindingTopCWNoneABStd name="Binding_Top_CW_None_AB_Std" userData={{ name: 'Binding_Top_CW_None_AB_Std' }} />
      <instances.BindingTopCWVeneABStd name="Binding_Top_CW_Vene_AB_Std" userData={{ name: 'Binding_Top_CW_Vene_AB_Std' }} />
      <instances.BindingTopCWFlorABStd name="Binding_Top_CW_Flor_AB_Std" userData={{ name: 'Binding_Top_CW_Flor_AB_Std' }} />
      <instances.PurflingTopCWVene name="Purfling_Top_CW_Vene002" userData={{ name: 'Purfling_Top_CW_Vene.002' }} />
      <instances.PurflingBottomCWVene name="Purfling_Bottom_CW_Vene002" userData={{ name: 'Purfling_Bottom_CW_Vene.002' }} />
      <instances.PurflingTopCWFlor name="Purfling_Top_CW_Flor002" userData={{ name: 'Purfling_Top_CW_Flor.002' }} />
      <instances.PurflingBottomCWFlor name="Purfling_Bottom_CW_Flor002" userData={{ name: 'Purfling_Bottom_CW_Flor.002' }} />
      <instances.PurflingTopCWNoneABStd name="Purfling_Top_CW_None_AB_Std002" userData={{ name: 'Purfling_Top_CW_None_AB_Std.002' }} />
      <instances.PurflingTopCWFlorABStd name="Purfling_Top_CW_Flor_AB_Std002" userData={{ name: 'Purfling_Top_CW_Flor_AB_Std.002' }} />
      <instances.BodyPurflingTopCWVeneABStd name="Body_Purfling_Top_CW_Vene_AB_Std002" userData={{ name: 'Body_Purfling_Top_CW_Vene_AB_Std.002' }} />
      <instances.BindingTop name="Binding_Top" userData={{ name: 'Binding_Top' }} />
      <instances.PurflingTop1 name="Purfling_Top003" userData={{ name: 'Purfling_Top.003' }} />
      <instances.PurflingBottom1 name="Purfling_Bottom003" userData={{ name: 'Purfling_Bottom.003' }} />
      <instances.BindingTop1 name="Binding_Top001" userData={{ name: 'Binding_Top.001' }} />
      <instances.BindingBottom1 name="Binding_Bottom001" userData={{ name: 'Binding_Bottom.001' }} />
    </group>
  )
}

useGLTF.preload('/Binding_Collection-transformed.glb')
