/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Sides_Collection.glb --types --transform --instanceall --keepmeshes --keepmaterials --keepattributes --keepnames --draco --meta --shadows --exportdefault --output ./src/_generated/LuthSides.tsx 
Files: ./public/Sides_Collection.glb [5.71MB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/Sides_Collection-transformed.glb [521.87KB] (91%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Sides__Parl_Standard_Fret12__CWNone: THREE.Mesh
    Sides__Parl_Standard_Fret12__CWVen: THREE.Mesh
    Sides__Parl_Standard_Fret12__CWFlo: THREE.Mesh
    Sides__Parl_Standard_Fret12__CWScal: THREE.Mesh
    Sides__Parl_Standard_Fret12__CWNone_ABStd: THREE.Mesh
    Sides__Parl_Standard_Fret12__CWFlo_ABStd: THREE.Mesh
    Sides__Parl_Standard_Fret12__CWVen_ABStd: THREE.Mesh
    Sides__Parl_Standard_Fret12__CW_Scal_AB_Std: THREE.Mesh
    Sides__Dread_Thinline_Fret14__CWFlo: THREE.Mesh
    Sides__Dread_Thinline_Fret14__CWFlo_ABNone_SPOval__1_: THREE.Mesh
    Sides__Dread_Thinline_Fret14__CWFlo_ABStd: THREE.Mesh
    Sides__Dread_Thinline_Fret14__CWNone: THREE.Mesh
    Sides__Dread_Thinline_Fret14__CWNone_ABNone_SPOval: THREE.Mesh
    Sides__Dread_Thinline_Fret14__CWNone_ABStd: THREE.Mesh
    Sides__Dread_Thinline_Fret14__CWSca: THREE.Mesh
    Sides__Dread_Thinline_Fret14__CWSca_ABNone_SPOval: THREE.Mesh
    Sides__Dread_Thinline_Fret14__CWSca_ABStd: THREE.Mesh
    Sides__Dread_Thinline_Fret14__CWVen: THREE.Mesh
    Sides__Dread_Thinline_Fret14__CWVen_ABNone_SPOval: THREE.Mesh
    Sides__Dread_Thinline_Fret14__CWVen_ABStd: THREE.Mesh
    Sides__Parl_Standard_Fret14__CWFlo_ABNone_SPOval__1_: THREE.Mesh
    Sides__Parl_Standard_Fret14__CWNone: THREE.Mesh
    Sides__Parl_Standard_Fret14__CWNone_ABNone_SPOval: THREE.Mesh
    Sides__Parl_Standard_Fret14__CWSca_ABNone_SPOval: THREE.Mesh
    Sides__Parl_Standard_Fret14__CWSca_ABStd: THREE.Mesh
    Sides__Parl_Standard_Fret14__CWVen_ABNone_SPOval: THREE.Mesh
    Sides__Dread_Thinline_Fret12__CWNone: THREE.Mesh
    Sides__Dread_Thinline_Fret12__CWVen: THREE.Mesh
    Sides__Dread_Thinline_Fret12__CWFlo: THREE.Mesh
    Sides__Dread_Thinline_Fret12__CWScal: THREE.Mesh
    Sides__Dread_Thinline_Fret12__CWNone_ABStd: THREE.Mesh
    Sides__Dread_Thinline_Fret12__CWFlo_ABStd: THREE.Mesh
    Sides__Dread_Thinline_Fret12__CWVen_ABStd: THREE.Mesh
    Sides__Dread_Thinline_Fret12__CWSca_ABStd: THREE.Mesh
    Sides__Parl_Thinline_Fret14__CWFlo_ABNone_SPOval__1_: THREE.Mesh
    Sides__Parl_Thinline_Fret14__CWNone: THREE.Mesh
    Sides__Parl_Thinline_Fret14__CWNone_ABNone_SPOval: THREE.Mesh
    Sides__Parl_Thinline_Fret14__CWSca_ABNone_SPOval: THREE.Mesh
    Sides__Parl_Thinline_Fret14__CWSca_ABStd: THREE.Mesh
    Sides__Parl_Thinline_Fret14__CWVen_ABNone_SPOval: THREE.Mesh
    Sides__Dread_Standard_Fret12__CWNone: THREE.Mesh
    Sides__Dread_Standard_Fret12__CWVen: THREE.Mesh
    Sides__Dread_Standard_Fret12__CWFlo: THREE.Mesh
    Sides__Dread_Standard_Fret12__CWScal: THREE.Mesh
    Sides__Dread_Standard_Fret12__CWNone_ABStd: THREE.Mesh
    Sides__Dread_Standard_Fret12__CWFlo_ABStd: THREE.Mesh
    Sides__Dread_Standard_Fret12__CWVen_ABStd: THREE.Mesh
    Sides__Dread_Standard_Fret12__CW_Scal_AB_Std: THREE.Mesh
    Sides__Parl_Thinline_Fret12__CWNone: THREE.Mesh
    Sides__Parl_Thinline_Fret12__CWVen: THREE.Mesh
    Sides__Parl_Thinline_Fret12__CWFlo: THREE.Mesh
    Sides__Parl_Thinline_Fret12__CWScal: THREE.Mesh
    Sides__Parl_Thinline_Fret12__CWNone_ABStd: THREE.Mesh
    Sides__Parl_Thinline_Fret12__CWFlo_ABStd: THREE.Mesh
    Sides__Parl_Thinline_Fret12__CWVen_ABStd: THREE.Mesh
    Sides__Parl_Thinline_Fret12__CW_Scal_AB_Std: THREE.Mesh
    Sides__Dread_Standard_Fret14__CWFlo: THREE.Mesh
    Sides__Dread_Standard_Fret14__CWFlo_ABNone_SPOval__1_: THREE.Mesh
    Sides__Dread_Standard_Fret14__CWFlo_ABStd: THREE.Mesh
    Sides__Dread_Standard_Fret14__CWNone: THREE.Mesh
    Sides__Dread_Standard_Fret14__CWNone_ABNone_SPOval: THREE.Mesh
    Sides__Dread_Standard_Fret14__CWNone_ABStd: THREE.Mesh
    Sides__Dread_Standard_Fret14__CWSca: THREE.Mesh
    Sides__Dread_Standard_Fret14__CWSca_ABNone_SPOval: THREE.Mesh
    Sides__Dread_Standard_Fret14__CWSca_ABStd: THREE.Mesh
    Sides__Dread_Standard_Fret14__CWVen: THREE.Mesh
    Sides__Dread_Standard_Fret14__CWVen_ABNone_SPOval: THREE.Mesh
    Sides__Dread_Standard_Fret14__CWVen_ABStd: THREE.Mesh
  }
  materials: {
    ['F_bee685e9c2024ab5a8ee3ee51ce988cc.012']: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Sides_Collection-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      SidesParlStandardFretCWNone: nodes.Sides__Parl_Standard_Fret12__CWNone,
      SidesParlStandardFretCWVen: nodes.Sides__Parl_Standard_Fret12__CWVen,
      SidesParlStandardFretCWFlo: nodes.Sides__Parl_Standard_Fret12__CWFlo,
      SidesParlStandardFretCWScal: nodes.Sides__Parl_Standard_Fret12__CWScal,
      SidesParlStandardFretCWNoneABStd: nodes.Sides__Parl_Standard_Fret12__CWNone_ABStd,
      SidesParlStandardFretCWFloABStd: nodes.Sides__Parl_Standard_Fret12__CWFlo_ABStd,
      SidesParlStandardFretCWVenABStd: nodes.Sides__Parl_Standard_Fret12__CWVen_ABStd,
      SidesParlStandardFretCWScalABStd: nodes.Sides__Parl_Standard_Fret12__CW_Scal_AB_Std,
      SidesDreadThinlineFretCWFlo: nodes.Sides__Dread_Thinline_Fret14__CWFlo,
      SidesDreadThinlineFretCWFloABNoneSPOval: nodes.Sides__Dread_Thinline_Fret14__CWFlo_ABNone_SPOval__1_,
      SidesDreadThinlineFretCWFloABStd: nodes.Sides__Dread_Thinline_Fret14__CWFlo_ABStd,
      SidesDreadThinlineFretCWNone: nodes.Sides__Dread_Thinline_Fret14__CWNone,
      SidesDreadThinlineFretCWNoneABNoneSPOval: nodes.Sides__Dread_Thinline_Fret14__CWNone_ABNone_SPOval,
      SidesDreadThinlineFretCWNoneABStd: nodes.Sides__Dread_Thinline_Fret14__CWNone_ABStd,
      SidesDreadThinlineFretCWSca: nodes.Sides__Dread_Thinline_Fret14__CWSca,
      SidesDreadThinlineFretCWScaABNoneSPOval: nodes.Sides__Dread_Thinline_Fret14__CWSca_ABNone_SPOval,
      SidesDreadThinlineFretCWScaABStd: nodes.Sides__Dread_Thinline_Fret14__CWSca_ABStd,
      SidesDreadThinlineFretCWVen: nodes.Sides__Dread_Thinline_Fret14__CWVen,
      SidesDreadThinlineFretCWVenABNoneSPOval: nodes.Sides__Dread_Thinline_Fret14__CWVen_ABNone_SPOval,
      SidesDreadThinlineFretCWVenABStd: nodes.Sides__Dread_Thinline_Fret14__CWVen_ABStd,
      SidesParlStandardFretCWFloABNoneSPOval: nodes.Sides__Parl_Standard_Fret14__CWFlo_ABNone_SPOval__1_,
      SidesParlStandardFretCWNone1: nodes.Sides__Parl_Standard_Fret14__CWNone,
      SidesParlStandardFretCWNoneABNoneSPOval: nodes.Sides__Parl_Standard_Fret14__CWNone_ABNone_SPOval,
      SidesParlStandardFretCWScaABNoneSPOval: nodes.Sides__Parl_Standard_Fret14__CWSca_ABNone_SPOval,
      SidesParlStandardFretCWScaABStd: nodes.Sides__Parl_Standard_Fret14__CWSca_ABStd,
      SidesParlStandardFretCWVenABNoneSPOval: nodes.Sides__Parl_Standard_Fret14__CWVen_ABNone_SPOval,
      SidesDreadThinlineFretCWNone1: nodes.Sides__Dread_Thinline_Fret12__CWNone,
      SidesDreadThinlineFretCWVen1: nodes.Sides__Dread_Thinline_Fret12__CWVen,
      SidesDreadThinlineFretCWFlo1: nodes.Sides__Dread_Thinline_Fret12__CWFlo,
      SidesDreadThinlineFretCWScal: nodes.Sides__Dread_Thinline_Fret12__CWScal,
      SidesDreadThinlineFretCWNoneABStd1: nodes.Sides__Dread_Thinline_Fret12__CWNone_ABStd,
      SidesDreadThinlineFretCWFloABStd1: nodes.Sides__Dread_Thinline_Fret12__CWFlo_ABStd,
      SidesDreadThinlineFretCWVenABStd1: nodes.Sides__Dread_Thinline_Fret12__CWVen_ABStd,
      SidesDreadThinlineFretCWScaABStd1: nodes.Sides__Dread_Thinline_Fret12__CWSca_ABStd,
      SidesParlThinlineFretCWFloABNoneSPOval: nodes.Sides__Parl_Thinline_Fret14__CWFlo_ABNone_SPOval__1_,
      SidesParlThinlineFretCWNone: nodes.Sides__Parl_Thinline_Fret14__CWNone,
      SidesParlThinlineFretCWNoneABNoneSPOval: nodes.Sides__Parl_Thinline_Fret14__CWNone_ABNone_SPOval,
      SidesParlThinlineFretCWScaABNoneSPOval: nodes.Sides__Parl_Thinline_Fret14__CWSca_ABNone_SPOval,
      SidesParlThinlineFretCWScaABStd: nodes.Sides__Parl_Thinline_Fret14__CWSca_ABStd,
      SidesParlThinlineFretCWVenABNoneSPOval: nodes.Sides__Parl_Thinline_Fret14__CWVen_ABNone_SPOval,
      SidesDreadStandardFretCWNone: nodes.Sides__Dread_Standard_Fret12__CWNone,
      SidesDreadStandardFretCWVen: nodes.Sides__Dread_Standard_Fret12__CWVen,
      SidesDreadStandardFretCWFlo: nodes.Sides__Dread_Standard_Fret12__CWFlo,
      SidesDreadStandardFretCWScal: nodes.Sides__Dread_Standard_Fret12__CWScal,
      SidesDreadStandardFretCWNoneABStd: nodes.Sides__Dread_Standard_Fret12__CWNone_ABStd,
      SidesDreadStandardFretCWFloABStd: nodes.Sides__Dread_Standard_Fret12__CWFlo_ABStd,
      SidesDreadStandardFretCWVenABStd: nodes.Sides__Dread_Standard_Fret12__CWVen_ABStd,
      SidesDreadStandardFretCWScalABStd: nodes.Sides__Dread_Standard_Fret12__CW_Scal_AB_Std,
      SidesParlThinlineFretCWNone1: nodes.Sides__Parl_Thinline_Fret12__CWNone,
      SidesParlThinlineFretCWVen: nodes.Sides__Parl_Thinline_Fret12__CWVen,
      SidesParlThinlineFretCWFlo: nodes.Sides__Parl_Thinline_Fret12__CWFlo,
      SidesParlThinlineFretCWScal: nodes.Sides__Parl_Thinline_Fret12__CWScal,
      SidesParlThinlineFretCWNoneABStd: nodes.Sides__Parl_Thinline_Fret12__CWNone_ABStd,
      SidesParlThinlineFretCWFloABStd: nodes.Sides__Parl_Thinline_Fret12__CWFlo_ABStd,
      SidesParlThinlineFretCWVenABStd: nodes.Sides__Parl_Thinline_Fret12__CWVen_ABStd,
      SidesParlThinlineFretCWScalABStd: nodes.Sides__Parl_Thinline_Fret12__CW_Scal_AB_Std,
      SidesDreadStandardFretCWFlo1: nodes.Sides__Dread_Standard_Fret14__CWFlo,
      SidesDreadStandardFretCWFloABNoneSPOval: nodes.Sides__Dread_Standard_Fret14__CWFlo_ABNone_SPOval__1_,
      SidesDreadStandardFretCWFloABStd1: nodes.Sides__Dread_Standard_Fret14__CWFlo_ABStd,
      SidesDreadStandardFretCWNone1: nodes.Sides__Dread_Standard_Fret14__CWNone,
      SidesDreadStandardFretCWNoneABNoneSPOval: nodes.Sides__Dread_Standard_Fret14__CWNone_ABNone_SPOval,
      SidesDreadStandardFretCWNoneABStd1: nodes.Sides__Dread_Standard_Fret14__CWNone_ABStd,
      SidesDreadStandardFretCWSca: nodes.Sides__Dread_Standard_Fret14__CWSca,
      SidesDreadStandardFretCWScaABNoneSPOval: nodes.Sides__Dread_Standard_Fret14__CWSca_ABNone_SPOval,
      SidesDreadStandardFretCWScaABStd: nodes.Sides__Dread_Standard_Fret14__CWSca_ABStd,
      SidesDreadStandardFretCWVen1: nodes.Sides__Dread_Standard_Fret14__CWVen,
      SidesDreadStandardFretCWVenABNoneSPOval: nodes.Sides__Dread_Standard_Fret14__CWVen_ABNone_SPOval,
      SidesDreadStandardFretCWVenABStd1: nodes.Sides__Dread_Standard_Fret14__CWVen_ABStd,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.SidesParlStandardFretCWNone name="Sides__Parl_Standard_Fret12__CWNone" userData={{ name: 'Sides__Parl_Standard_Fret12__CWNone' }} />
      <instances.SidesParlStandardFretCWVen name="Sides__Parl_Standard_Fret12__CWVen" userData={{ name: 'Sides__Parl_Standard_Fret12__CWVen' }} />
      <instances.SidesParlStandardFretCWFlo name="Sides__Parl_Standard_Fret12__CWFlo" userData={{ name: 'Sides__Parl_Standard_Fret12__CWFlo' }} />
      <instances.SidesParlStandardFretCWScal name="Sides__Parl_Standard_Fret12__CWScal" userData={{ name: 'Sides__Parl_Standard_Fret12__CWScal' }} />
      <instances.SidesParlStandardFretCWNoneABStd name="Sides__Parl_Standard_Fret12__CWNone_ABStd" userData={{ name: 'Sides__Parl_Standard_Fret12__CWNone_ABStd' }} />
      <instances.SidesParlStandardFretCWFloABStd name="Sides__Parl_Standard_Fret12__CWFlo_ABStd" userData={{ name: 'Sides__Parl_Standard_Fret12__CWFlo_ABStd' }} />
      <instances.SidesParlStandardFretCWVenABStd name="Sides__Parl_Standard_Fret12__CWVen_ABStd" userData={{ name: 'Sides__Parl_Standard_Fret12__CWVen_ABStd' }} />
      <instances.SidesParlStandardFretCWScalABStd name="Sides__Parl_Standard_Fret12__CW_Scal_AB_Std" userData={{ name: 'Sides__Parl_Standard_Fret12__CW_Scal_AB_Std' }} />
      <instances.SidesDreadThinlineFretCWFlo name="Sides__Dread_Thinline_Fret14__CWFlo" userData={{ name: 'Sides__Dread_Thinline_Fret14__CWFlo' }} />
      <instances.SidesDreadThinlineFretCWFloABNoneSPOval name="Sides__Dread_Thinline_Fret14__CWFlo_ABNone_SPOval__1_" userData={{ name: 'Sides__Dread_Thinline_Fret14__CWFlo_ABNone_SPOval__1_' }} />
      <instances.SidesDreadThinlineFretCWFloABStd name="Sides__Dread_Thinline_Fret14__CWFlo_ABStd" userData={{ name: 'Sides__Dread_Thinline_Fret14__CWFlo_ABStd' }} />
      <instances.SidesDreadThinlineFretCWNone name="Sides__Dread_Thinline_Fret14__CWNone" userData={{ name: 'Sides__Dread_Thinline_Fret14__CWNone' }} />
      <instances.SidesDreadThinlineFretCWNoneABNoneSPOval name="Sides__Dread_Thinline_Fret14__CWNone_ABNone_SPOval" userData={{ name: 'Sides__Dread_Thinline_Fret14__CWNone_ABNone_SPOval' }} />
      <instances.SidesDreadThinlineFretCWNoneABStd name="Sides__Dread_Thinline_Fret14__CWNone_ABStd" userData={{ name: 'Sides__Dread_Thinline_Fret14__CWNone_ABStd' }} />
      <instances.SidesDreadThinlineFretCWSca name="Sides__Dread_Thinline_Fret14__CWSca" userData={{ name: 'Sides__Dread_Thinline_Fret14__CWSca' }} />
      <instances.SidesDreadThinlineFretCWScaABNoneSPOval name="Sides__Dread_Thinline_Fret14__CWSca_ABNone_SPOval" userData={{ name: 'Sides__Dread_Thinline_Fret14__CWSca_ABNone_SPOval' }} />
      <instances.SidesDreadThinlineFretCWScaABStd name="Sides__Dread_Thinline_Fret14__CWSca_ABStd" userData={{ name: 'Sides__Dread_Thinline_Fret14__CWSca_ABStd' }} />
      <instances.SidesDreadThinlineFretCWVen name="Sides__Dread_Thinline_Fret14__CWVen" userData={{ name: 'Sides__Dread_Thinline_Fret14__CWVen' }} />
      <instances.SidesDreadThinlineFretCWVenABNoneSPOval name="Sides__Dread_Thinline_Fret14__CWVen_ABNone_SPOval" userData={{ name: 'Sides__Dread_Thinline_Fret14__CWVen_ABNone_SPOval' }} />
      <instances.SidesDreadThinlineFretCWVenABStd name="Sides__Dread_Thinline_Fret14__CWVen_ABStd" userData={{ name: 'Sides__Dread_Thinline_Fret14__CWVen_ABStd' }} />
      <instances.SidesParlStandardFretCWFloABNoneSPOval name="Sides__Parl_Standard_Fret14__CWFlo_ABNone_SPOval__1_" userData={{ name: 'Sides__Parl_Standard_Fret14__CWFlo_ABNone_SPOval__1_' }} />
      <instances.SidesParlStandardFretCWNone1 name="Sides__Parl_Standard_Fret14__CWNone" userData={{ name: 'Sides__Parl_Standard_Fret14__CWNone' }} />
      <instances.SidesParlStandardFretCWNoneABNoneSPOval name="Sides__Parl_Standard_Fret14__CWNone_ABNone_SPOval" userData={{ name: 'Sides__Parl_Standard_Fret14__CWNone_ABNone_SPOval' }} />
      <instances.SidesParlStandardFretCWScaABNoneSPOval name="Sides__Parl_Standard_Fret14__CWSca_ABNone_SPOval" userData={{ name: 'Sides__Parl_Standard_Fret14__CWSca_ABNone_SPOval' }} />
      <instances.SidesParlStandardFretCWScaABStd name="Sides__Parl_Standard_Fret14__CWSca_ABStd" userData={{ name: 'Sides__Parl_Standard_Fret14__CWSca_ABStd' }} />
      <instances.SidesParlStandardFretCWVenABNoneSPOval name="Sides__Parl_Standard_Fret14__CWVen_ABNone_SPOval" userData={{ name: 'Sides__Parl_Standard_Fret14__CWVen_ABNone_SPOval' }} />
      <instances.SidesDreadThinlineFretCWNone1 name="Sides__Dread_Thinline_Fret12__CWNone" userData={{ name: 'Sides__Dread_Thinline_Fret12__CWNone' }} />
      <instances.SidesDreadThinlineFretCWVen1 name="Sides__Dread_Thinline_Fret12__CWVen" userData={{ name: 'Sides__Dread_Thinline_Fret12__CWVen' }} />
      <instances.SidesDreadThinlineFretCWFlo1 name="Sides__Dread_Thinline_Fret12__CWFlo" userData={{ name: 'Sides__Dread_Thinline_Fret12__CWFlo' }} />
      <instances.SidesDreadThinlineFretCWScal name="Sides__Dread_Thinline_Fret12__CWScal" userData={{ name: 'Sides__Dread_Thinline_Fret12__CWScal' }} />
      <instances.SidesDreadThinlineFretCWNoneABStd1 name="Sides__Dread_Thinline_Fret12__CWNone_ABStd" userData={{ name: 'Sides__Dread_Thinline_Fret12__CWNone_ABStd' }} />
      <instances.SidesDreadThinlineFretCWFloABStd1 name="Sides__Dread_Thinline_Fret12__CWFlo_ABStd" userData={{ name: 'Sides__Dread_Thinline_Fret12__CWFlo_ABStd' }} />
      <instances.SidesDreadThinlineFretCWVenABStd1 name="Sides__Dread_Thinline_Fret12__CWVen_ABStd" userData={{ name: 'Sides__Dread_Thinline_Fret12__CWVen_ABStd' }} />
      <instances.SidesDreadThinlineFretCWScaABStd1 name="Sides__Dread_Thinline_Fret12__CWSca_ABStd" userData={{ name: 'Sides__Dread_Thinline_Fret12__CWSca_ABStd' }} />
      <instances.SidesParlThinlineFretCWFloABNoneSPOval name="Sides__Parl_Thinline_Fret14__CWFlo_ABNone_SPOval__1_" userData={{ name: 'Sides__Parl_Thinline_Fret14__CWFlo_ABNone_SPOval__1_' }} />
      <instances.SidesParlThinlineFretCWNone name="Sides__Parl_Thinline_Fret14__CWNone" userData={{ name: 'Sides__Parl_Thinline_Fret14__CWNone' }} />
      <instances.SidesParlThinlineFretCWNoneABNoneSPOval name="Sides__Parl_Thinline_Fret14__CWNone_ABNone_SPOval" userData={{ name: 'Sides__Parl_Thinline_Fret14__CWNone_ABNone_SPOval' }} />
      <instances.SidesParlThinlineFretCWScaABNoneSPOval name="Sides__Parl_Thinline_Fret14__CWSca_ABNone_SPOval" userData={{ name: 'Sides__Parl_Thinline_Fret14__CWSca_ABNone_SPOval' }} />
      <instances.SidesParlThinlineFretCWScaABStd name="Sides__Parl_Thinline_Fret14__CWSca_ABStd" userData={{ name: 'Sides__Parl_Thinline_Fret14__CWSca_ABStd' }} />
      <instances.SidesParlThinlineFretCWVenABNoneSPOval name="Sides__Parl_Thinline_Fret14__CWVen_ABNone_SPOval" userData={{ name: 'Sides__Parl_Thinline_Fret14__CWVen_ABNone_SPOval' }} />
      <instances.SidesDreadStandardFretCWNone name="Sides__Dread_Standard_Fret12__CWNone" userData={{ name: 'Sides__Dread_Standard_Fret12__CWNone' }} />
      <instances.SidesDreadStandardFretCWVen name="Sides__Dread_Standard_Fret12__CWVen" userData={{ name: 'Sides__Dread_Standard_Fret12__CWVen' }} />
      <instances.SidesDreadStandardFretCWFlo name="Sides__Dread_Standard_Fret12__CWFlo" userData={{ name: 'Sides__Dread_Standard_Fret12__CWFlo' }} />
      <instances.SidesDreadStandardFretCWScal name="Sides__Dread_Standard_Fret12__CWScal" userData={{ name: 'Sides__Dread_Standard_Fret12__CWScal' }} />
      <instances.SidesDreadStandardFretCWNoneABStd name="Sides__Dread_Standard_Fret12__CWNone_ABStd" userData={{ name: 'Sides__Dread_Standard_Fret12__CWNone_ABStd' }} />
      <instances.SidesDreadStandardFretCWFloABStd name="Sides__Dread_Standard_Fret12__CWFlo_ABStd" userData={{ name: 'Sides__Dread_Standard_Fret12__CWFlo_ABStd' }} />
      <instances.SidesDreadStandardFretCWVenABStd name="Sides__Dread_Standard_Fret12__CWVen_ABStd" userData={{ name: 'Sides__Dread_Standard_Fret12__CWVen_ABStd' }} />
      <instances.SidesDreadStandardFretCWScalABStd name="Sides__Dread_Standard_Fret12__CW_Scal_AB_Std" userData={{ name: 'Sides__Dread_Standard_Fret12__CW_Scal_AB_Std' }} />
      <instances.SidesParlThinlineFretCWNone1 name="Sides__Parl_Thinline_Fret12__CWNone" userData={{ name: 'Sides__Parl_Thinline_Fret12__CWNone' }} />
      <instances.SidesParlThinlineFretCWVen name="Sides__Parl_Thinline_Fret12__CWVen" userData={{ name: 'Sides__Parl_Thinline_Fret12__CWVen' }} />
      <instances.SidesParlThinlineFretCWFlo name="Sides__Parl_Thinline_Fret12__CWFlo" userData={{ name: 'Sides__Parl_Thinline_Fret12__CWFlo' }} />
      <instances.SidesParlThinlineFretCWScal name="Sides__Parl_Thinline_Fret12__CWScal" userData={{ name: 'Sides__Parl_Thinline_Fret12__CWScal' }} />
      <instances.SidesParlThinlineFretCWNoneABStd name="Sides__Parl_Thinline_Fret12__CWNone_ABStd" userData={{ name: 'Sides__Parl_Thinline_Fret12__CWNone_ABStd' }} />
      <instances.SidesParlThinlineFretCWFloABStd name="Sides__Parl_Thinline_Fret12__CWFlo_ABStd" userData={{ name: 'Sides__Parl_Thinline_Fret12__CWFlo_ABStd' }} />
      <instances.SidesParlThinlineFretCWVenABStd name="Sides__Parl_Thinline_Fret12__CWVen_ABStd" userData={{ name: 'Sides__Parl_Thinline_Fret12__CWVen_ABStd' }} />
      <instances.SidesParlThinlineFretCWScalABStd name="Sides__Parl_Thinline_Fret12__CW_Scal_AB_Std" userData={{ name: 'Sides__Parl_Thinline_Fret12__CW_Scal_AB_Std' }} />
      <instances.SidesDreadStandardFretCWFlo1 name="Sides__Dread_Standard_Fret14__CWFlo" userData={{ name: 'Sides__Dread_Standard_Fret14__CWFlo' }} />
      <instances.SidesDreadStandardFretCWFloABNoneSPOval name="Sides__Dread_Standard_Fret14__CWFlo_ABNone_SPOval__1_" userData={{ name: 'Sides__Dread_Standard_Fret14__CWFlo_ABNone_SPOval__1_' }} />
      <instances.SidesDreadStandardFretCWFloABStd1 name="Sides__Dread_Standard_Fret14__CWFlo_ABStd" userData={{ name: 'Sides__Dread_Standard_Fret14__CWFlo_ABStd' }} />
      <instances.SidesDreadStandardFretCWNone1 name="Sides__Dread_Standard_Fret14__CWNone" userData={{ name: 'Sides__Dread_Standard_Fret14__CWNone' }} />
      <instances.SidesDreadStandardFretCWNoneABNoneSPOval name="Sides__Dread_Standard_Fret14__CWNone_ABNone_SPOval" userData={{ name: 'Sides__Dread_Standard_Fret14__CWNone_ABNone_SPOval' }} />
      <instances.SidesDreadStandardFretCWNoneABStd1 name="Sides__Dread_Standard_Fret14__CWNone_ABStd" userData={{ name: 'Sides__Dread_Standard_Fret14__CWNone_ABStd' }} />
      <instances.SidesDreadStandardFretCWSca name="Sides__Dread_Standard_Fret14__CWSca" userData={{ name: 'Sides__Dread_Standard_Fret14__CWSca' }} />
      <instances.SidesDreadStandardFretCWScaABNoneSPOval name="Sides__Dread_Standard_Fret14__CWSca_ABNone_SPOval" userData={{ name: 'Sides__Dread_Standard_Fret14__CWSca_ABNone_SPOval' }} />
      <instances.SidesDreadStandardFretCWScaABStd name="Sides__Dread_Standard_Fret14__CWSca_ABStd" userData={{ name: 'Sides__Dread_Standard_Fret14__CWSca_ABStd' }} />
      <instances.SidesDreadStandardFretCWVen1 name="Sides__Dread_Standard_Fret14__CWVen" userData={{ name: 'Sides__Dread_Standard_Fret14__CWVen' }} />
      <instances.SidesDreadStandardFretCWVenABNoneSPOval name="Sides__Dread_Standard_Fret14__CWVen_ABNone_SPOval" userData={{ name: 'Sides__Dread_Standard_Fret14__CWVen_ABNone_SPOval' }} />
      <instances.SidesDreadStandardFretCWVenABStd1 name="Sides__Dread_Standard_Fret14__CWVen_ABStd" userData={{ name: 'Sides__Dread_Standard_Fret14__CWVen_ABStd' }} />
    </group>
  )
}

useGLTF.preload('/Sides_Collection-transformed.glb')
