/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Back_Strips_Collection.glb --types --transform --instanceall --keepmeshes --keepmaterials --keepattributes --keepnames --draco --meta --shadows --exportdefault --output ./src/_generated/LuthBackStrips.tsx 
Files: ./public/Back_Strips_Collection.glb [31.73KB] > /Users/samsoedien/Documents/Repositories/project-luth/apps/common/src/_generated/Back_Strips_Collection-transformed.glb [7.4KB] (77%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Body_Back_Center_Strip: THREE.Mesh
    Body_Back_Center_Strip__1_: THREE.Mesh
    Body_Back_Double_Strip_Left: THREE.Mesh
    Body_Back_Double_Strip_Right__1_: THREE.Mesh
    Body_Center_Back_Strip: THREE.Mesh
    Body_Double_Back_Strip_Left: THREE.Mesh
    Body_Double_Back_Strip_Right: THREE.Mesh
  }
  materials: {
    ['F_fe865806f74f44db9b4c67623d1ad385.005']: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Back_Strips_Collection-transformed.glb') as GLTFResult
  const instances = React.useMemo(
    () => ({
      BodyBackCenterStrip: nodes.Body_Back_Center_Strip,
      BodyBackDoubleStripLeft: nodes.Body_Back_Double_Strip_Left,
      BodyBackDoubleStripRight: nodes.Body_Back_Double_Strip_Right__1_,
      BodyCenterBackStrip: nodes.Body_Center_Back_Strip,
      BodyDoubleBackStripLeft: nodes.Body_Double_Back_Strip_Left,
      BodyDoubleBackStripRight: nodes.Body_Double_Back_Strip_Right,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances: ContextType) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.BodyBackCenterStrip name="Body_Back_Center_Strip" userData={{ name: 'Body_Back_Center_Strip' }} />
      <instances.BodyBackCenterStrip name="Body_Back_Center_Strip__1_" userData={{ name: 'Body_Back_Center_Strip__1_' }} />
      <instances.BodyBackDoubleStripLeft name="Body_Back_Double_Strip_Left" userData={{ name: 'Body_Back_Double_Strip_Left' }} />
      <instances.BodyBackDoubleStripRight name="Body_Back_Double_Strip_Right__1_" userData={{ name: 'Body_Back_Double_Strip_Right__1_' }} />
      <instances.BodyCenterBackStrip name="Body_Center_Back_Strip" userData={{ name: 'Body_Center_Back_Strip' }} />
      <instances.BodyDoubleBackStripLeft name="Body_Double_Back_Strip_Left" userData={{ name: 'Body_Double_Back_Strip_Left' }} />
      <instances.BodyDoubleBackStripRight name="Body_Double_Back_Strip_Right" userData={{ name: 'Body_Double_Back_Strip_Right' }} />
    </group>
  )
}

useGLTF.preload('/Back_Strips_Collection-transformed.glb')
