import '~/styles/main.css'

import { Inter } from 'next/font/google'

import { ThemeProvider } from '../theme/provider/theme-provider'
import { TRPCReactProvider } from '~/trpc/react'
import { getServerAuthSession } from '~/server/auth'
import Footer from '~/components/footer/footer'
import Header from '~/components/header/header'

// import { GridProvider } from '@project-luth/core'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata = {
  title: 'Project Luth',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerAuthSession()

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* <GridProvider> */}
            <div className="relative mx-auto min-h-screen max-w-[1440px]">
              <Header session={session} />
              <main className="min-h-screen">{children}</main>
              <Footer />
            </div>
            {/* </GridProvider> */}
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  )
}
