import '~/styles/main.css'

// import { Inter, Poppins } from 'next/font/google'

import { GeistSans } from 'geist/font/sans'
// import { GeistMono } from 'geist/font/mono'

import { ThemeProvider } from '../theme/provider/theme-provider'
import { TRPCReactProvider } from '~/trpc/react'
import Footer from '~/app/_components/footer/footer'
import Header from '~/app/_components/header/header'
import { api } from '~/trpc/server'

import { auth } from '~/auth'

// import { GridProvider } from '@project-luth/core'

// const inter = Inter({
//   subsets: ['latin'],
//   variable: '--font-sans',
// })

// const poppins = Poppins({
//   subsets: ['latin'],
//   weight: ['400', '500', '600', '700', '800', '900'],
//   variable: '--font-sans',
// })

export const metadata = {
  title: 'Project Luth',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth()
  let profile

  if (session?.user) {
    profile = await api.user.getProfile.query()
  }

  return (
    <html lang="en" suppressHydrationWarning={true}>
      {/* <body className={`font-sans ${poppins.variable}`}> */}
      <body className={GeistSans.className}>
        <TRPCReactProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* <GridProvider> */}
            <div className="bg-muted/40 relative min-h-screen w-full">
              <div className="bg-background mx-auto max-w-[1440px] ">
                <Header session={session} profilePhoto={profile?.image ?? ''} />
                <main className="min-h-screen ">{children}</main>

                <Footer />
              </div>
            </div>
            {JSON.stringify(session)}
            {/* </GridProvider> */}
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  )
}
