# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install

      - name: Run Linting
        run: yarn lint

      - name: Run Tests
        run: yarn test

      - name: Run Build
        run: yarn build

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker compose
        run: docker compose up
